### ISSUE TITLE
Calling `to_ary` in `flatten`

### ISSUE THREAD

**Issue by joshvoigts** [ohler55/ox#102]
I'm running into an issue upgrading ox from 2.0.6 (ruby 1.9.3-p392) to 2.1.3 (ruby 2.1.3). It looks like the `id` coming into `respond_to?` is `to_ary`. So I'm assuming `flatten` is calling `to_ary` at some point and messing things up.

    /Users/jv/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ox-2.1.3/lib/ox/element.rb:168:in `block in respond_to?': undefined method `value' for " ":String (NoMethodError)
       from /Users/jv/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ox-2.1.3/lib/ox/element.rb:167:in `each'
       from /Users/jv/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ox-2.1.3/lib/ox/element.rb:167:in `respond_to?'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:117:in `flatten'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:117:in `process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:350:in `convert_r'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:104:in `convert_element'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:88:in `process_node'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `block in process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `map'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:296:in `convert_p'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:104:in `convert_element'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:88:in `process_node'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `block in process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `map'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:261:in `convert_body'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:104:in `convert_element'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:88:in `process_node'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `block in process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `map'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:112:in `process_nodes'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:176:in `convert_document'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:104:in `convert_element'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:88:in `process_node'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:164:in `convert_source'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:86:in `process_node'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:77:in `convert!'
       from /Users/jv/Desktop/Dropbox/word_to_icml/converter.rb:24:in `convert'
       from /Users/jv/bin/word_to_icml:58:in `block in <main>'
       from /Users/jv/bin/word_to_icml:37:in `each'
       from /Users/jv/bin/word_to_icml:37:in `<main>'

**Comment by ohler55** [comment]
no response, closing

**Comment by joshvoigts** [comment]
Sorry, I don't seem to have the example anymore.

**Comment by ohler55** [comment]
If you come up with the problem again we can reopen the issue.
