### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by valtri** [ohler55/ox#104]
I'm packaging ox gem for Fedora. There are mentioned MIT and GPLv3 licenses in gemfile, but the license text in the sources is BSD 3-clause license. Either gemfile would need to be fixed or license text replaced.

Which is the right license for ox?

If you would want to keep the "no advertisement" clause in the license text (=keeping the BSD license), you could fix the gemspec with s.license=['BSD']. But maybe you wanted to change the license of ox to the ones mentioned in the issue #77?

Thanks.

**Comment by ohler55** [comment]
Ok to close?

**Comment by valtri** [comment]
Yes, it can be closed. Thanks!
