### ISSUE TITLE
Sax parsing of nodes with whitespace

### ISSUE THREAD

**Issue by mindreframer** [ohler55/ox#105]
# in sax_test.rb

      # I really need the space to be present and passed to `text` -callback,
      # is there a options combination, that would make it work?
      def test_sax_only_whitespace
        parse_compare(%{<top> </top>},
                      [[:start_element, :top],
                       [:text, " "],
                       [:end_element, :top]
                      ], AllSax,
                      #:convert_special => true,
                      #:smart => true,
                      #:mode => :generic,
                      :skip => :skip_none,
                    )
      end

      
     1) Failure:
    test_sax_only_whitespace(SaxBaseTest) [/Users/roman/Desktop/sand/ox/test/sax/helpers.rb:33]:
    <[[:start_element, :top], [:text, " "], [:end_element, :top]]> expected but was
    <[[:start_element, :top], [:end_element, :top]]>.

As you can see from the error message the `text`-callback was skipped.... this causes problems for excel parsing, where I have a shared string, that is a space char, that since it is skipped, the resulting array has wrong indicies for all following entries.... 
I'm using this gem: 
https://github.com/gbiczo/oxcelix and this is the line: 
https://github.com/gbiczo/oxcelix/blob/master/lib/oxcelix/workbook.rb#L217

Any hope that there is a parameters combination that works??? I have tried every possible permutation for the :skip parameter.... :sob:

**Comment by ohler55** [comment]
I'll check it this weekend. I can't make any promises for the other gems but I'll make sure Ox is doing what is expected.

**Comment by ohler55** [comment]
If you have a small sample XML I can test against that would be great otherwise I'll assume <foo></foo>.

**Comment by mindreframer** [comment]
Hey Peter, thanks for fast response,  here is a shortened xml with the critical node: 

        <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
        <sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="45" uniqueCount="7">
            <si>
                <t>monthly</t>
            </si>
            <si>
                <t>NPS</t>
            </si>
            <si>
                <t>WebAnalytics</t>
            </si>
            <si>
                <t xml:space="preserve"> </t>
            </si>
            <si>
                <t>Unit</t>
            </si>
            <si>
                <t>%</t>
            </si>
            <si>
                <t xml:space="preserve">Total </t>
            </si>
        </sst>



this is the node, that is ignored: 

      <t xml:space="preserve"> </t>


After this all the indices are skewed by -1 ...

**Comment by ohler55** [comment]
I just merged a branch that I believe fixes the problem in the correct way. Let me know what you think.

**Comment by mindreframer** [comment]
@ohler55 This looks great! Works for me too! Would love to see this released soon(-ish), but I see you're also working on the 2.2 GC bug.... Does it make sense to release this fix separately? If it's too much hasle and the 2.2 GC wont take you weeks fix, it could wait a bit... 
Thx for the fix!

**Comment by ohler55** [comment]
Let me decide this weekend. If I can not get it released this weekend I'll make it two releases.

**Comment by mindreframer** [comment]
cool, thx a lot!

**Comment by ohler55** [comment]
Ready to release. Just need a few people to check the GC issue.

**Comment by mindreframer** [comment]
Great, waiting for the release!

**Comment by ohler55** [comment]
Did the recent release take care of the issue?

**Comment by mindreframer** [comment]
@ohler55 Yes, it did! Did a pull request to oxcelix and waiting for the maintainer to merge. But this issue here can be closed! Thx again for the fix!
