### ISSUE TITLE
Viewing progress

### ISSUE THREAD

**Issue by harmdewit** [ohler55/ox#107]
I would like to see the progress of the SAX parser. Is there a way to get the bytes count read during parsing?

I tried using the line count as progress indicator, but many xml files are formed as a single concatenated line. Next i tried reading the column size, but I couldn't find a good way to get it. I would think that using the bytes count read during parsing would return the most reliable results.

Thanks b.t.w. for this gem. We're using it happily for more than a year now. I would just like to add some monitoring.

**Comment by ohler55** [comment]
If your handler has a @line and @column then they should be set by the parser as it parses the file. That will not give a byte could but it provide some indication of progress. Is that enough for you?

Outside of Ox you could also subclass an IO object to count bytes read. That will only be as accurate for when bytes are pulled from the source and not when they are parsed though.

**Comment by ohler55** [comment]
Any comments?

**Comment by harmdewit** [comment]
I would like to use the column count, but i don't think there is an easy way to find the total column count of a file before reading it.

I'm going to try to read the bytes count read, when i have a solution i'll post it here. There's no rush so i'll close the issue for now.
