### ISSUE TITLE
Ox::ParseError: invalid format, elements overlap at ...

### ISSUE THREAD

**Issue by yeban** [ohler55/ox#111]
I was hoping you could help me understand the following issue raised by Ox: `Ox::ParseError: invalid format, elements overlap at line 962, column 26 [parse.c:561]`

I have posted the problematic XML and 2 lines to reproduce this error in a gist - https://gist.github.com/yeban/b6a2c8fd082acc3e1371

To run:

    $ wget https://gist.githubusercontent.com/yeban/b6a2c8fd082acc3e1371/raw/00712716215426180e01ed94e1866f79476c55f9/ox_invalid_format_elements_overlap.rb
    $ ruby ox_invalid_format_elements_overlap.rb

**Comment by yeban** [comment]
Ok. The error is probably because `<Iteration>` and `<Iteration_hits>` elements do not have a closing tag. So I'm wondering now if ox can be a bit accomodating in this case - like a flag I can set for the parsing to be lenient?

**Comment by ohler55** [comment]
You can use the :effort option set to :tolerant but in this case I don't think it will make much difference. The XML is very badly formed and other than using the indentation to guess are the structure there is no way of telling what the intended structure is. Try :tolerant and also :smart to true. It might make it through without errors but the resulting structure will not be what you expect.

**Comment by yeban** [comment]
Thanks @ohler55. Investigating the malformed XML led us to a deeper issue that we will try to address instead of patching it.

**Comment by ohler55** [comment]
good luck
