### ISSUE TITLE
How to parse/ignore JavaScript in HTML documents

### ISSUE THREAD

**Issue by derSascha** [ohler55/ox#112]
Hi,

the following HTML document can't be parsed by Ox:
```
<!DOCTYPE html>
<html>
  <head>
    <script type='text/javascript'>
      (function(c,d){return(c<d)?1:0;})(2,3);
    </script>
  </head>
  <body>
    <h1>123</h1>
  </body>
</html>
```

The JS code `c<d` results in trouble (Invalid Element: d). Is there a simple and fast way to ignore the script parts?

**Comment by ohler55** [comment]
There is a "smart" option for Ox. I will look into handling the <script> tag so that it deals with scripting contents better.

**Comment by ohler55** [comment]
Please check the current version on github. It is a candidate enhancement to jump over script elements. It isn't perfect but should handle cases where the user is not intentionally trying to trick it. Any more than this would require a script parser and I'm not ready to add that to Ox.

**Comment by derSascha** [comment]
Thanks, works perfectly! And i agree with you that ox should be a xml and not a script parser.
