### ISSUE TITLE
Locating elements based off of presence of child elements?

### ISSUE THREAD

**Issue by newbkaek** [ohler55/ox#113]
Is there any way to get a list of xml elements based on the presence/non-presence of a child element using ox?

Specifically I want to replicate the functionality of this XPath `//ELEMENT[not(CHILD)]`

Given this XML
```
<XML>
  <ELEMENT>
    <CHILD>Has child</CHILD>
  </ELEMENT>
  <ELEMENT>
    <OTHER>something</OTHER>
  </ELEMENT>
</XML>
```

It should only return the element with the "CHILD" element.
```
<ELEMENT>
  <OTHER>something</OTHER>
</ELEMENT>
```

**Comment by ohler55** [comment]
Ox has the locate() method but that is not XPath. As the docs indicate it is similar but not the same and should be considered a small subset of XPath. It does not support the options you described.

**Comment by newbkaek** [comment]
Thanks for the clarification!

Following on this, is it safe to assume that there is no support for match expressions? i.e.: `//ELEMENT[text() = 'blah']`

**Comment by ohler55** [comment]
I'm afraid it is not there. You will have to use ruby code instead.

**Comment by newbkaek** [comment]
Thanks!
