### ISSUE TITLE
Trace file position in SAX-parser

### ISSUE THREAD

**Issue by juskoljo** [ohler55/ox#115]
Hi Peter,

I would start using Ox for processing large XML files. Would it it be possible to add some file position (byte) trace methods to Ox::Sax? e.g. @offset_start, @offset_end for each event just like @column and @line.

Thanks in advance! :)

With best regards,
Jussi

**Comment by ohler55** [comment]
I will check on the feasibility and approach that might get you what you are looking for.

**Comment by juskoljo** [comment]
Great, thanks! :+1:

**Comment by ohler55** [comment]
Started looked at the feature request. I'm not sure I understand what you are asking for. I tested the sax_file parser and the line and column numbers seem to be correct. I added a unit test for it. Can you explain in more detail what you are looking for?

**Comment by ohler55** [comment]
Any reason I should not close this?

**Comment by take-five** [comment]
I guess author meant he wanted to track current byte offset, not column and line

**Comment by juskoljo** [comment]
Yes, that's correct as Alexey wrote. Sorry for the delayed answer, I've
been on holiday and away from computer.

I would like get current byte offset e.g. offset of "<" character in
start_element and offset of ">" with end_element.

Also length of current node string would be useful e.g. with <node
attr="1"> in start_element it would be 15.

I've implemented custom ORM that currently Nokigiri, however the
performance is quite bad and would love to switch to Ox. I have plans to
release this as open source some day if possible.

These improvements would help me a lot. There is also another improvement
suggestion regarding value callback when playing with large files (e.g.
node with file attachment), but I'll get back to you with that as new
feature request.

Thanks in advance,
Jussi

**Comment by ohler55** [comment]
I can add the offset from start of a string or file in bytes. Counting from the start of the elements gets a little more twisted as elements can be in other elements as can text. Since there are a fair number of variations on what would be considered correct I'd rather leave that to the caller. Byte offset will be set at the start of each element so it would be trivial for the caller to remember that value.

**Comment by ohler55** [comment]
I pushed a version to github that support a pos attribute that will be the position from the start. Let me know if it works for you.

**Comment by ohler55** [comment]
Decided to release 2.2.1. Hope it works for you.

**Comment by juskoljo** [comment]
Great! I'll give this a try when I'm back in business (from my summer vacation). Thanks again! :)
