### ISSUE TITLE
SAX Parser Crashes w/ Empty Node

### ISSUE THREAD

**Issue by ajrkerr** [ohler55/ox#120]
Hello,

Thanks for the great work with OX. I found a bug while working on an integration project and though I'd contribute a failing test case.  Unfortunately my C is a little weak otherwise I'd attempt to submit a pull request as well.

It looks like empty XML nodes are causing SAX to raise an exception in C, which is killing Ruby outright.  I am not attached to the error message provided, but would like an error of some kind to be provided so that ruby can handle the problem.

```ruby
# in test/sax/sax_test.rb
  def test_sax_empty_element_name
    parse_compare(%{<?xml version="1.0"?>
<top>
  <>
</top>},
                  [[:instruct, 'xml'],
                   [:attr, :version, "1.0"],
                   [:end_instruct, "xml"],
                   [:start_element, :top],
                   [:error, "Empty Element: element is invalid", 5, 3],
                   [:end_element, :top],
                  ])
  end
```

Thanks,

Adam

**Comment by ohler55** [comment]
Will check next week.

**Comment by ohler55** [comment]
I just push a version to github that fixes the problem. I also added your test with some modifications. Thanks. If it works for you I will make a release.

**Comment by ohler55** [comment]
Ox 2.2.2 released with the fix. No response here so closing.

**Comment by ajrkerr** [comment]
Thanks, everything looks good.  Appreciate you making the fix!

**Comment by ohler55** [comment]
Glad it works.
