### ISSUE TITLE
Error when parsing XML with entity in attribute value

### ISSUE THREAD

**Issue by trevorrowe** [ohler55/ox#121]
I've run across what appears to be a bug in how Ox deals with XML attributes that contain entity references. I ran into this when writing a SAX parser, but it also seems to affect document parsing too. Here is an example of how-to reproduce the issue.  Removing the `bad` attribute from the `oops` element  avoids the issue. It does not appear to cause an issue if the same entity reference is in the text of an element.

Example:

```ruby
require 'ox'
require 'stringio'

xml = <<-XML.strip
<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE example [
  <!ENTITY example "example-value">
]>
<xml>
  <works>&example;</works>
  <oops bad="&example;"></oops>
</xml>
XML

class SaxParser

  def attr(name, str); end

  def error(msg, line = nil, column = nil)
    raise "#{msg} on line #{line} at column #{column}"
  end

end

Ox.sax_parse(SaxParser.new, StringIO.new(xml), convert_special: true)
#=> raises RuntimeError: Not Terminated: special character does not end with a semicolon on line 7 at column 18

Ox.parse(xml)
#=> raises Ox::ParseError: invalid format, element not closed at line 8, column 4 [parse.c:443]
```

**Comment by ohler55** [comment]
I will look into it. Might be next week though.

**Comment by trevorrowe** [comment]
Thanks! Also, thanks for the excellent library and support. You do you a stellar job!

**Comment by ohler55** [comment]
Thanks :-)

**Comment by ohler55** [comment]
A little slow but working on it now. The sax parser is doing what I expected. It should raise an exception and it does. The regular parser does not and mangles the value. I will make it raise and exception also.

**Comment by ohler55** [comment]
Please try the version on github. If it looks ok I will release.

**Comment by ohler55** [comment]
Ox 2.2.2 released with the fix. No response here so closing.

**Comment by trevorrowe** [comment]
Sorry for the lack of a response. A quick followup question. Is there a reason the example should raise an error at all? Is it not valid to have xml entities in xml attribute values?

**Comment by ohler55** [comment]
&example; is not a valid character. If it was &lt; or something like that it would be fine. I believe the test case cover that.

**Comment by trevorrowe** [comment]
Given

```xml
<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE example [
  <!ENTITY example "example-value">
]>
<xml>
  <works>&example;</works>
  <oops bad="&example;"></oops>
</xml>
```

Isn't `&example;` valid as it was defined as an entity near the top?

**Comment by ohler55** [comment]
My apologies. I did not pay attention to that. Currently Ox does not support any entity elements in the doctype. It returns the whole doctype contents as a single string.

If your concern was more than academic and there is a need for registering new entities in what you are doing give me some more details and either you or I can create an issue for a new feature.

**Comment by trevorrowe** [comment]
I'll open the issue and give some more context. Thanks.
