### ISSUE TITLE
 Unexpected text at line 4, column 26 [obj_load.c:407]

### ISSUE THREAD

**Issue by giubueno** [ohler55/ox#123]
Hi,

I am reading a file and trying to parse it using Ox.parse_obj.

        xml = File.read(exif_file)
        objs = Ox.parse_obj(xml)

The XML content is ok. Can I help fix it if it is a bug? How?

Thanks,

**Comment by ohler55** [comment]
Was the xml file generated by Ox? If not then it can not be used with parse_obj. Can you provide the XML file or text?

**Comment by giubueno** [comment]
Okay, it wasn't generate by Ox. Is it possible to parse a generic XML with other method? Thanks!

**Comment by ohler55** [comment]
Simply use Ox.parse().
