### ISSUE TITLE
Ox.dump changes encoding of strings?

### ISSUE THREAD

**Issue by timting** [ohler55/ox#124]
I'm using Ox 2.2.1, and I noticed this behavior:

1. Create a new Ox::Document
2. Add an element that has UTF-8 specific characters (like 'Joël Brunet-Bélanger')
3. If you Ox.dump this document, the resultant string has ASCII-8BIT encoding, which results in errors when I try to write it to a file, since it's trying to convert something that's already UTF-8 into UTF-8.

Is this by design? I just wanted to understand why it's working the way it is. Currently, I'm just forcing the encoding of the resultant string to UTF-8; that seems like a reasonable workaround.

**Comment by ohler55** [comment]
It is by design. Ox default to what ever the Ruby default is. Ruby defaults to ASCII-8BIT. Thats no what most of the world uses so Ox has the option to change that. Either pass an :encoding option 'UTF-8' or set the default options use UTF-8 like this.
```` ruby
Ox.default_options = {:encoding => 'utf-8'}
```

**Comment by timting** [comment]
Ok - thanks for the help!
