### ISSUE TITLE
Adding to CPPFLAGS

### ISSUE THREAD

**Issue by mcarpenter** [ohler55/ox#125]
Hi,

I need to add to `CPPFLAGS` (`-fms-extensions` for a creaky old GCC, in order to understand anon unions in `sax_buf.h`) but I'm struggling to see how to do it. `mkmf` appears to ignore the exported environment variable of the same name.

I can work around this by adding a line like this to `extconf.rb`:

    $CPPFLAGS += ' ' + ENV['CPPFLAGS']

(just before `create_makefile()` is called) and re-packaging the gem but that's clearly not ideal. I'm a little surprised that extconf doesn't provide something similar natively, so perhaps I'm missing something?

**Comment by mcarpenter** [comment]
Another possibility is that the generated `Makefile` could take the environment variable into account but currently it generates a line like:

    CPPFLAGS =   -I/usr/local/include ...

rather than, say `CPPFLAGS+=...`. I don't know if extconf provides for this, though.

**Comment by ohler55** [comment]
Are the anonymous unions the only problem? If so I can make some code changes.

**Comment by mcarpenter** [comment]
Hmm, I _think_ so. Output from `gem install` is as follows (perhaps missing <strings.h> in a couple of places too):

    compiling gen_load.c
    compiling dump.c
    compiling err.c
    compiling cache.c
    compiling base64.c
    compiling sax_as.c
    In file included from sax.h:34:0,
                     from sax_as.c:44:
    sax_buf.h:51:6: warning: declaration does not declare anything
    compiling ox.c
    In file included from sax.h:34:0,
                     from ox.c:39:
    sax_buf.h:51:6: warning: declaration does not declare anything
    compiling sax_hint.c
    sax_hint.c: In function 'ox_hint_find':
    sax_hint.c:195:2: warning: implicit declaration of function 'strcasecmp'
    compiling special.c
    compiling cache8.c
    compiling parse.c
    parse.c: In function 'ox_parse':
    parse.c:161:6: warning: implicit declaration of function 'strncasecmp'
    parse.c: In function 'read_coded_chars':
    parse.c:984:5: warning: implicit declaration of function 'strcasecmp'
    compiling cache8_test.c
    compiling sax.c
    In file included from sax.h:34:0,
                     from sax.c:44:
    sax_buf.h:51:6: warning: declaration does not declare anything
    sax.c: In function 'sax_drive_init':
    sax.c:132:5: warning: 'rb_data_object_alloc' is deprecated (declared at /usr/local/include/ruby-2.3.0/ruby/ruby.h:1421): by rb_data_object_wrap
    compiling sax_buf.c
    In file included from sax.h:34:0,
                     from sax_buf.c:44:
    sax_buf.h:51:6: warning: declaration does not declare anything
    sax_buf.c: In function 'ox_sax_buf_init':
    sax_buf.c:64:5: error: 'struct _Buf' has no member named 'in_str'
    sax_buf.c:74:16: error: 'struct _Buf' has no member named 'fd'
    sax_buf.c:77:16: error: 'struct _Buf' has no member named 'io'
    sax_buf.c:89:16: error: 'struct _Buf' has no member named 'fd'
    sax_buf.c:92:16: error: 'struct _Buf' has no member named 'io'
    sax_buf.c: In function 'partial_io_cb':
    sax_buf.c:190:27: error: 'struct _Buf' has no member named 'io'
    sax_buf.c: In function 'io_cb':
    sax_buf.c:209:27: error: 'struct _Buf' has no member named 'io'
    sax_buf.c: In function 'read_from_fd':
    sax_buf.c:235:19: error: 'struct _Buf' has no member named 'fd'
    sax_buf.c: In function 'read_from_str':
    sax_buf.c:265:21: error: 'struct _Buf' has no member named 'in_str'
    sax_buf.c:269:34: error: 'struct _Buf' has no member named 'in_str'
    sax_buf.c:272:8: error: 'struct _Buf' has no member named 'in_str'
    make: *** [sax_buf.o] Error 1
    
    make failed, exit code 2

**Comment by ohler55** [comment]
Odd that the line numbers are off. Are you using the latests Ox code?

From the output it looks like the changes needed are:

1. Get rid of the anonymous union.
2. Implement strcasecmp() and strncasecmp().
3. Figure out what the complaint about sax_buf.h:51 is about. With the line numbers being off it is hard to tell.

**Comment by mcarpenter** [comment]
Ahh, sorry, I think I pasted the (very similar) error from an install from our local gem repo and not from a fresh gem build from HEAD. That output follows below, line numbers should then match up?

    $ git log -1 
    commit 8c5a3640b8b732e1bbadb24b996a6f266878854a
    Author: Peter Ohler <peter@ohler.com>
    Date:   Thu Dec 31 17:28:30 2015 -0800
   
        Release 2.2.3

    $ gem build ox.gemspec 
      Successfully built RubyGem
      Name: ox
      Version: 2.2.3
      File: ox-2.2.3.gem
    $ sudo gem install ox-2.2.3.gem 
    Password: 
    Building native extensions.  This could take a while...
    ERROR:  Error installing ox-2.2.3.gem:
            ERROR: Failed to build gem native extension.
    
        current directory: /usr/local/lib/ruby/gems/2.3.0/gems/ox-2.2.3/ext/ox
    /usr/local/bin/ruby -r ./siteconf20160203-10948-1xyt3p8.rb extconf.rb
    >>>>> Creating Makefile for ruby version 2.3.0 on i386-solaris2.11 <<<<<
    creating Makefile
    
    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/ox-2.2.3/ext/ox
    make "DESTDIR=" clean
    
    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/ox-2.2.3/ext/ox
    make "DESTDIR="
    compiling sax_buf.c
    In file included from sax.h:9:0,
                     from sax_buf.c:19:
    sax_buf.h:28:6: warning: declaration does not declare anything
    sax_buf.c: In function 'ox_sax_buf_init':
    sax_buf.c:40:5: error: 'struct _Buf' has no member named 'in_str'
    sax_buf.c:43:5: error: 'struct _Buf' has no member named 'fd'
    sax_buf.c:46:5: error: 'struct _Buf' has no member named 'io'
    sax_buf.c:49:5: error: 'struct _Buf' has no member named 'io'
    sax_buf.c: In function 'partial_io_cb':
    sax_buf.c:140:27: error: 'struct _Buf' has no member named 'io'
    sax_buf.c: In function 'io_cb':
    sax_buf.c:159:27: error: 'struct _Buf' has no member named 'io'
    sax_buf.c: In function 'read_from_fd':
    sax_buf.c:184:19: error: 'struct _Buf' has no member named 'fd'
    sax_buf.c: In function 'read_from_str':
    sax_buf.c:213:21: error: 'struct _Buf' has no member named 'in_str'
    sax_buf.c:217:34: error: 'struct _Buf' has no member named 'in_str'
    sax_buf.c:220:8: error: 'struct _Buf' has no member named 'in_str'
    make: *** [sax_buf.o] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/ox-2.2.3 for inspection.
    Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86-solaris-2.11/2.3.0-static/ox-2.2.3/gem_make.out

**Comment by ohler55** [comment]
ok, I will create a branch and ask you to test it for me if that works for you.

**Comment by ohler55** [comment]
Try the 'old' branch I just pushed.

**Comment by mcarpenter** [comment]
Compiles and installs clean so I think this is a good change. Thanks!

Subsequently I have another problem when requiring the gem (`LoadError: cannot load such file -- ox/version`) but I suspect that's a ruby 2.3.0 or platform issue. I'll dig into that tomorrow and open a new issue if it really is ox related (but I really doubt that).

Thanks for your help.

**Comment by ohler55** [comment]
ok, I will make a release later tonight.

**Comment by mcarpenter** [comment]
Thanks.

Just to confirm: LoadError issue is _not_ related to ox. (I can reproduce with io-console, on both Solaris 11 and RH 6 -> next stop: ruby-core).

**Comment by ohler55** [comment]
A new Ox release has been made.

**Comment by ohler55** [comment]
ok to close?

**Comment by mcarpenter** [comment]
Yes, thanks. Installs without error, runs fine.

(The LoadError thing was indeed tangential: installer's umask was strict preventing subsequent file read on `require`).

**Comment by ohler55** [comment]
Great, thanks.
