### ISSUE TITLE
Feature Request: XML Schema (XSD) 1.1 Validation

### ISSUE THREAD

**Issue by alanwsmith** [ohler55/ox#126]
There doesn't seem to be a stand-alone, free, open-source XML Schema 1.1 validator. The closest I've seen is people making [java wrappers for Xerces](https://jeszysblog.wordpress.com/2012/09/27/free-and-open-source-xsd-1-1-validation-tool/). (Nokogiri will do 1.0 validation but not 1.1.)

If the ox roadmap includes XSD validation, please consider covering 1.1.

**Comment by ohler55** [comment]
At this point there are not plans for XSD validation. Its a hefty task in itself and I've got too much else going on right now. If someone else is interested in writing a validator I'd be glad to help out though.

**Comment by alanwsmith** [comment]
Figured that was likely the case. And, it seems like it would make sense to have as it's own project. I'll keep an eye out.
