### ISSUE TITLE
Ox.dump generates invalid XML for certain non-printable characters

### ISSUE THREAD

**Issue by vandrijevik** [ohler55/ox#128]
When `Ox.dump` encounters a string which contains `\b` or `\v` (there may be others, but I’ve tested with these), it outputs the following XML:

```
$ ruby -r ox -e 'puts Ox.dump("Bob\bBarker")'
<s>Bob&#x0008;Barker</s>
```

which is different than the XML generated by the `builder` gem (among other ways):

```
$ ruby -rbuilder -e 'puts Builder::XmlMarkup.new.s("Bob\bBarker")'
<s>Bob�Barker</s>
```

Running the output through `xmllint` suggests that `builder`’s generation is correct:

```
$ ruby -rbuilder -e 'puts Builder::XmlMarkup.new.name("Bob\bBarker")' | xmllint -
<?xml version="1.0"?>
<name>Bob&#xFFFD;Barker</name>

$ ruby -r ox -e 'puts Ox.dump("Bob\bBarker")' | xmllint -
-:1: parser error : xmlParseCharRef: invalid xmlChar value 8
<s>Bob&#x0008;Barker</s>
              ^
```

Passing `encoding: "UTF-8"` as an option to `Ox.dump` does not affect the generated output, and the same invalid output is generated when using `Ox::Document` directly:

```
$ ruby -r ox -e 'puts Ox.dump("Bob\bBarker", encoding: "UTF-8")'
<s>Bob&#x0008;Barker</s>

$ ruby -r ox -e 'doc = Ox::Document.new(version: "1.0", encoding: "UTF-8"); s = Ox::Element.new(:s); s << "Bob\bBarker"; doc << s; puts Ox.dump(doc)'

<s>Bob&#x0008;Barker</s>
```

Is there a way to have Ox generate the same output as `builder`, which leaves the character as-is since the document’s encoding is UTF-8, or to have it correctly escape these characters, as in the result of `xmllint`?

Here is my local environment, if that helps:

```
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

$ gem list | grep ox
ox (2.2.4)
```

**Comment by ohler55** [comment]
You have raised an interesting issue. I did a bit of checking and I would say xmllint is correct but builder is not. \b is not an allowable character in XML. The #FFFD character is sometimes used as a replacement character for unknown or invalid characters. Builder is actually changing the content of the string.

I think you would like a builder mode if I understand correctly. How about a new output option for invalid characters. I could see 'leave_out', 'replace_with', and 'put_in_anyway' as viable choices. What do you think?

**Comment by vandrijevik** [comment]
Thanks for such a quick reply!

I actually do not have a preference over builder vs. xmllint behavior (from the above), but I think a new output option like you mention is a fantastic idea!

To give a bit of context, I ran into this while debugging an issue with an API that was served via Rails (and uses `Ox.dump`), but whose XML is being consumed by iPhone and Android apps (with different XML parsers that blow up on the output as-is.

Since `invalid_character: :leave_out` seems like it would solve this problem, I think that is a good idea! `Nokogiri` seems to do something similar to `leave_out`, but it leaves out the whole string:

```
$ ruby -rnokogiri -e 'puts Nokogiri::XML::Builder.new { |xml| xml.name "Bob\bBarker" }.to_xml'
xmlEscapeEntities : char out of range
<?xml version="1.0"?>
<name></name>
```

(the `xmlEscapeEntities : char out of range` goes to stderr, so it is not a part of the output).

> I did a bit of checking and I would say xmllint is correct but builder is not. \b is not an allowable character in XML.

I am curious, can you share a link to where you found this? I am not very well versed in the XML spec, and I’d love to learn more (so that I can handle this before passing to `Ox.dump` for an immediate short-term fix).

**Comment by ohler55** [comment]
https://www.w3.org/TR/REC-xml/#Unicode. Section 2.2.

I'll put together a change and let you give it a try before releasing. Might take a day or two though.

**Comment by vandrijevik** [comment]
@ohler55 Thank you, that sounds fantastic!

**Comment by ohler55** [comment]
I just pushed a fix. When you have time please check it and let me know what you think.

**Comment by vandrijevik** [comment]
@ohler55 Thank you! I just updated to `2.3.0a3`, and the invalid text replacement works very well! I did notice some failing tests, which show that the handling of `nil` seems to have changed from:

```
<name nil="true"/>
```

to

```
<name nil="true">
</name>
```

We’re currently on 2.2.3, and I don’t see anything else in [the diff from that version to master](https://github.com/ohler55/ox/compare/v2.2.3...master) which could affect this, so do you have any ideas?

**Comment by ohler55** [comment]
That has to do with the :skip option. I can take a look at it and make sure I did not change the default value.

**Comment by ohler55** [comment]
You are talking about dumping though so that is something different. What object are you dumping?

**Comment by vandrijevik** [comment]
Here is a minimal replication I was able to come up with:

```
$ cat ox_dump.rb 
require "ox"
doc = Ox::Document.new(version: "1.0")
person = Ox::Element.new(:person)
doc << person
name = Ox::Element.new(:name)
name[:nil] = true
person << name
puts Ox::VERSION
puts Ox.dump doc, indent: 0

$ # Run using system gems, which only includes 2.2.4
$ ruby ox_dump.rb 
2.2.4

<person>
<name nil="true"/>
</person>

$ # Run using a bundle that includes 2.3.0a3
$ bundle exec ruby ox_dump.rb 
2.3.0a3

<person>
<name nil="true">
</name>
</person>
```

Without any changes besides Ox’s version, I see that difference between 2.2.4 and 2.3.0a3. Can I help with anything else?

**Comment by ohler55** [comment]
That should help. There were some changes. I didn't think in that area but I will look tonight. Thanks.

**Comment by ohler55** [comment]
Found the change. The nodes array of the Element is now initialized to an empty array. Before it was nil. I'll change the check to check for empty instead of nil.

**Comment by ohler55** [comment]
Just released Ox 2.3.0.

**Comment by vandrijevik** [comment]
I just upgraded to it, and the difference in handling nil went away! Thank you very much for your help and hard work here @ohler55, you are great! :smile:

**Comment by ohler55** [comment]
:-)
