### ISSUE TITLE
SAX XML Parsing, name arguments without namespaces?

### ISSUE THREAD

**Issue by theharq** [ohler55/ox#131]
Hi! I want to know if it's possible to have support for namespaces or maybe have an option in the `sax_parse` method where we could disable namespaces? for example Nokogiri have this method `remove_namespaces!`, the reason I ask this, is because is a performance issue doing this from the ruby class..

I'm parsing a 6 GB file and I get a hash from each node of this file, but to make it useable I need to remove the namespaces from the hash.. so the process without removing the namespaces it takes 2 hours aprox to parse all the file.. but when I make the change to remove this .. takes a lot of time.. the last test I made took more than 6 hours before I killed the process.

I would like to know where can I modify this in the c extension so the names returned to the `start_element` and `end_element` to come without a namespace.

Thank you

**Comment by ohler55** [comment]
If the desire is to just strip off the namespace that should be possible. Is that it?

**Comment by theharq** [comment]
yup, that's what I need

**Comment by ohler55** [comment]
The option I propose is to have an :strip_namespace option. Values for the option would be nil or false to do nothing. That would be the default. If a string was provided then any namespace with that string on the element or attribute names would be stripped. If '*' or true was given then all namespaces would be stripped. How does that sound?

**Comment by theharq** [comment]
that sounds perfect! :smiley:  :tada:

**Comment by ohler55** [comment]
Give it a try. I jus pushed a version to github with the :strip_namespace option.

**Comment by theharq** [comment]
Thank you @ohler55! thank you so much, it works perfect! you made my day  :heart:  :smiley:

**Comment by ohler55** [comment]
Does it make your processing faster?

**Comment by theharq** [comment]
Definitely, now it takes the same 2 hours.. ( for the 6 GB file )  not the n hours doing this from the `Ox::Sax` ruby class. :+1:  :+1:

**Comment by ohler55** [comment]
Just released Ox 2.3.0.

**Comment by theharq** [comment]
Awesome :smiley: , I think I can close this thread now.
