### ISSUE TITLE
Create XML tags as class names without indentation

### ISSUE THREAD

**Issue by Shruti-R** [ohler55/ox#134]
I am just started using ox gem for converting ruby object to xml and back. Following is sample code :
```
require 'ox'
class Author
  attr_accessor :name
end

class Book
  attr_accessor :title, :author
end

class Library
  attr_accessor :book
end

a1 = Author.new
a1.name = "ABC"

a2 = Author.new
a2.name = "XYZ"

b = Book.new
b.title = "RoR"
authors = []
authors << a1 << a2
b.author = authors

lib = Library.new
lib.book = b

xml = Ox.dump(lib, :indent => 0)
puts xml
```
which outputs :
```
"<o c=\"Library\">\n<o a=\"@book\" c=\"Book\">\n<s a=\"@title\">RoR</s>\n<a a=\"@author\">\n<o c=\"Author\">\n<s a=\"@name\">ABC</s>\n</o>\n
<o c=\"Author\">\n<s a=\"@name\">XYZ</s>\n</o>\n</a>\n</o>\n</o>\n"
```
How can I create XML tag names as that of class name(`<Library></Library>`) instead of type(`<o></o>`)? Also I see "\n" even after specifying `:indent=>0` 

Expected Output : 
`"<Library><book><title>RoR</title><author><name>ABC</name></author><author><name>XYZ</name></author></book></Library>"`

**Comment by ohler55** [comment]
The default mode for Ox is the :object mode. That outputs XML in a format optimized for Ox to reload/recreate the original object. It does not allow for custom XML formats as you describe. It should however honor the indent argument. I'll check on that.

If you want a custom format then you will need to convert to either native Ruby objects or Ox object first and them dump. Load would do the opposite. There are no options to both marshal and also preachify a custom format for the output. To off that would require a fair amount of set up on the part of the user which would also negate the performance and simplicity Ox provides today.

**Comment by Shruti-R** [comment]
@ohler55 thanks for quick response. I wanted to write generic function that would work for all models and attributes(may be annotations). Could you please elaborate on creating Ox object first and then dump? Are you referring to creating Ox object as below?
```
require 'ox'

doc = Ox::Document.new(:version => '1.0')

top = Ox::Element.new('top')
top[:name] = 'sample'
doc << top

xml = Ox.dump(doc)
puts xml
```

**Comment by ohler55** [comment]
Yes, exactly. Use Ox::Document, Ox::Element and the others to form your XML then dump.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by Shruti-R** [comment]
@ohler55 sure this can be closed.
