### ISSUE TITLE
Larger indents slows down Ox.dump

### ISSUE THREAD

**Issue by dvandersluis** [ohler55/ox#135]
While testing my [`ox-builder`](https://github.com/dvandersluis/ox-builder) gem, I observed a slowdown relating to the indent value when calling `Ox.dump`. The benchmark below shows how many iterations/second (`i/s`) were performed for each test case. <code>indent(<em>n</em>)</code> is a test for calling <code>Ox.dump(doc, indent: <em>n</em>)</code>.

```
Calculating -------------------------------------
         indent(200)    15.000  i/100ms
          indent(10)   138.000  i/100ms
           indent(2)   216.000  i/100ms
           indent(0)   224.000  i/100ms
-------------------------------------------------
         indent(200)    171.013  (± 5.8%) i/s -      3.420k
          indent(10)      1.140k (±13.5%) i/s -     22.356k
           indent(2)      2.100k (± 9.3%) i/s -     41.688k
           indent(0)      2.187k (± 8.4%) i/s -     43.456k

Comparison:
           indent(0):     2186.5 i/s
           indent(2):     2099.8 i/s - 1.04x slower
          indent(10):     1140.2 i/s - 1.92x slower
         indent(200):      171.0 i/s - 12.79x slower
```

The document I was dumping is about 110kb once generated (with normal indentation). As you can see from the benchmarks above, the larger the requested indentation, the slower `Ox.dump` is.

Any thoughts?

**Comment by dvandersluis** [comment]
It's been a long while since I did C, but my naive guess is that the loop in [`fill_indent`](https://github.com/ohler55/ox/blob/master/ext/ox/dump.c#L157-L165) is the cause of the slowdown. When it has to loop 200 times each time a node is output (and in my test there are a lot of nodes at various depths), there's a lot of work to do to build the indentation string.

I don't know if there's a more efficient way to build a string of a certain length, but perhaps caching the result and using the cached value will help? I'm not sure if `fill_indent` is being used with different counts in different places, but each could be cached.

**Comment by ohler55** [comment]
I'm not surprised the large indents take more time. You are writing a lot more characters. First there is extra code to traverse and reallocating buffers to build the larger string will slow it down. I tried caching at one point and saw no improvement on smaller indents. I did not try 200 as that is not a reasonable number. This is not a bug nor an issue. Optimizing for large indents and sacrificing performance for the usual values is not the direction I want to take Ox.

**Comment by dvandersluis** [comment]
Fair enough, 200 was exaggerated purposely, but even with 10 it's almost half as fast. I'm not sure what the appropriate threshhold for indents is. I actually don't want to optimize for large indents anyways, I want 2 to be as fast as 0, but perhaps that's too small of an optimization.

**Comment by ohler55** [comment]
I'd say that just 4% slower with 2 space indentation is pretty good. Probably writing more than the percent more characters. If you want to see a big difference between the two try a document that with indent of 0 is less than 64k and with indent of 2 over that. Ox starts with a 64k buffer and has to realloc for larger size. All expected though.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by dvandersluis** [comment]
Yep.
