### ISSUE TITLE
HTML tolerance

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#137]
Is Ox capable of handling HTML documents?
I'm getting the following error when trying to parse [this](https://gist.github.com/Zapotek/ebb89c0bd9450f6bbe1e73cad0f9fe85) HTML document.

```
tmp/benchmarks/xml.rb:12:in `parse': invalid format, elements overlap at line 48, column 8 [parse.c:565] (Ox::ParseError)
        from tmp/benchmarks/xml.rb:12:in `<main>'
```

```ruby
HTML = IO.read( "#{File.dirname( __FILE__ )}/regular_page.html" )

Ox.parse( HTML )
```

I'm basically looking for a lightweight and faster Nokogiri replacement that can deal with random and probably malformed web pages.

**Comment by Zapotek** [comment]
`Ox.sax_parse` doesn't have that issue, shouldn't they behave identically?

**Comment by ohler55** [comment]
There are multiple options for Ox. Take a look at the options and use the smart and tolerant ones. The SAX parser does not have as many options and defaults to more tolerant ones.

**Comment by Zapotek** [comment]
That's the ticket, cheers.
I had experimented with them previously but I had probably missed the `smart` one.

For anyone else having the same issue, this did the trick:

```ruby
Ox.default_options = {
    indent:          4,
    mode:            :generic,
    effort:          :tolerant,
    smart:           true,
    invalid_replace: nil
}
```

A link to the options in the README would save a lot of time for newcomers.

By the way, is there a way to abort the parse via a SAX handler?

**Comment by ohler55** [comment]
If more people are using Ox to parse HTML then you are right, a section in the REAME would be helpful. I've made a note to that effect and will get it added.

You can abort the SAX parser by raising an exception.

**Comment by Zapotek** [comment]
Exception sounds good, cheers.

**Comment by Zapotek** [comment]
Btw, for what it's worth, I think more people would use it as an HTML parser if they knew that they could, the performance benefits seems to be massive compared to the alternatives.
I had looked into Ox in the past but couldn't configure it properly, know I hope that I'll be able to replace Nokogiri with it.

**Comment by ohler55** [comment]
Thanks for the feedback.

How much difference in performance did you notice?

**Comment by Zapotek** [comment]
I haven't incorporated it into my project yet, but based on the type of workload that I generally handle my results are as follows.

Usual workload, page of medium size and complexity:
```
Warming up --------------------------------------
      Nokogiri::HTML    32.000  i/100ms
                  Ox   159.000  i/100ms
Calculating -------------------------------------
      Nokogiri::HTML    355.462  (±18.3%) i/s -      1.696k
                  Ox      1.662k (± 0.4%) i/s -      8.427k
```

Edge case, page of very large size:
```
Warming up --------------------------------------
      Nokogiri::HTML     1.000  i/100ms
                  Ox     4.000  i/100ms
Calculating -------------------------------------
      Nokogiri::HTML      8.278  (±12.1%) i/s -     42.000 
                  Ox     38.253  (±13.1%) i/s -    192.000 
```

I haven't benchmark RAM consumption yet, but I'm guessing Ox will be better at that too, so that in turn means that I can also be more aggressive with my caching strategies.

And given the fact that my system basically performs these operations in a loop (thousands and even hundreds of thousands of times), the overall savings should be quite astonishing.

**Comment by ohler55** [comment]
Wow, that is a huge difference. I'm very glad to see those results. I've be happy to see you publish those results or maybe give a tweet or something.

**Comment by Zapotek** [comment]
You mean in addition to me shouting it from my rooftop? Certainly.
I can't wait to see what happens.

**Comment by ohler55** [comment]
Thanks. :-)
