### ISSUE TITLE
Slash in attribute value without quotes

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#138]
It'd be helpful if Ox behaved like Nokogiri in this regard:

```ruby
require 'ox'
require 'nokogiri'

html = <<EOHTML
<a href='/' stuff=AAA1FAA399CAE6CF6819ADC9CDBFE9CE/>onunload</a>
EOHTML

Ox.default_options = {
    indent:          4,
    mode:            :generic,
    effort:          :tolerant,
    smart:           true,
    invalid_replace: nil
}

puts Nokogiri::HTML.fragment( html ).to_html
# <a href="/" stuff="AAA1FAA399CAE6CF6819ADC9CDBFE9CE/">onunload</a>

Ox.parse( html )
# tmp/ox.rb:17:in `parse': invalid format, document not terminated at line 1, column 66 [parse.c:441] (Ox::ParseError)
#         from tmp/ox.rb:17:in `<main>'
```

It'd be better still if there was an option to self-correct in some way (like if in doubt close the element) rather than raise an exception.

**Comment by ohler55** [comment]
The complaint Ox has is that there is a close on the 'a' element and then again. Unfortunately a more liberal close would not solve this but rather a less liberal closing policy would be the better choice. Let me look at it and see if there is a reasonable way to detect that problem and fix it. Note that if the last / in stuff is removed Ox does parse without raising an exception.

**Comment by Zapotek** [comment]
Yeah I noticed, in the end I figured I could always work around this with my own SAX handler, as in my case structure doesn't matter, I just need the elements -- so my issue is just with the error.
Still, if you could make it mimic Nokogiri's behavior or something then all the better.

**Comment by ohler55** [comment]
By mimic nokogiri you mean not raise an exception, right? Or put another way, detect and fix that error with the trailing /.

**Comment by Zapotek** [comment]
Yep.

**Comment by ohler55** [comment]
Just pushed a version that handles the situation described. Let me know what you think.

**Comment by Zapotek** [comment]
Sweet! Thanks.

**Comment by Zapotek** [comment]
Turns out I can't use SAX because once Ruby got involved performance dropped like a stone.
Could you add an `ignore_errors` option please?

**Comment by ohler55** [comment]
If there is no error handler method for the errors it will not be called. Just don't define the error() method on the handler and do not inherit from the Ox::Sax class.

**Comment by Zapotek** [comment]
I meant when using `Ox.parse`, I dropped my SAX approach due to the decline in performance.

**Comment by ohler55** [comment]
Ahh, no not the error callbacks but just building the Ruby objects.

**Comment by Zapotek** [comment]
Yeah without callbacks it's the same, but once you start doing even a little bit of processing/building performance goes downhill.
Not Ox's fault.
