### ISSUE TITLE
Problems with @pos in SAX parser

### ISSUE THREAD

**Issue by gzigzigzeo** [ohler55/ox#143]
Hello!

There is a problem with @pos variable value. It returns wrong values if file contains Cyrillic and probably some other non-ascii characters. It could be reproduced, for example, by changing line 247 of test/sax_parse.rb ("family" changed to "фамили" - it's just the transliteration):

```xml
<!DOCTYPE top PUBLIC "top.dtd">
<top attr="one">
  <!-- фамили -->
  <child>
```
I've tried to specify default encoding in options, force_encoding, adding BOM to the string and various other stuff. Nothing worked. Could you please help figure this out?

**Comment by gzigzigzeo** [comment]
Just discovered that the position is correct if used with #byteslice/#bytesize, and incorrect for regular #slice/#[]

**Comment by ohler55** [comment]
@pos is meant to help identify where a problem exists. It is not meant to be precise for everyone's idea about what is the location of a problem. Let me explain that statement a bit. In your case the problem could be said to be at the #byteslice or at the character after that. Depending on your perspective either could be correct. It gets even worse for something like an unterminated string.

Having said that, where was the @pos pointing to or was it not set at all?

**Comment by gzigzigzeo** [comment]
I considered `@pos` as a character index within a string. Instead of it it points to byte index. It works perfectly and precise if I use `#byteslice` / `#bytesize` and fails if I try to use `#slice`/`#size`/`#[]` on a string containing non-ascii characters. So, if `@pos` is intended to identify the location of a problem then it should be said somewhere in documentation that user should treat it as byte pos instead of char pos.

For example:
```<!-- Абвгдежзиклмнопрстухф --><div><s></div></s>```

If we imagine that error will happen somewhere near ```<s>``` - then `@pos` is expected to be something like 35, but instead of it it will contain some value around 70 because each Cyrilic/Katakana/Hirakana letter has size of at least two bytes. So, `@pos` will show the location beyond the end of the string. User will be unable nor to call `@source_string[@pos-1..@pos+1]` either nor take a look at text editor to returned position to figure out what's happened. 

I think, this issue it is not the issue itself, is just the minor lack of documentation. 

Besides that, thank you for amazing job you have done! I use `ox` in all tasks related to xml, it's really simple, useful and incredibly fast!

**Comment by ohler55** [comment]
You are correct it is the byte position. I will update the docs to reflect that. It would be nicer to have the position be the character position but in order to provide that would require more overhead and I'd rather keep Oj fast. Updating the docs is easy though. Thanks for helping improve Oj.

**Comment by gzigzigzeo** [comment]
Thank you!

**Comment by ohler55** [comment]
Checked the docs. @pos is defined as the number of bytes from the start in sax.rb and the rubydocs. Did you see it described differently somewhere else? I'd like to make sure everything is consistent.
