### ISSUE TITLE
Number of written bytes from Ox::Builder?

### ISSUE THREAD

**Issue by groe** [ohler55/ox#144]
I am working on a SAX parser that simultaneously writes to a SAX builder (i.e. converts between two XML structures). I would like to create a mapping of where each XML tag begins in the input file and where it begins in the output file (actual byte positions).

Getting the position in the input stream already works perfectly by defining the `@pos` instance variable in `Ox::Sax`. However, I could not find a way to get the number of written bytes from an `Ox::Builder` instance.

Am I missing something? Any ideas on how to achieve this?

**Comment by ohler55** [comment]
Try the candidate release on github. I added line(), column(), and pos() methods to Builder.

**Comment by groe** [comment]
I will try it tomorrow. Looking at the diff of your commit just for this issue (pushed in ~8 hrs from me asking about it!), I must already thank you for this – and all your efforts on this project – honestly, keep up the great work @ohler55 !

**Comment by ohler55** [comment]
The timing was good. :-)

**Comment by groe** [comment]
I just tested it, seems to work perfectly! Thanks again, @ohler55 :+1:

**Comment by ohler55** [comment]
Released Ox 2.4.2.
