### ISSUE TITLE
Option to disable self-closing tags in Ox::Builder

### ISSUE THREAD

**Issue by groe** [ohler55/ox#148]
`Ox::Builder` generates self closing tags (e.g. `<div />`), which causes problems with HTML5 output documents. For most tags in HTML5, this isn't allowed and browsers treat the tag like a regular opening tag (which of course creates a big mess) – [check out this StackOverflow](http://stackoverflow.com/a/3558200).

What do you think about an option to disable self-closing tags in favor of the explicit `<div></div>` style?

**Comment by ohler55** [comment]
Ox::Builder is a builder for XML, not HTML. I could see adding an HTML 5 builder but that would be a separate class. HTML and more so HTML 5 is not XML in many ways.

**Comment by ohler55** [comment]
If you set the indentation to a negative value no terminating newline will be added. Let me know if it works for you with the version on github. If it does I will make a new release.

**Comment by groe** [comment]
You are right, HTML(5) is different to XML in some aspects. Having used Ox::Builder for HTML for a while now, self-closing tags however where the first incompatibility I have encountered. (Note that I'm just writing partial HTML5 snippets, not whole HTML5 documents).

Nokogiri also has a [separate module for HTML](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/HTML).

(The last comment refers to #147 I guess, thanks for that as well!)

**Comment by ohler55** [comment]
HTML 5 is picky about what can be closed and what can not be. It also has a restricted set of element types it allows. An HTML 5 builder should support all features to produce only correct HTML 5. I'll give it some thought.

**Comment by ohler55** [comment]
After going over portions of the HTML 5 specification I've decided it would be too much effort to implement a builder that would support the complete spec. There are just too many rules and conditions. It would be a major undertaking all by itself.

As for the self closing, the simplest way to force a non-self closing is to call the text() method with an empty string. I'd like to keep the options limited to avoid some of the explosion that has occurred with the parser.

**Comment by groe** [comment]
Alright, I went with this:

```ruby
HTML5_VOID_ELEMENTS = %w(area base br col embed hr img input keygen link meta param source track wbr).map(&:to_sym).freeze
builder.text("") unless HTML5_VOID_ELEMENTS.include?(target_tag)
```

Makes sense to only add a HTML5 builder to Ox if we can ensure that it generates valid HTML5. If that's just too much effort (or not a goal of Ox as an XML parser/builder after all), that's fine.

Anyway, thanks for considering it!

**Comment by ohler55** [comment]
If that works for you, great. I'll leave a note to myself to consider and HTML builder if I run out of things to do. Thanks for being understanding.

**Comment by ohler55** [comment]
Can this be closed?
