### ISSUE TITLE
Error building the native extension (no tm_gmtoff struct member)

### ISSUE THREAD

**Issue by th** [ohler55/ox#15]
I'm running ruby 1.9.3p194 (2012-04-20) [i386-mingw32] from rubyinstaller.org with the DevKit on Windows 7 64 bit.

When I try to install the ox gem (gem install ox), the build of the native extension fails:

C:\Users\Thomas>gem install ox
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ox:
        ERROR: Failed to build gem native extension.

```
    D:/Ruby/Ruby193/bin/ruby.exe extconf.rb
```

> > > > > Creating Makefile for ruby version 1.9.3 <<<<<
> > > > > creating Makefile

make
generating ox-i386-mingw32.def
compiling base64.c
compiling cache.c
cache.c: In function 'ox_cache_new':
cache.c:62:5: warning: implicit declaration of function 'bzero'
cache.c:62:5: warning: incompatible implicit declaration of built-in function 'b
zero'
compiling cache8.c
compiling cache8_test.c
cache8_test.c:35:5: warning: large integer implicitly truncated to unsigned type

cache8_test.c:37:5: warning: large integer implicitly truncated to unsigned type

compiling cache_test.c
compiling dump.c
dump.c: In function 'dump_time_xsd':
dump.c:507:15: error: 'struct tm' has no member named 'tm_gmtoff'
dump.c:509:26: error: 'struct tm' has no member named 'tm_gmtoff'
dump.c:510:25: error: 'struct tm' has no member named 'tm_gmtoff'
dump.c:512:26: error: 'struct tm' has no member named 'tm_gmtoff'
dump.c:513:25: error: 'struct tm' has no member named 'tm_gmtoff'
make: **\* [dump.o] Error 1

Gem files will remain installed in D:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/ox-1
.5.9 for inspection.
Results logged to D:/Ruby/Ruby193/lib/ruby/gems/1.9.1/gems/ox-1.5.9/ext/ox/gem_m
ake.out

Is there something wrong with my build environment? Other gems' extensions build fine.

**Comment by satheyogesh** [comment]
I am still facing issue in setting up Ox on windows environment. Is this issue is fixed ?

**Comment by ohler55** [comment]
I don not have an environment to duplicate your issue. The error message indicates it is a problem with your environment. The makefile could not even be created. The build never even go to Ox code. If you can get past the problem of creating the makefile I would be glad to address any issues with the Ox code.
