### ISSUE TITLE
Add text between tags ?

### ISSUE THREAD

**Issue by MatthiasRMS** [ohler55/ox#152]
Hi, 

I can't find in your documentation how to get a structure like this:

```
 <root>
    <Element>
      <foo>ex1</foo>
    </Element>
  </root>
```

I found how to create nested tags, but how can I get text between tags ? ("ex1" between "foo" tags). 

Couldn't find the answer. Thanks for your help

**Comment by ohler55** [comment]
```ruby
require 'ox'

root = Ox::Element.new('root')
element = Ox::Element.new('Element')
foo = Ox::Element.new('foo')
foo << 'ex1'
element << foo
root << element
```
