### ISSUE TITLE
Null byte truncates document

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#154]
Hello,

I've found a bug where a null byte truncates the rest of the text.

``` ruby
TEXT = "My text \0 after null."

HTML = <<-EOHTML
    <html>
        #{TEXT}
    </html>
EOHTML

class Handler
    def text( value )
        p value
    end
end

Ox.sax_html( Handler.new, StringIO.new( HTML ) )
```

Prints out:

``` ruby
"\n        My text "
```

Rather than:

``` ruby
"\n        My text \u0000 after null."
```

**Comment by Zapotek** [comment]
I just realized that it's much more serious than that, it doesn't just truncate the text, it truncates the whole document:

```ruby
TEXT = "My text \0 after null."

HTML = <<-EOHTML
    <html>
        #{TEXT}

        <a href="" />
    </html>
EOHTML

class Handler

    def start_element( name )
        p [__method__, name]
    end

    def end_element( name )
        p [__method__, name ]
    end

    def text( value )
        p [__method__, value]
    end

end

Ox.sax_html( Handler.new, StringIO.new( HTML ) )
```

Prints out:
```
[:start_element, :html]
[:text, "\n        My text "]
[:end_element, :html]
```

**Comment by ohler55** [comment]
A collision of C style strings and UTF-8. Good catch that I will have to fix. It might a bit of time.

**Comment by Zapotek** [comment]
No worries, I can wait.

Cheers

**Comment by ohler55** [comment]
From what I can tell reading the XML 1.0 and 1.1 spec the NULL character (#x0) is not a valid XML character. So what I would have expected is that Ox would raise an exception. Looking into why that did not occur.

**Comment by Zapotek** [comment]
It'd say it'd be better to call the `#error` callback but keep parsing.
Or make the behavior configurable.

**Comment by ohler55** [comment]
Sax, right. I was looking in the wrong place. I'll get you test going here but add an error() method so the callback will be visible. I expect it will be called. At that point it does terminate parsing. I'll look into how to continue without romping off into random memory after the string.

So I think the plan is
1. make sure the error is raised
2. attempt to keep parsing, maybe only if the smart option is used

**Comment by Zapotek** [comment]
Sounds good.

**Comment by Zapotek** [comment]
Have you had a chance to look into this?

**Comment by ohler55** [comment]
Yes, looked at it but have not fixed. Its been a busy week. I hope to have time Tuesday for Ox.

**Comment by ohler55** [comment]
Sorry but it would take a major re-write to support allowing null bytes in XML. There are too many places where strings are expected to be C strings. I'd put it on the wish list but since valid XML can not have null characters it doesn't seem worth the effort.

Maybe there is a different work around that would satisfy your needs. What is your input? String, file, socket, something else? It might be possible to wrap the io in a reader that removes null characters.

**Comment by Zapotek** [comment]
It's a string, I guess I could remove nulls, it's not a deal breaker.
Thanks for looking into it.

**Comment by ohler55** [comment]
If it would help I could put a pre-parse routine in to compress out nulls. Probably not much different than doing it in Ruby before though. Sorry.

**Comment by Zapotek** [comment]
No worries, I can do it in Ruby.
