### ISSUE TITLE
Feature request: add `margin` to options for `Ox.dump` 

### ISSUE THREAD

**Issue by madebydna** [ohler55/ox#157]
First of all, thank you for the `ox` gem. I've started using it as an XML writer and I'm amazed as to how blazingly fast it is! 

Unfortunately the `Ox.dump` method is missing a feature that is quite important for my use case. I'd need a way to indent the entire generated XML block by a specified number of spaces. I'm aware of the `indent` option, but that defines the number of spaces to indent each element by, rather than representing a "margin" that would indent the entire block.

What I'm doing is building XML blocks using `Ox::Element` and writing them to a file continuously. Depending on the location in the file, the "margin" of the block needs to change. Is there maybe a workaround that I could use (other than looping over the generated lines of the XML and prepending them with spaces)?

**Comment by ohler55** [comment]
That seems like a reasonable addition. I'll try to get that done over the next week or so.

**Comment by madebydna** [comment]
Thank you @ohler55! I really appreciate that.

**Comment by ohler55** [comment]
Please check out the latest in GitHub and see what you think. The :margin option should be a string.

**Comment by madebydna** [comment]
I've tried out the `:margin` option and it's exactly what I needed. Thanks so much for taking care of this!

**Comment by ohler55** [comment]
Great. Just release 2.4.6.
