### ISSUE TITLE
Document truncation after '<>'

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#158]
I'm using the SAX parser and it seems to truncate everything past `<>`.

Example:

```ruby
require 'ox'

HTML = <<-EOHTML
    <html>
        <>

        <a href="">Stuff</a>
    </html>
EOHTML

class Handler

    def start_element( name )
        p [__method__, name]
    end

    def end_element( name )
        p [__method__, name ]
    end

    def text( value )
        p [__method__, value]
    end

end

Ox.sax_html( Handler.new, StringIO.new( HTML ) )
```

It only prints out:

```
[:start_element, :html]
[:end_element, :html]
```

**Comment by ohler55** [comment]
Thanks, will look into it an get it fixed. I'm not sure what the correct output should be but it should not ignore other elements.

**Comment by Zapotek** [comment]
Hello,

Has there been any progress on this?

Cheers

**Comment by ohler55** [comment]
I thought I fixed it and responded. My apologies. Let me double check in the next day or two. Tomorrow I can not look but will the day after. I take it the problem still persists in the most recent release.

**Comment by Zapotek** [comment]
Yeah I just tried it with 2.4.6 and I'm getting the same behavior.

**Comment by ohler55** [comment]
Pushed a fix to the sax parser. I have not added a test for the html parser yet though. You are welcome to try though.

**Comment by Zapotek** [comment]
Thank you.
