### ISSUE TITLE
SAX overlay element skipping

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#160]
Hello again,

I've run into a situation where I need to whitelist comments but without whitelisting their parent.
I can do that with regular nodes but I don't see how I can do it with comments.

For example:

```ruby
WHITELIST = %w(p)

HTML =<<EOHTML
<html>
    <body  class="body">
        <!-- Comment -->

        <p> Paragraph </p>
    </body>
</html>
EOHTML

class Handler

    def start_element( name )
        p [__method__, name]
    end

    def end_element( name )
        p [__method__, name ]
    end

    def text( value )
        p [__method__, value]
    end

    def comment( value )
        p [__method__, value]
    end

end

Ox.default_options = {
    indent:          4,
    mode:            :generic,
    effort:          :tolerant,
    smart:           true,
    invalid_replace: nil
}

overlay = Ox.sax_html_overlay.dup
overlay.each do |k, v|
    overlay[k] = :off
end

WHITELIST.each do |e|
    overlay[e] = :active
end

Ox.sax_html( Handler.new, StringIO.new( HTML ), overlay: overlay )
```

Returns:

```
[:start_element, :p]
[:text, " Paragraph "]
[:end_element, :p]
```

I'd like the above to also include the comment but without having to whitelist the `body`.

Cheers

**Comment by Zapotek** [comment]
Sorry to bother you again but this is holding up my release.
Is my feature request doable?

Cheers

**Comment by ohler55** [comment]
Soory, lost track of it. I'll look at it today again. I think it is doable. Not simple but possible.

**Comment by ohler55** [comment]
It ended up being easier than my original thoughts. Please try the current candidate on GitHub. Look at the test in the test/sax/smart_test.rb titled test_comment_active(). Basically what you have but set ``` overlay['!--'] = :active```.

**Comment by Zapotek** [comment]
That did that trick, thank you.

**Comment by Zapotek** [comment]
Can you make a release please?

**Comment by ohler55** [comment]
Ox 2.4.9 was release Jan 25.
