### ISSUE TITLE
getting segmentation fault while using ox parser.

### ISSUE THREAD

**Issue by arashiya** [ohler55/ox#161]
I am getting segmentation fault error when using ox parser. The error is as follows:
/mnt/deployed/data-import/releases/data-import_20170207-112126_1677_bb8e24ecee_dev-branch/helpers/easy_sax.rb:30: [BUG] Segmentation fault at 0x00000000000030  check_box FILTER FOR'

Following is the code which is there in easy_sax.rb
```ruby
class EasySax < ::Ox::Sax
  def initialize(roots_name, handler)
    @roots_name = roots_name.to_sym
    @handler = handler
    @ignore = true
    @stack = []
  end

  def create_new_element(name)
    {
      name: name,
      attributes: {},
      children: {},
      cdata: nil,
      text: nil
    }
  end

  def start_element(name)
    if @ignore
      if name == @roots_name
        @current = @current_root = create_new_element(name)
        @stack.push(@current)
        @ignore = false
      else
        return
      end
    else
      new_elm = create_new_element(name)
      @current[:children][name] ||= []
      @current[:children][name].push new_elm
      @current = new_elm
      @stack.push(@current)
    end
  end

  def end_element(name)
    return if @ignore

    popped = @stack.pop
    @current = @stack.last

    if name == @roots_name
      @ignore = true
      @handler.call(@current_root)
    end
  end

  def attr(name, value)
    return if @ignore
    @current[:attributes][name] = value
  end

  def text(value)
    return if @ignore
    @current[:text] = value
  end

  def cdata(value)
    return if @ignore
    @current[:cdata] = value
  end
end
```
code at line 30 is  "@current[:children][name] ||= []"
This was not happening before and it suddently started happening. I am trying to parse a file with size almost 1.7 GB.

**Comment by ohler55** [comment]
What ruby version are you using? What Ox version? If you have a smaller sample I can test with that would help. Also the Ox::default_options settings and the line you use to run the parser. It seems like an odd place to default as it is pure ruby at that point. If I can recreate the crash I should be able to either fix it if the problem is in Ox.

**Comment by shruthipuranik** [comment]
RUBY VERSION: 1.9.3
Using ox 2.1.1

This is the method which calls Ox.sax_parse()

`def extract
    amazon_items = []
    start_time = Time.now
    handler = Proc.new do |title|
      amazon_item = extract_helper(title)
      if amazon_item
        amazon_items << {normalized_item: amazon_item.normalized_item, availabilities: amazon_item.availabilities}
        logger.info "Extracted Amazon ID #{IngestionHelper::traverse_dom(title, [:children, :ASIN, 0, :text])}"
        if amazon_items.length%1_000 === 0
          logger.info "#{amazon_items.length} Amazon Items Tokenized. Time per 1000 items = #{(Time.now-start_time)}"
          start_time = Time.now
        end
      else
        logger.info "Could not find title. #{IngestionHelper::traverse_dom(title, [:children, :CONTENTTYPE, 0, :text])} Provided - ASIN:#{IngestionHelper::traverse_dom(title, [:children, :ASIN, 0, :text])}"
      end
    end
    logger.info "Begin Amazon Tokenize"
    Ox.sax_parse(EasySax.new(:Item, handler), feed)
    logger.info "#{amazon_items.length} Amazon Items Tokenized"
    amazon_items
  end`

Following is a smaller sample of the XML feed:

`<UnboxCatalog>
  <Item>
  <AMAZONRATINGS>5.0</AMAZONRATINGS>
  <AMAZONRATINGSCOUNT>1922</AMAZONRATINGSCOUNT>
  <ASIN>B00IZ10ODO</ASIN>
  <CONTENTTYPE>TVEpisode</CONTENTTYPE>
  <EPISODENUMBER>13</EPISODENUMBER>
  <GENRE_DRAMA>Y</GENRE_DRAMA>
  <GENRE_THRILLER>Y</GENRE_THRILLER>
  <HASIMAGE>Y</HASIMAGE>
  <IMAGE_URL_LARGE>http://ecx.images-amazon.com/images/I/415X9keg52L._SX320_SY240_.jpg</IMAGE_URL_LARGE>
  <IMAGE_URL_SMALL>http://ecx.images-amazon.com/images/I/415X9keg52L._SX160_SY120_.jpg</IMAGE_URL_SMALL>
  <QUALITY>SD</QUALITY>
  <ISPREORDER>N</ISPREORDER>
  <ISRENTAL>N</ISRENTAL>
  <ISSEASONPASS>N</ISSEASONPASS>
  <ISSTREAMABLE>Y</ISSTREAMABLE>
  <LONGSYNOPSIS>A well prepared Fitz gets thrown a curve ball during the first presidential debate, Olivia receives shocking news and is forced to make an extremely difficult decision, and the gladiators work with a powerful CEO accused of murder. Meanwhile, one dirty little secret could lead to deadly consequences.</LONGSYNOPSIS>
  <MPAARATING>TV-14</MPAARATING>
  <PRICE>1.99</PRICE>
  <RELEASEDATE>2014-03-13T00:00:00</RELEASEDATE>
  <RUNTIME>43</RUNTIME>
  <SEASONASIN>B00FMOBCOC</SEASONASIN>
  <SEASONNUMBER>3</SEASONNUMBER>
  <SERIESASIN>B007RV6CCK</SERIESASIN>
  <SERIESTITLE>Scandal</SERIESTITLE>
    <RELATED_PRODUCTS>
  
   <UNBOX_HD_PURCHASE_ASIN>B00IZ12I92</UNBOX_HD_PURCHASE_ASIN>
   <UNBOX_HD_PURCHASE_URL>http://www.amazon.com/gp/product/B00IZ12I92/INSERT_TAG_HERE/ref=atv_feed_catalog/</UNBOX_HD_PURCHASE_URL>
   <UNBOX_HD_PURCHASE_PRICE>2.99</UNBOX_HD_PURCHASE_PRICE>
    </RELATED_PRODUCTS>
  <STUDIO>ABC</STUDIO>
  <SYNOPSIS>Fitz gets thrown a curve ball during the first presidential debate.</SYNOPSIS>
  <TCONST>tt3288600</TCONST>
  <TITLE>No Sun on the Horizon</TITLE>
  <TIVOENABLED>Y</TIVOENABLED>
  
  <URL>http://www.amazon.com/gp/product/B00IZ10ODO/ref=atv_feed_catalog</URL>
  </Item>
  <Item>
  <AMAZONRATINGS>0.0</AMAZONRATINGS>
  <AMAZONRATINGSCOUNT>0</AMAZONRATINGSCOUNT>
  <ASIN>B01MCYULFX</ASIN>
  <CONTENTTYPE>Movie</CONTENTTYPE>
  <GENRE_SPORT>Y</GENRE_SPORT>
  <HASIMAGE>Y</HASIMAGE>
  <IMAGE_URL_LARGE>http://ecx.images-amazon.com/images/I/51feLm09M3L._SX320_SY240_.jpg</IMAGE_URL_LARGE>
  <IMAGE_URL_SMALL>http://ecx.images-amazon.com/images/I/51feLm09M3L._SX160_SY120_.jpg</IMAGE_URL_SMALL>
  <QUALITY>SD</QUALITY>
  <ISPREORDER>N</ISPREORDER>
  <ISRENTAL>Y</ISRENTAL>
  <ISSEASONPASS>N</ISSEASONPASS>
  <ISSTREAMABLE>Y</ISSTREAMABLE>
  <LONGSYNOPSIS>Bob shows you some exercises that you can do at home.</LONGSYNOPSIS>
  <PRICE>1.99</PRICE>
  <RUNTIME>13</RUNTIME>
    <RELATED_PRODUCTS>
  
   <UNBOX_HD_RENTAL_ASIN>B01MCYUO5T</UNBOX_HD_RENTAL_ASIN>
   <UNBOX_HD_RENTAL_URL>http://www.amazon.com/gp/product/B01MCYUO5T/INSERT_TAG_HERE/ref=atv_feed_catalog/</UNBOX_HD_RENTAL_URL>
   <UNBOX_HD_RENTAL_PRICE>2.99</UNBOX_HD_RENTAL_PRICE>
   <UNBOX_PURCHASE_ASIN>B01MDRFZ7H</UNBOX_PURCHASE_ASIN>
   <UNBOX_PURCHASE_URL>http://www.amazon.com/gp/product/B01MDRFZ7H/INSERT_TAG_HERE/ref=atv_feed_catalog/</UNBOX_PURCHASE_URL>
   <UNBOX_PURCHASE_PRICE>7.99</UNBOX_PURCHASE_PRICE>
   <UNBOX_HD_PURCHASE_ASIN>B01MCYULWN</UNBOX_HD_PURCHASE_ASIN>
   <UNBOX_HD_PURCHASE_URL>http://www.amazon.com/gp/product/B01MCYULWN/INSERT_TAG_HERE/ref=atv_feed_catalog/</UNBOX_HD_PURCHASE_URL>
   <UNBOX_HD_PURCHASE_PRICE>9.99</UNBOX_HD_PURCHASE_PRICE>
    </RELATED_PRODUCTS>
  <STUDIO>Bob Mann</STUDIO>
  <SYNOPSIS>Bob shows you some exercises that you can do at home.</SYNOPSIS>
  <TITLE>Be Your Own Private Trainer</TITLE>
  <TIVOENABLED>N</TIVOENABLED>
  
  <URL>http://www.amazon.com/gp/product/B01MCYULFX/ref=atv_feed_catalog</URL>
  <ISTRIDENT>Y</ISTRIDENT>
  </Item>
</UnboxCatalog>`

Thanks

**Comment by ohler55** [comment]
Super, thanks. I'll look at it later this afternoon.

**Comment by ohler55** [comment]
Is there a reason you are using a 3 year old version of Ox?

**Comment by ohler55** [comment]
I was not able to get a failure with the current version of Ox and a stripped down version of your extract() function. The ```@current[:children][name] ||= []``` line was not called in the example though. Are you able to provide a failing test with the latest version of Ox?

**Comment by ohler55** [comment]
Any updates on this? Did the latest version of Ox work any better than the 3 year old version?

**Comment by shruthipuranik** [comment]
We haven't tried the new version of Ox.  We are suspecting that the problem is due to the huge feed being parsed.

**Comment by ohler55** [comment]
The SAX parse should handle some very large files. I've used it on multiple GB files before. Of course the test did not hang on to any data which is probably different than how you are using it.

**Comment by shruthipuranik** [comment]
The following error appears sometimes in line 30. 
code at line 30 is "@current[:children][name] ||= []"
method `hash' called on unexpected T_NODE object (0x007efd2f1bdf90 flags=0x651c)
Any idea of what this could be?

**Comment by ohler55** [comment]
That line is of course outside of Ox. I would guess that the value for ```@current[:children]``` is not a hash. Kind of an odd error message though. How about adding a puts statement in front of it or in a rescue and printing out the value of the possible variables involved.

**Comment by ohler55** [comment]
Is this still open?

**Comment by arashiya** [comment]
Upgrading ox version to latest seemed to solve the issue. Hence, this is no longer happening. Thanks for help :)

**Comment by ohler55** [comment]
Thanks
