### ISSUE TITLE
Disable XML entities in Ox::Builder?

### ISSUE THREAD

**Issue by groe** [ohler55/ox#162]
I'm using ox to translate XML files by reading them with a SAX parser and simultaneously writing the translated texts to an Ox::Builder.

Now I've noticed that the builder seems to escape certain XML entities ([`&quot;`, `&amp;`, `&apos;`, `&lt;` and `&gt;`](https://github.com/ohler55/ox/blob/master/ext/ox/builder.c#L125)). For instance, if the source XML contains `<p>It's great. You won't believe it.</p>`, the converted file has `<p>It&apos;s great. You won&apos;t believe it.</p>`.

Escaping a `<` char is of course necessary to ensure XML well-formedness, but is it necessary to escape all 5 characters in all contexts (attribute values, text nodes)? Or could it be relaxed, e.g. for `&quot;`s and `&apos;`es in non-attribute text?

**Comment by ohler55** [comment]
It makes sense to only use the escaped version when necessary. Let me look at what it will take to get that change made.

**Comment by ohler55** [comment]
Give the github master branch a try please.

**Comment by groe** [comment]
The master branch works perfectly.

Thanks for the (repeatedly) great support, @ohler55 – you're doing a outstanding job! :+1: Have you considered dual-licensing ox under the beer license, or the postcard license? ;)

**Comment by ohler55** [comment]
Beer license sounds good. I'll have to look into that. :-)

**Comment by groe** [comment]
Unfortunately with 2.4.13b2, `&quot;` is present again:

```ruby
b = Ox::Builder.new
b.text("\"'")
b.to_s
# => "&quot;'\n"
```

**Comment by ohler55** [comment]
I believe the spec allows raw single quotes.

**Comment by ohler55** [comment]
If it is for double quotes that is what you pointed out as an error.

**Comment by groe** [comment]
This single quote is fine! But the double quote only has to become a `&quot;` entity if used in an attribute value, no? In my example it's used as regular text, where it should just stay a `"`.

**Comment by ohler55** [comment]
I'm going to have to go over the specs again. The release is not going out until I get it a reference to the spec added to each place in the code. Too much back and forth. I'll look today.

**Comment by ohler55** [comment]
Ok, by the XML 1.1 spec the restrictions are
attribute: not <&" for double quoted attribute values <&' for single quoted attribute values
element content: not <& only

The > "may" be replaced and must under some circumstances. It seems easier to replace with &gt; since most people expect that anyway.

Of course the spec indicated that single and double quotes may be replaced in both element content and attributes.

I'm inclined to follow the must part of the spec except for > which will be replaced with &lt;

**Comment by ohler55** [comment]
Try the most recent push please.

**Comment by groe** [comment]
I justed updated to 2.4.13b3 from github and all my tests are green :+1: 

I agree 100% with your interpretation of the spec. Always replacing `>` seems most consistent with what you would intuitively expect. For (single and double) quotes my expectation is that XML-encoded entities are only used when necessary, i.e. in an attribute value context.

Thanks, closing here!

**Comment by ohler55** [comment]
Ok, I'll make a release today. Thanks.
