### ISSUE TITLE
#sax_html segfault

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#164]
A user of mine has reported the following segfault: http://pastebin.com/eKmibpXP

Unfortunately I haven't been able to reproduce it.

**Comment by ohler55** [comment]
Any idea what the calls were before that? Like what was being parsed?

**Comment by Zapotek** [comment]
Unfortunately, none at all. I'll try to get some more info from my user but it's going to be difficult to track down what is being parsed.

**Comment by ohler55** [comment]
That makes it tough to debug.

**Comment by Zapotek** [comment]
Close to impossible I'd say, this is more of an FYI rather than me expecting a fix.

**Comment by ohler55** [comment]
If you can't get any more information on it in the next few days we might as well close the issue.

**Comment by ohler55** [comment]
No new info, closing.
