### ISSUE TITLE
Error installing gem: No rule to make target

### ISSUE THREAD

**Issue by StarryLiquid** [ohler55/ox#165]
Trying to install the gem on windows 7, using the command `gem install ox`

log:

current directory: C:/.../Ruby/lib/ruby/gems/2.0.0/gems/ox-2.4.11/ext/ox
C:/.../Ruby/bin/ruby.exe -r ./siteconf20170409-112636-11fo02e.rb extconf.rb
```
>>>>> Creating Makefile for ruby version 2.0.0 on x64-mingw32 <<<<<
creating Makefile
mingw32-make: *** No rule to make target '/C/.../Ruby/include/ruby-2.0.0/ruby.h', needed by 'base64.o'.  Stop.

current directory: C:/.../Ruby/lib/ruby/gems/2.0.0/gems/ox-2.4.11/ext/ox
make "DESTDIR=" clean

C:/...\Ruby\lib\ruby\gems\2.0.0\gems\ox-2.4.11\ext\ox>mingw32-make
mingw32-make: *** No rule to make target '/C/.../Ruby/include/ruby-2.0.0/ruby.h', needed by 'base64.o'.  Stop.

current directory: C:/.../Ruby/lib/ruby/gems/2.0.0/gems/ox-2.4.11/ext/ox
make "DESTDIR="

C:...\Ruby\lib\ruby\gems\2.0.0\gems\ox-2.4.11\ext\ox>mingw32-make
mingw32-make: *** No rule to make target '/C/.../Ruby/include/ruby-2.0.0/ruby.h', needed by 'base64.o'.  Stop.

make failed, exit code 2
```

Looks like a problem with backwards slashes and forward slashes

**Comment by ohler55** [comment]
That is not a problem with Oj but with your environment. Ruby is what creates the Makefile, I'm not a Window developer myself but I know there are guidelines on how to set up your environment to install Ruby C extensions.

**Comment by ohler55** [comment]
Did you figure out the Ruby environment for Windows? Can this be closed?

**Comment by StarryLiquid** [comment]
Sorry for the delayed response. I reinstalled ruby and used the devkit and now the installation is working fine.
For posterity, the devkit can be downloaded from the [rubyinstaller site](http://rubyinstaller.org/downloads/) (bottom left) and the full installation instruction are on the [github wiki](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit).

**Comment by ohler55** [comment]
Thanks for leaving a note on the fix for the next person.
