### ISSUE TITLE
Sax Parser Auto-Closing Elements

### ISSUE THREAD

**Issue by mgeyer** [ohler55/ox#166]
Hi There,

I ran into unexpected behavior when trying to debug a file encoding issue I was having. It seems that the Sax parser is finding closing elements that don't exist.

```ruby
xml = <<~EOXML
  <a>
    <b>
      <c/>
    </b>
    <b>
      <c>
EOXML

class SaxParser < ::Ox::Sax
  def start_element(name); puts "start: #{name}"; end
  def end_element(name);   puts "end: #{name}";   end
end

Ox.sax_parse(SaxParser.new, xml)
```
produces
```plaintext
start: a
start: b
start: c
end: c
end: b
start: b
start: c
end: c
end: b
end: a
```
I would have expected an exception to be thrown or at least to end at `start: c`. Is that intended behavior?

**Comment by ohler55** [comment]
The SAX parser attempts to be as tolerant as reasonably possible. It keeps going if it can but generates errors when it detects problems. If you define the error() method on your parser it will be called when the elements are not closed.

**Comment by mgeyer** [comment]
Thanks for clarifying. Does this tolerance have anything to do with effort (https://github.com/ohler55/ox/blob/master/ext/ox/ox.c#L273)?

Also for what it's worth the error message is missing from https://github.com/ohler55/ox/blob/master/lib/ox/sax.rb#L48. Glad to make a small PR if it would help.

**Comment by ohler55** [comment]
The SAX options are different than the defaults.

You are correct, the error is missing from the docs. It's a one liner. I'll fix that and then you can close the issue.

**Comment by mgeyer** [comment]
Sounds good, thanks again for your help. I'll keep an eye out for the change and then will close.

**Comment by mgeyer** [comment]
Saw the update on master, think everything is finalized.
