### ISSUE TITLE
Escaping of "<" in attributes

### ISSUE THREAD

**Issue by lwilliams-oats** [ohler55/ox#167]
v2.4.11 seems to have introduced a regression in the escaping of "<" in attributes:

```
builder = Ox::Builder.new
builder.element(:div, title: '"<&>')
builder.pop
builder.to_s
# <div title="&quot;<&amp;>"/>
```
v2.4.9 gives `<div title="&quot;&lt;&amp;&gt;"/>`

**Comment by groe** [comment]
2.4.13b1 gives: `<div title=\"\"&lt;&amp;&gt;\"/>\n`

So `<` and `>` are now escaped again, but `"` is not. I have created a separate issue for that (#170).

**Comment by ohler55** [comment]
The recently pushed might be better.

**Comment by groe** [comment]
With 2.4.13b2 it works for me!

**Comment by ohler55** [comment]
I think the attribute and element content character maps are correct now.

**Comment by groe** [comment]
I can confirm. Version 2.4.13b3 from github returns `<div title="&quot;&lt;&amp;&gt;"/>\n` for the above test, which is correct.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by ohler55** [comment]
No response but tests pass so closing.

**Comment by lwilliams-oats** [comment]
Thanks, @ohler55 :thumbsup:
