### ISSUE TITLE
Lost whitespaces

### ISSUE THREAD

**Issue by groe** [ohler55/ox#168]
Hi!

While parsing a few XML files I've noticed that ox seems to skip some whitespaces between tags.

Here's a reduced test case:

```ruby
class MyParser < ::Ox::Sax
  def initialize
    @texts = []
  end
  def text(str)
    @texts << str
  end
  def texts
    @texts
  end
end

parser = MyParser.new
Ox.sax_parse(parser, "<sample><span>lorem</span> <span>ipsum</span></sample>")
parser.texts == ["lorem", " ", "ipsum"]
# => false
parser.texts
# => ["lorem", "ipsum"]
```

Not sure if this is meant as a feature (detecting indentation, xml formatting, etc.) but for my use case it's not really desirable. My goal is to convert XML files while keeping their original formatting wherever it is possible.

Any ideas on what's the issue here?

**Comment by ohler55** [comment]
Have you looked at the :skip option? That should work if you set the :skip value to :skip_none.

**Comment by groe** [comment]
I did, but the docs suggested that would be the default.

I just checked the docs again and realized they don't say that anymore (maybe I was reading an outdated version though...).

Thanks, will try and report back!

**Comment by groe** [comment]
It seems like `:skip_none` does not change the behaviour:

```ruby
parser = MyParser.new
Ox.sax_parse(
  parser,
  "<sample><span>lorem</span> <span>ipsum</span></sample>",
  skip: :skip_none
)
parser.texts
# => ["lorem", "ipsum"]
```

(And `:skip_none` is also the default, according to `Ox::default_options`)

**Comment by ohler55** [comment]
Pushed a version to github that is makes the callback on all text even all whitespace.

**Comment by groe** [comment]
Works like a charm, thanks a lot!

(Now I've ran into #170 but that's a separate issue)
