### ISSUE TITLE
SAX parsing triggers text callback too often 

### ISSUE THREAD

**Issue by larskuhnt** [ohler55/ox#171]
With this commit 238607c the `text` callback is getting called for text blocks between a closing- and opening tag. For example this XML 

```xml
<root>
  <tag1>1</tag1>
  <tag2>2</tag2>
</root>
```

will trigger the `text` callback not only with values `1`  and `2` but with `\n   ` as well. This is unexpected and breaks all my tests. The `skip: :skip_white` option should be default imho, as this change is not downwards compatible and will likely break a lot of applications that are using a SAX parser.

Thanks for this great library
Lars

**Comment by ohler55** [comment]
From the XML spec it is not clear to me which should be the default as element data is considered anything between the start and end tags. I propose we put it to a vote. Anyone interested please post your preference here. The options are :skip_node, :skip_return, and :skip_white as described in the Ox docs. I'll give it a week and make the default what the majority think.

**Comment by larskuhnt** [comment]
Thanks for the quick response.
But shouldn't it be the data between the same start and end tag only, for example `<tag1>` and `</tag1>`? The data between `</tag1>` and `<tag2>` is just whitespace to make it look nicer and should be ignored by the parser.

**Comment by ohler55** [comment]
Not everyone has the same thoughts. That was the reason the skip feature was added. Some people want to get every detail of the XML file to be able to recreate it exactly. As for the data content of the XML, you are correct the whitespace is or should be insignificant.

**Comment by awood45** [comment]
If you're going to change a default, my vote would be to make that a minor version bump at minimum, otherwise a breaking behavior change is hidden in a patch version bump.

**Comment by awood45** [comment]
It does look like explicitly setting `:skip_white` fixed our issue. So, it actually appears that making that a default is important to avoid the breaking behavior change.

**Comment by ohler55** [comment]
So far 2 votes for :skip_white.

**Comment by hakanensari** [comment]
Just wanted to chime in to :+1: :skip_white. As @ohler55 suggested, setting this option made tests pass again [here](https://github.com/hakanensari/peddler/commit/c42287cc61fa5b977b3c1232795a802f82f0a0cd#commitcomment-21921625) with the latest Ox.

**Comment by ohler55** [comment]
The winner is :skip_white. That will be in the next release coming soon.

**Comment by ohler55** [comment]
Release 2.5.0 completed with the change.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by larskuhnt** [comment]
As far as I am concerned yes, thanks for resolving this quickly.
