### ISSUE TITLE
Smart options adds additional elements in SAX parser

### ISSUE THREAD

**Issue by derSascha** [ohler55/ox#172]
Parsing `<ul><ul>Test</ul></ul>` with SAX parser and smart option enabled results in additional `ul` elements:
```
start: ul
end: ul    <-- ?
start: ul
text Test
end: ul
start: ul   <-- ?
end: ul    <-- ?
```
Is there a simple way to disable this behavior with smart option enabled?

**Comment by derSascha** [comment]
Looking at [ext/ox/sax_hint.c](https://github.com/ohler55/ox/blob/master/ext/ox/sax_hint.c#L150) and change this line
`{ "ul", false, false, false, ActiveOverlay, NULL },`
into
`{ "ul", false, true, false, ActiveOverlay, NULL },`
fixes the problem. Is there an simple configuration option to accomplish this?

**Comment by ohler55** [comment]
Ox is doing the right thing. The ul elements are not allowed to be nested so Ox closes the first one before opening the second. That covers the common error of forgetting to close a ```<ul>``` list. To turn off the ul hints you can make it inactive by passing in a :overlay option.

**Comment by derSascha** [comment]
Thanks for the fast replay :)

What i need is something like this:
```
...other stuff...
<ul id="123">    <!-- everything starting from here -->
  <li>...</li>
  <ul>...<li>...</li>...</ul>
</ul>   <!-- everything until this -->
....ohther stuff...
```
My current implementation simply increments/decrements a counter on `ul` elements starts/ends. On `id=123` a variable remembers the counter and if the counter gets lower than the remembered value, than the parser has left the scope.

This does not work if `<ul>` elements are inactive. Any suggestions?

And yes, you and ox are doing the right thing. Directly nested `ul` elements are not allowed, but handled by browser and a some big websites use this buggy thing...

**Comment by ohler55** [comment]
Maybe I can add something to allow the hints to be modified. Let me mull it over as to the best way to do that.

**Comment by ohler55** [comment]
Late getting back due to Oj releases. Now that has settled down it seems like the best, simplest approach is to add a new hint option. Maybe :nest_ok or something like that. What do you think?

**Comment by ohler55** [comment]
Release 2.5.0 with the described option.

**Comment by derSascha** [comment]
Works like charm. Thanks for the new feature.

There was just a copy & past bug. See #175
