### ISSUE TITLE
Sax Parsing Regression from 2.4.12 to 2.4.13

### ISSUE THREAD

**Issue by awood45** [ohler55/ox#173]
I'm still investigating how our usage may be impacting this issue, but opening this to share what I've found so far. The [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby) library has started to get failures in our Travis tests, but only for our "third party parsing gems allowed" setting, which I have narrowed down to the upgrade from `ox 2.4.12` to `ox 2.4.13`. See [aws-sdk-ruby Issue 1495](https://github.com/aws/aws-sdk-ruby/issues/1495).

Here is an example stack trace:
```
NoMethodError:
        undefined method `set_text' for #<Aws::Xml::Parser::Stack:0x007facc9bd08a8>
      # ./aws-sdk-core/lib/aws-sdk-core/xml/parser/stack.rb:32:in `text'
      # ./aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/ox.rb:14:in `sax_parse'
      # ./aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/ox.rb:14:in `parse'
      # ./aws-sdk-core/lib/aws-sdk-core/xml/parser.rb:44:in `parse'
      # ./aws-sdk-core/lib/aws-sdk-core/rest/response/body.rb:37:in `parse'
      # ./aws-sdk-core/lib/aws-sdk-core/rest/response/body.rb:23:in `apply'
      # ./aws-sdk-core/lib/aws-sdk-core/rest/response/parser.rb:32:in `extract_body'
      # ./aws-sdk-core/lib/aws-sdk-core/rest/response/parser.rb:13:in `apply'
      # ./aws-sdk-core/lib/aws-sdk-core/rest/handler.rb:8:in `block in call'
      # ./aws-sdk-core/lib/seahorse/client/response.rb:45:in `block in on'
      # ./aws-sdk-core/lib/seahorse/client/http/response.rb:139:in `block in on_success'
      # ./aws-sdk-core/lib/seahorse/client/http/response.rb:166:in `block in listener'
      # ./aws-sdk-core/lib/seahorse/client/http/response.rb:130:in `on_done'
      # ./aws-sdk-core/lib/seahorse/client/http/response.rb:137:in `on_success'
      # ./aws-sdk-core/lib/seahorse/client/response.rb:44:in `on'
      # ./aws-sdk-core/lib/aws-sdk-core/rest/handler.rb:8:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/s3_get_bucket_location_fix.rb:8:in `call'
      # ./aws-sdk-core/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
      # ./aws-sdk-core/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
      # ./aws-sdk-core/lib/seahorse/client/plugins/response_target.rb:21:in `call'
      # ./aws-sdk-core/lib/seahorse/client/request.rb:70:in `send_request'
      # ./aws-sdk-core/spec/services_spec.rb:144:in `block (5 levels) in <module:Aws>'
```

We consume the [ox gem here](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/ox.rb). I'm continuing to investigate, but if you have a notion about what has changed across these versions that would contribute to this regression, it would be helpful and appreciated. Thanks!

**Comment by ohler55** [comment]
It looks like your Stack.text() method is calling 'set_text'. Can you share the stack.rb file so I can take a look at it?

**Comment by ohler55** [comment]
The change may have had something to do with the :skip option. There is an open issue waiting on votes #171. Vote there for your preference.

**Comment by awood45** [comment]
I added my thoughts there - it does look like the most likely culprit. Going to see if explicitly setting that fixes the issue.

**Comment by awood45** [comment]
It does fix the issue - going to push that here, added revised thoughts to that issue.

**Comment by ohler55** [comment]
Thanks. I suspect there may be a problem waiting to occur in Stack.text() method as well but that is for you to decide of course.

**Comment by awood45** [comment]
This is possible, and merits a deeper look on our end. As for this, you can close this issue as we've resolved the failure.

**Comment by ohler55** [comment]
Thanks.
