### ISSUE TITLE
support for selecting elements by attribute (value)

### ISSUE THREAD

**Issue by moritzschepp** [ohler55/ox#178]
First of all, this is a great gem and I use it many times because of its leight install footprint and its speed. Thanks a lot for sharing it with everybody!

I found myself wishing for `Ox::Node#locate` to support selecting by attribute values on many occasions. Something like

    my_node.locate('*/furniture[@type=wood]/price')

Would be great. Future additions could include partial or even regex matching on the value.

**Comment by ohler55** [comment]
Not sure when I can get to it but I'll put it on the list.

**Comment by ohler55** [comment]
Please take a look at the 'each' branch. It took a while to get to it but I think it is what you are looking for.

**Comment by moritzschepp** [comment]
I'm looking at the docs and your test cases and this looks great! Thanks a lot! I will test this in production when I can give a time slice to the project I will use this with!
