### ISSUE TITLE
multi_xml tests fails since ox 2.4.13

### ISSUE THREAD

**Issue by valtri** [ohler55/ox#179]
Hi,

multi_xml testuite fails since ox 2.4.13. The commit causing it is 238607c (later there has been changed default options for skip mode in ox, which fixed two errors in multi_xml, but one error still remains).

I guess the problem is in different behavior between ox 2.4.11 and 2.4.13 of this:

    #! /usr/bin/ruby
    require 'ox'
    p Ox.parse("<tag>\n </tag>")

The failing multi_xml test (it somehow interprets the yaml part, so I think the problem are vanished the \n characters):

    #! /usr/bin/ruby
    require 'multi_xml'
    xml = "<tag type=\"yaml\">--- \n1: returns an integer\n:message: Have a nice day\narray: \n- has-dashes: true\n  has_underscores: true\n</tag>"
    p MultiXml.parse(xml, :disallowed_types => [])['tag']

I don't know, if this is a problem in ox or not.

**Comment by ohler55** [comment]
There is an Ox option for what to do with white space. Look at the :skip option.

**Comment by valtri** [comment]
So it is issue at multi_xml part and there should be added `:skip => :skip_none` in sax_parse() call. I've tested it works!

If I understand correctly, it was better to use this option also before ox 2.4.13?

What puzzles me this doesn't work: (maybe I'm using it wrong?)

    Ox.default_options[:skip] = :skip_none
    p Ox.parse("<tag>\n </tag>")

But this is not related to the problem with multi_xml.

**Comment by ohler55** [comment]
The correct approach to setting the defaults is
```ruby
Ox.default_options = { skip: :skip_none }
```

**Comment by valtri** [comment]
Thanks!

Sent pull-request to multi_xml: https://github.com/sferik/multi_xml/pull/60

**Comment by ohler55** [comment]
👍
