### ISSUE TITLE
Request for inline options for #sax_parse

### ISSUE THREAD

**Issue by gzigzigzeo** [ohler55/ox#180]
Good day.

This works, but breaks parsing in other places:

```
Ox.default_options = { mode: :generic, effort: :tolerant, smart: true }
```

This doesn't work:

```
Ox.sax_parse(h, StringIO.new(value), mode: :generic, effort: :tolerant, smart: true)
```

Also fails:

```
old_options = Ox.default_options
Ox.default_options = { ... }
Ox.sax_parse(....)
Ox.default_options = old_options
```

**Comment by ohler55** [comment]
Can you describe what you mean but "doesn't" work and "fails"? Maybe tell me what XML it fails on. Note also that the SAX parser does not support a mode as the callbacks are responsible for what ever behavior is desired. Also effort is not a SAX parser option. There is a smart option though. Check out the documentation on sax_parse here. http://www.ohler.com/ox/doc/Ox.html#sax_parse-class_method

**Comment by gzigzigzeo** [comment]
Yeah, sorry. First, "fails" means that `Ox.default_options` can not be changed temporary and even can not be read. `puts Ox.default_options` gives nothing. It's not the behaviour I've expected for regular Ruby hash.

I will provide failing XML sample tomorrow. That would be response from eBay API. Even `:smart` and `:effort` are not `sax_parse` options - they have effect on `#sax_parse`, so it seems little illogically for me that I can't control the behaviour of this method in-place.

**Comment by ohler55** [comment]
Odd, this is what I get with the current version. Seems to work fine.
```ruby
> irb -rox
irb(main):001:0> Ox.default_options
=> {:encoding=>nil, :margin=>"", :indent=>2, :trace=>0, :with_dtd=>false, :with_xml=>false, :with_instructions=>false, :circular=>false, :xsd_date=>false, :symbolize_keys=>true, :smart=>false, :convert_special=>true, :mode=>nil, :effort=>:strict, :skip=>:skip_none, :invalid_replace=>"", :strip_namespace=>false, :overlay=>nil}
irb(main):002:0> Ox.default_options = { mode: :generic }
=> {:mode=>:generic}
irb(main):003:0> Ox.default_options
=> {:encoding=>nil, :margin=>"", :indent=>2, :trace=>0, :with_dtd=>nil, :with_xml=>nil, :with_instructions=>nil, :circular=>nil, :xsd_date=>nil, :symbolize_keys=>nil, :smart=>nil, :convert_special=>true, :mode=>:generic, :effort=>nil, :skip=>:skip_none, :invalid_replace=>nil, :strip_namespace=>false, :overlay=>nil}
```

I'm not sure I followed the second paragraph. ```:smart``` is an option for ```Ox.sax_parse``` but ```:effort``` is not. I doubled checked the unit tests and the ```:smart``` seems to work fine in the cases tested. Is there some case you think it should work on but is not?

You lost me on the "can't control the behavior on this method in-place". Are you saying something about passing in the options or that you want the options for the non-SAX parser to be available in the SAX parser?

**Comment by gzigzigzeo** [comment]
Hm, strange that it did not work for me today (2.5.0 release). I've copied all the samples from my debug session, will double check it from my side.

Yes, I am saying that options supposed to not to have effect on sax_parse has that effect in my case.

Let me provide failing snippets then, I think it will make things clear. 

Brief background: I am using ox in two parts of my project: 1) eBay API response parsing 2) product descriptions parsing using google_translate_diff gem. eBay API response is strict xml, descriptions are usually malformed, non-valid HTML. SAX in both cases. If I try to set Ox.default_options for HTML parsing as docs recommends - eBay response parsing breaks because of some reason.

Today I've upgraded ox to 2.5.0 from 2.4.11, and that upgrade broke the project.

**Comment by ohler55** [comment]
I'll check the changes from 2.4.11 to 2.5 and see what might have broken something. Some example or tests would be super.

**Comment by ohler55** [comment]
Are you able to provide an example or is this no longer an issue?

**Comment by gzigzigzeo** [comment]
Hi. Thank you for long waiting. Looks, i've found the reason.

```ruby
require 'stringio'
require 'ox'

value = %(start       7 spaces before this)

class Sample < ::Ox::Sax
  def text(value); puts value; end

  class << self
    def parse(value, options = {})
      new.tap { |h| Ox.sax_parse(h, StringIO.new(value), options) }
    end
  end
end

Ox.default_options[:skip] # => :skip_white
Sample.parse(value) # => start 7 spaces before this

Ox.default_options = { mode: :generic, effort: :tolerant, smart: true }
Ox.default_options[:skip] # => nil
# ^ but, must be default value
Sample.parse(value) # => start       7 spaces before this
                    #            ^ :skip_none behaviour

# Passing :skip_white explicitly: behaviour is the same as with default options
Sample.parse(value, smart: true, skip: :skip_white) # => start 7 spaces before this
```
In docs, in global default_options skip field described as:
:skip [:skip_none|:skip_return|:skip_white] determines how to handle white space in text

In sax_parse options it is described as:
:skip [:skip_return|:skip_white] flag indicating the parser skips r or collpase white space into a single space. Default (skip space)

(no skip_none, plus default value is incorrect).

It was not expected behaviour for me that `Ox.default_options = { ... }` changes defaults which are supposed to stay unchanged. I've upgraded to 2.6.0 again, set :skip option explicitly in my code, will see how it works.

**Comment by ohler55** [comment]
Maybe there is a disconnect on what default_options are. The are meant to be the options used if none are over-ridden in the call options. They can be set or changed otherwise there really would be no point in providing them as options.

Please let me know how 2.6.0 works for you.

**Comment by ohler55** [comment]
Can this be closed?
