### ISSUE TITLE
Ox eat multiple spaces

### ISSUE THREAD

**Issue by r72cccp** [ohler55/ox#182]
Hi!
This is the nice gem, but, something went wrong:

Let,we have xml:
```xml
<item>
  <url>20170624\filename  2k.jpg</url>
  <photo>0</photo>
  ...
</item>
```

when ox read value in `<url>` - this text is returned: `20170624\filename 2k.jpg`. Ox eat one space and file name become wrong.

for read value i use this code:
```ruby
  def text(value)
    value
  end
```

Is way to prevent this behaviour?
With best regards.

**Comment by ohler55** [comment]
That is normal XML behavior if the specification is followed. You can change that in Ox with the :skip option. Try a value of :skip_none.

**Comment by r72cccp** [comment]
Thank you for answer! I'm closing the issue.

**Comment by r72cccp** [comment]
And, although this one is closed,
I want to note that
This was my most positive experience on github.
After all, I usually create a issue, in the hope that the answer will be this year, at least.
And today I received an answer before I found it myself.
It was unusual and cool!
Thousands of percent of health to the author of the repository
And by the way, this is a cool gem!

**Comment by ohler55** [comment]
Thanks. Nice to have the feedback.
