### ISSUE TITLE
.to_h

### ISSUE THREAD

**Issue by ohaddahan** [ohler55/ox#186]
Hi,

A .to_h will be a great addition.
I wrote an implementation for my usage , I'm sure it can be made much better :)

I pass and empty hash to this function and it fills it up (without adding nodes for attributes , just tags to keys).

Thanks,
Ohad.

```
def ApplicationHelper.ox_to_hash( el , parent )
    return if el.nil?

    if el.nodes.size == 1 && !el.nodes.first.is_a?(Ox::Element)
      if parent.has_key?(el.value)
        parent[el.value] = [parent[el.name] , el.nodes.first].flatten
      else
        parent[el.value] = el.nodes.first
      end
      return
    end

    if parent.is_a?(Hash)
      if !parent.has_key?(el.value)
        container = {}
        parent[el.value] = container
      else
        container       = {}
        parent[el.value] = [ parent[el.value] , container ].flatten
      end
    end
    el.nodes.each do |child|
      ApplicationHelper.ox_to_hash( child , container)
    end
  end 
```

**Comment by ohler55** [comment]
It seems like a conversion for a very specific use case. Can you explain when you use it and give an example of the conversion?

**Comment by ohaddahan** [comment]
@ohler55 it's a conversion to a Hash , I stumbled upon serious memory issues with Hash.from_xml and compared Hash.from_xml , Nokogiri based conversion and Ox based conversion.

https://gist.github.com/ohaddahan/8cbc355c25efb8b41748fd911355f653

The default Rails , Hash.from_xml is really bad , hence I think if you add native .to_h , you can be the new Hash.from_xml standard :)

BTW I also compared your Oj vs. JSON.parse and you won , so I'm now using both your Gems in my app for this very basic and common operation :)

**Comment by ohaddahan** [comment]
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>

Turns to:
{"note"=>{"to"=>"Tove", "from"=>"Jani", "heading"=>"Reminder", "body"=>"Don't forget me this weekend!"}}

**Comment by ohler55** [comment]
Much easier to read after the update. So, ignore element attributes and just pick up the text in the element body. Correct?

**Comment by ohaddahan** [comment]
@ohler55 well that depends on how 'strict' you want to be. I believe Hash.from_xml also add attributes as nodes. But I guess it can be an option , or an enhancement for future stages.

For my personal usage , they're unneeded.

Kudos again on an excellent implementation that really helps reducing memory allocations.

**Comment by ohler55** [comment]
Thanks.

So if such an implementation became part of Ox, where would the element attributes go in the conversion you are proposing? What do others do?

**Comment by ohaddahan** [comment]
https://www.w3schools.com/xml/xml_dtd_el_vs_attr.asp

```
<person sex="female">
  <firstname>Anna</firstname>
  <lastname>Smith</lastname>
</person>

```

Hash.from_xml :

`{"person"=>{"sex"=>"female", "firstname"=>"Anna", "lastname"=>"Smith"}}
`
My conversion : 
`{"person"=>{"firstname"=>"Anna", "lastname"=>"Smith"}}
`

**Comment by ohler55** [comment]
Ok, that seems reasonable. I'll look at making an addition later this week. Right now I am neck deep in setting up embedded Ruby for http://www.opo.technolog and the WABuR (https://github.com/ohler55/wabur) project. Turning out pretty well so far and super fast.

**Comment by jqr** [comment]
Would be awesome to see this supported natively! I was just about to start on this tonight until I saw this thread.

Backstory: I'm currently using [`xmlhasher`](https://github.com/cloocher/xmlhasher) to parse many millions of medium sized XML files, taking about 0.2s/each. In my investigation, it seems that `xmlhasher` is responsible for >99% of that time. So I was looking around to see how much speed improvement I could get by getting closer to `ox` and possibly removing some features unnecessary for my use (attributes, namespaces).

**Comment by ohler55** [comment]
That changes things a bit. I was thinking of just implementing the ruby version so it would be available but it sounds like maybe a hash mode for parsing might be better. I suspect that the hash mode would actually be faster than straight Ox in any other mode.

**Comment by jqr** [comment]
The Ruby version still makes sense to me if it’s easier to implement. For my use case, @ohaddahan’s code is ~2 orders of magnitude faster than the alternative. Would love more but I’m not greedy! 😁

**Comment by ohler55** [comment]
I'll look at it at the end of the week.I'm working through using embedded Ruby. Pretty excited about it. It's look good.

**Comment by ohaddahan** [comment]
@jqr wow you got 100X of my code? Can you post the comparison on a gist like I did , really interesting?
I was going mainly for memory issues , but I saw that Ox also gave me a nice speed improvement , which is an awesome surprise :)

**Comment by ohaddahan** [comment]
@ohler55 @jqr are you guys talking about Ox.parse_to_h( xml_string ) , and avoid the intermediate conversion?
That will be amazing!

**Comment by ohler55** [comment]
That is what I'm talking about.

**Comment by ohler55** [comment]
Okay, lets define what this thing is going to do. I was thinking 2 new modes, `:hash` and `:fullhash`. If either of you have better names please suggest them. Anyway, `:hash` will encode elements and text but not attributes. `:fullhash` will also encode attributes.

Text and elements will become Strings or Hashes unless there is more than one for a key in which case they will become an array of Strings or Hashes.

No attempts will be made to identify numbers, time, or any other pattern. Does that work for both of you? Maybe later I can add a detect option.

How does that sound?

**Comment by jqr** [comment]
I like that a lot and it works perfectly for my use.

I'm also fine with `:hash` being the most faithful representation with attributes and some more lengthy name for my specialized use(ex: `:hash_without_attributes`).

**Comment by jqr** [comment]
@ohaddahan my benchmark is fairly app specific, but if you head over to my branch of [`xmlhasher`](https://github.com/ready13/xmlhasher/blob/speed-investigation/benchmark/benchmark.rb) you can see a the benchmark file with a derivative of your code. I get approximately a 65% speedup on this, but again my app is doing significantly more on top of this which adds a lot.

**Comment by joshuamcginnis** [comment]
@ohaddahan Thanks for looking into this.

Slight issue with your method above in working with an API that returns xml:

```xml
<result>
    <variables>
         <var name="Blue">14</var>
         <var name="Jack">14</var>
         <var name="Magenta">12</var>
         <var name="Yellow">14</var>
    </variables>
</result>
```
```ruby
parsed = Ox.parse(result)
schema = {}
ox_to_hash(parsed, schema)
p schema
```

Outputs
`{"result"=>{"variables"=>{"var"=>["14", "14", "12", "14"]}}}`

Lost the attributes on the vars.

**Comment by ohler55** [comment]
I was planning on starting the Ox implementation tonight or tomorrow. What is the desired behavior for the example just given?

**Comment by joshuamcginnis** [comment]
Unlike the `<person/>` example above, the embedded elements act as an array, not additional attributes. 

I'm not sure we can ever know if nested elements are additional attributes of the parent element or if they are an array of children, unless all of the children have the same element name?

Here's one idea:

```ruby
{ node: 'variables': { children: [{ node: 'var', attributes: { name: 'Blue' }, value: '14' }] }
```

This breaks the `<person/>` example above. It becomes:
```ruby
{ node: 'person': { attributes: { sex: 'female' }, children: [{ node: 'firstname', value: 'Anna' }, { node: 'lastname', value: 'Anna' }]
```
The trade-off here is that users will likely need to take the extra step of building their own pretty hash from this version.

**Comment by jqr** [comment]
I'm generally trying to mirror [`Hash.from_xml`](url) from `ActiveSupport`, so in the mode without attributes this is what I'm after. This is what @ohaddahan's code produces as well:

```ruby
# Single tag
> Hash.from_xml '<result><variables><var name="Blue">14</var></variables></result>'
=> {"result"=>{"variables"=>{"var"=>"14"}}}

# Repeated tag siblings
> Hash.from_xml '<result><variables><var name="Blue">14</var><var name="Jack">14</var></variables></result>'
=> {"result"=>{"variables"=>{"var"=>["14", "14"]}}}
```

I just happened to notice that `ActiveSupport` supports the type attribute, so:
```ruby
> Hash.from_xml '<result type="integer">123</result>'
=> {"result"=>123}

I think for supporting attributes you'd have to do something like (`xml-simple`)[], although I don't have a need for this.

```ruby
# Single tag instance
> XmlSimple.xml_in '<result><variables><var name="Blue">14</var></variables></result>'
=> {"variables"=>[{"var"=>[{"name"=>"Blue", "content"=>"14"}]}]}

# Repeated tag instance
> XmlSimple.xml_in '<result><variables><var name="Blue">14</var><var name="Jack">14</var></variables></result>'
=> {"variables"=>[{"var"=>[{"name"=>"Blue", "content"=>"14"}, {"name"=>"Jack", "content"=>"14"}]}]}

# Attribute on parent of multiple children
> XmlSimple.xml_in '<result><variables a="1"><var name="Blue">14</var><var name="Jack">14</var></variables></result>'
=> {"variables"=>[{"a"=>"1", "var"=>[{"name"=>"Blue", "content"=>"14"}, {"name"=>"Jack", "content"=>"14"}]}]}
```

**Comment by jqr** [comment]
I'm generally trying to mirror [`Hash.from_xml`](http://api.rubyonrails.org/classes/Hash.html#method-c-from_xml) from `ActiveSupport`, so in the mode without attributes this is what I'm after. This is what @ohaddahan's code produces as well:

```ruby
# Single tag
> Hash.from_xml '<result><variables><var name="Blue">14</var></variables></result>'
=> {"result"=>{"variables"=>{"var"=>"14"}}}

# Repeated tag siblings
> Hash.from_xml '<result><variables><var name="Blue">14</var><var name="Jack">14</var></variables></result>'
=> {"result"=>{"variables"=>{"var"=>["14", "14"]}}}
```

I just happened to notice that `ActiveSupport` supports the type attribute. Not required for my use case but nice to have :)

```ruby
> Hash.from_xml '<result type="integer">123</result>'
=> {"result"=>123}
```

I think for supporting attributes you'd have to do something like [`xml-simple`](https://github.com/maik/xml-simple), although I don't have a direct need for this.

```ruby
# Single tag instance
> XmlSimple.xml_in '<result><variables><var name="Blue">14</var></variables></result>'
=> {"variables"=>[{"var"=>[{"name"=>"Blue", "content"=>"14"}]}]}

# Repeated tag instance
> XmlSimple.xml_in '<result><variables><var name="Blue">14</var><var name="Jack">14</var></variables></result>'
=> {"variables"=>[{"var"=>[{"name"=>"Blue", "content"=>"14"}, {"name"=>"Jack", "content"=>"14"}]}]}

# Attribute on parent of multiple children
> XmlSimple.xml_in '<result><variables a="1"><var name="Blue">14</var><var name="Jack">14</var></variables></result>'
=> {"variables"=>[{"a"=>"1", "var"=>[{"name"=>"Blue", "content"=>"14"}, {"name"=>"Jack", "content"=>"14"}]}]}
```

**Comment by joshuamcginnis** [comment]
Makes sense. Too bad I won't be able to use it though. I need the attribute names and values in the hash for the api client I'm writing.

**Comment by ohler55** [comment]
We have discussed having two modes, `:hash` and `:hash_no_attrs`. In the `:hash` mode I see something or maybe exactly what @jqr suggested or XmlSimple rules which seem natural. For the `:hash_no_attrs` mode the output would exclude element attributes. In both cases multiple element with the same key would become an Array.

That sound good to everyone?

**Comment by joshuamcginnis** [comment]
Sounds good here. If parsing / hashing is indeed faster than the alternatives, I'm perfectly fine massaging the result hash into something friendlier for my users.

Also, `xml-simple` has a several [options](https://github.com/maik/xml-simple/blob/master/lib/xmlsimple.rb#L264-L276) you may want to consider if not already included.

**Comment by ohler55** [comment]
Ox covers some (well, 2) but not all by any means. I'll leave it at that for the first cut and see what people ask for.

**Comment by ohler55** [comment]
While working on the `:hash` mode it seemed to make more sense to not follow the XMLSimple for including attributes. Instead of introducing a special keyword which could conflict with child elements the attributes are treated by a child element. The new addition is not complete but is ready for some benchmarking. I will add more unit tests and make sure the new modes work correctly for dumping. I also want to make sure a few options work with the modes. The branch is 'hash'.

**Comment by ohler55** [comment]
Any feedback?

**Comment by ohaddahan** [comment]
@ohler55 I personally don't need attributes (at least not in the near future).
So I don't mind what you decide on that :)

**Comment by ohler55** [comment]
Does the branch work as you expect or need?

**Comment by ohaddahan** [comment]
@ohler55 I checked it now , seems good.
I'm guessing that symbols as keys are used for better memory footprint.
I'll need to adjust my code accordingly.
When you plan on merging it with the main branch?

**Comment by ohler55** [comment]
The symbolize_keys option should work.ill merge once I get feedback from you and others or by Monday otherwise.

**Comment by ohaddahan** [comment]
@ohler55 they are already symbolised , I'll need to convert my code to use symbols instead of string keys. Not a big issue from my perspective.

**Comment by ohler55** [comment]
By setting the default_options or an option on parse that sets :symbolize_keys to false should leave the keys as strings.

**Comment by joshuamcginnis** [comment]
I need the attributes for this feature to be useful to me.

**Comment by ohler55** [comment]
There two modes. :Hash has attributes.

**Comment by joshuamcginnis** [comment]
Ah, roger - I see that in your post now. :) Just gave it a shot using the example above:

```xml
<result>
    <variables>
         <var name="Blue">14</var>
         <var name="Jack">14</var>
         <var name="Magenta">12</var>
         <var name="Yellow">14</var>
    </variables>
</result>
```

```ruby
doc = Ox.load(xml, mode: :hash)

{:result=>
  {:variables=>
    {:var=>
      [{:name=>"Blue"},
       "14",
       [{:name=>"Jack"}, "14"],
       [{:name=>"Magenta"}, "12"],
       [{:name=>"Yellow"}, "14"]]}}}
```
What is the logic here for building the results with attributes? It seems like there is an inconsistency:

```console
2.4.2 :046 > doc[:result][:variables][:var][0]
 => {:name=>"Blue"} 
2.4.2 :047 > doc[:result][:variables][:var][1]
 => "14" 
2.4.2 :048 > doc[:result][:variables][:var][2]
 => [{:name=>"Jack"}, "14"] 
2.4.2 :049 > doc[:result][:variables][:var][3]
 => [{:name=>"Magenta"}, "12"] 
2.4.2 :050 > doc[:result][:variables][:var][4]
 => [{:name=>"Yellow"}, "14"] 
```
I'd expect `[:var]` to have length 4 as there are 4 vars and that each would mirror the same `[{attributes_hash}, value]` format.

**Comment by ohler55** [comment]
I agree. I'll add that as a test case and fix it. Thanks.

**Comment by ohler55** [comment]
Ok, try it now.

It would be great is one of you can re-run your benchmarks with the new mode as a comparison.

**Comment by joshuamcginnis** [comment]
> Ok, try it now.
Works great!

Here's boilerplate if someone wants to use it to get some benchmarks going:
```ruby
# load local gem
$LOAD_PATH.unshift('~/sandbox/ox/lib')
require 'ox'
require 'benchmark'

xml = File.read('test.xml')

n = 50000
Benchmark.bm do |x|
  x.report('ox-hash') { Ox.load(xml, mode: :hash) }
end
```

**Comment by ohler55** [comment]
Released after some pain with an API change in Ruby 2.4.2.

**Comment by ohaddahan** [comment]
@ohler55  sorry for the delay.
https://gist.github.com/ohaddahan/cdaef533abf963f16f7bccec141c2185

There seem to be an issue , an Array is generated even when there are no repeated keys.
All the details inside Gist.

**Comment by ohler55** [comment]
You are using the :hash mode which includes attributes. Those attributes are put in a hash and then in an array that will include the element's children.

**Comment by ohaddahan** [comment]
@ohler55 changed it , now `ox1 == ox2`.
After deducting what seems to be an issue in `memory_profiler` the top level results are around 10K vs 30K compared to the new implementation.
Awesome job!

Total allocated: 180247 bytes (1629 objects)
Total retained:  174871 bytes (1564 objects)

allocated memory by gem
-----------------------------------
    170184  memory_profiler-0.9.8
      8783  other
      1280  activesupport-5.0.0

Total allocated: 30379218 bytes (218956 objects)
Total retained:  30358126 bytes (218604 objects)

allocated memory by gem
-----------------------------------
  30350941  memory_profiler-0.9.8
     26437  chili-hunter-2/app
      1840  activesupport-5.0.0

**Comment by ohaddahan** [comment]
I'll try migrating to symbolized keys too , will only do good for my memory footstamp since the keys will be repeated many times.

**Comment by ohaddahan** [comment]
@ohler55 
I'm seeing that when you symbolise you also lower case the first character.
Is it possible to keep simply use a `to_sym` keys without the first character change?

Is it one of` Ox.default_options` ?

 `{:encoding=>nil, :margin=>"", :indent=>2, :trace=>0, :with_dtd=>false, :with_xml=>false, :with_instructions=>false, :circular=>false, :xsd_date=>false, :symbolize_keys=>true, :smart=>false, :convert_special=>true, :mode=>nil, :effort=>:strict, :skip=>:skip_white, :invalid_replace=>"", :strip_namespace=>false, :overlay=>nil} `

**Comment by ohaddahan** [comment]
@jqr @joshuamcginnis @ohler55  everyone satisfied? Can I close the issue?

**Comment by ohler55** [comment]
Ok to to close as far as I'm concerned. Are your benchmarks showing a 5x performance improvement? Seemed like it from the gist but that was :hash mode not :hash_no_attrs.

**Comment by ohaddahan** [comment]
@ohler55 I tried `:hash_no_attrs` too , the numbers were very similar.
So that's around 2X-3X improvement on run-time and memory , which was already the best as far as I'm aware of.
You should ping the Ruby / Rails core team and put your Gems as the default implementations :)

**Comment by jqr** [comment]
This is looking very promising! I'm hoping to do some testing today but if you guys are confident with the output, trust your heart.

**Comment by ohler55** [comment]
I think the Rails team has other ideas. :-)

**Comment by ohaddahan** [comment]
@jqr the Gem was already updated , the issue can stay open until you get around to report your findings too. This issue raised much more interest than I expected :)

**Comment by joshuamcginnis** [comment]
ohler55 The updates and working great so far. It's very fast and I think that'll help give my gem an advantage over the alternatives. Nice work - thanks for doing this!

**Comment by ohler55** [comment]
Great. Glad to help.

**Comment by ohaddahan** [comment]
@ohler55 FYI https://gist.github.com/ohaddahan/cfd8e452174732957872ecd7bc32bcc3 
You're also kicking ass on this comparison :)

**Comment by ohler55** [comment]
Thanks for the info. It looks great!

**Comment by tilo** [comment]
@ohler55 Peter, this is awesome!
It would be good to also cover this feature in the README

**Comment by ohler55** [comment]
Added mention in README.md.
