### ISSUE TITLE
Ignore Embedded Elem

### ISSUE THREAD

**Issue by joshuamcginnis** [ohler55/ox#188]
I'm working with an API that returns an element with possible HTML in it that is not protected via CDATA.

For example:
```xml
<result>
  <description>This line is <BR/> broken by one or more <BR/></description>
</result>
```

Parsing this will result in description having multiple child nodes instead of just the description. 

Is there a way around this? I've tried various combinations of the following options to no avail. 

```ruby
Ox.default_options = {
  effort: :strict,
  symbolize_keys: true,
  smart:  true,
  overlay: {
    'BR' => :block
  }
}
```
Worse-case scenario is I will sgsub these tags from the raw xml before parse.

**Comment by ohler55** [comment]
I believe `:inactive` or `:off` should ignore them. If you want them in the output then they have to go somewhere though.

**Comment by joshuamcginnis** [comment]
Neither work, I'm still getting nested <`Ox::Element:0x007fc6352c9888 @value="BR">` elems.

**Comment by joshuamcginnis** [comment]
Complete example:
```ruby
require 'ox'

xml = <<EOM
<result>
  <description>This line is <BR/> broken by one or more <BR/></description>
</result>
EOM

Ox.default_options = {
  effort: :strict,
  symbolize_keys: true,
  smart:  true,
  overlay: {
    'BR' => :off
  }
}

p Ox.parse(xml)
```
```
##<Ox::Element:0x007feb2893f7b8 @value="result", @nodes=[#
<Ox::Element:0x007feb2893f718 @value="description", @nodes=["This line is ", #
<Ox::Element:0x007feb2893f588 @value="BR">, " broken by one or more ", #
<Ox::Element:0x007feb2893f510 @value="BR">]>]> 
```

**Comment by ohler55** [comment]
Are you using the SAX parser? I would not expect to see OX::Elements unless you are creating them in your SAX handler.

**Comment by ohler55** [comment]
I see, you are using Ox.parse. The overlays are only for the SAX parser.

**Comment by joshuamcginnis** [comment]
Ah roger. Thanks!

**Comment by ohler55** [comment]
Lets leave the issue open until I get it finished 😄

**Comment by ohler55** [comment]
oops, wrong issue. My bad. Closing again.
