### ISSUE TITLE
GCC 4.4.7 support

### ISSUE THREAD

**Issue by jhej** [ohler55/ox#192]
Ox 2.8.0 does not compile under GCC 4.4.7, because of the use of the `_Noreturn` keyword. Maybe future versions could add a compiler version check to not specify this keyword for legacy compilers?

**Comment by ohler55** [comment]
Thanks for the update. I'll get a fix in. Not soon I'm afraid but I will get it on the list.

**Comment by ohler55** [comment]
Just released 2.8.1 that I think has a fix. If you can check it that would be great.

**Comment by jhej** [comment]
Yes, it works now, thanks a lot!
