### ISSUE TITLE
parse(xml, mode: :hash) vs Hash.from_xml(xml)

### ISSUE THREAD

**Issue by tilo** [ohler55/ox#198]
Thank you for adding the direct parsing to a hash! This is super useful!

I found a corner case where `parse(xml, mode: :hash_no_attrs)` might want to mimic what `Hash.from_xml(xml)` does.

When parsing an Oracle Atom feed ( 😭  😷  ), I found this case of an empty XML link tag:

```
<entry><link href=\"https://somewhere.oraclecloud.com/hcmCoreApi/atomservlet/employee/newhire/EMP300000012345678\" rel=\"edit\"></link><id>atomservlet:newhire:EMP300000012345678</id>
<link href=\"https://somewhere.oraclecloud.com/hcmCoreApi/resources/latest/emps?q=PersonId=300000012345678&effectiveDate=2017-10-11\" rel=\"related\">
</entry>
```

Hash.from_xml parses this as:

```
{ "entry" => 
   {
     "link" => [
                     {
                        "href" => "https://somewhere.oraclecloud.com/hcmCoreApi/atomservlet/employee/newhire/EMP300000012345678",
                         "rel" => "edit"
                    },
 {
                        "href" => "https://somewhere.oraclecloud.com/hcmCoreApi/resources/latest/emps?q=PersonId=300000012345678&effectiveDate=2017-10-11",
                         "rel" => "related"
                    }
      ],
     "id" => "atomservlet:newhire:EMP300000012345678"
  } 
}
```

whereas `parse(xml, mode:  #:hash_no_attrs)` parses this as:

```
{ "entry" => 
   {
     :link => [
                     nil,
                     nil
                ],
                       :id => "atomservlet:newhire:EMP300000012345678",
  }
}
```

For the rest of the XML parsing, the attributes should be ignored - only for empty tags they should be processed.

It might be nice to add an exception for this or add a mode.

**Comment by ohler55** [comment]
I'm torn. Putting in more modes for different possible conditions adds to bloat. On the other hand it would be nice to have some way to handle arbitrary conditions. Let me think about possible alternatives. Maybe callback for specific conditions like empty elements or element names.

**Comment by tilo** [comment]
I'm not sure if a new mode is the right answer, or modifying what hash_no_attrs does, 
but completely Ignoring "empty" XML nodes does not seem to be very useful.

I think there is value in providing compatibility with Hash.from_xml.

**Comment by ohler55** [comment]
I don't want to get caught in trying to make Ox compatible with any other gem, especially Rails. It only leads to issues later as Ox tries to chase changes in the gem or worse has to match different versions of that gem. It has been a never ending headache with Oj trying to match the JSON gem and Rails.

Right now the two modes are clear, either pull in attributes or don't. You are asking for something that is between those two modes. Empty elements in your case might not be useful but I think you will find other have different opinions depending on the application. The challenge is giving options without impacting ease of use and performance.

**Comment by ohler55** [comment]
Is this a dead issue?
