### ISSUE TITLE
Escaping '<' and '>' in attributes when dumping xml

### ISSUE THREAD

**Issue by JeroenBrinkman** [ohler55/ox#201]
According to chapter 2.4 of https://www.w3.org/TR/xml/
```text
The ampersand character (&) and the left angle bracket (<) must not appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. 
If they are needed elsewhere, they must be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. 
The right angle bracket (>) may be represented using the string " &gt; ", and must, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.
```
This means that `<` must be escaped to `&lt;` in attributes
This does not currently happen when dumping Ox documents to string. However when parsing xml the `&lt;` and `&gt;` are properly deserialised.
The following spec is a minimal failing example:
```ruby
it "Escapes '<' and '>' properly in attributes" do
  xml = %{\n<top name="&lt;test&gt;">value</top>\n}
  doc = Ox.parse(xml)
  expect(doc.attributes[:name]).to eql '<test>'
  dumped_xml = Ox.dump(doc)
  expect(dumped_xml).to eql xml
end
```
Fails like this:
![image](https://user-images.githubusercontent.com/5592764/36902587-4bd878c6-1e2b-11e8-9c85-e457df8cb08f.png)

Important note being that Ox itself does not have any issues parsing the both the input and the output.
Maybe there is there an option i need to enable to get my desired behaviour?

**Comment by ohler55** [comment]
It does look like an oversight. String values work correctly but attribute values are not encoded correctly. Interesting is that no one else has noticed this over the years. I'll get it fixed.

**Comment by JeroenBrinkman** [comment]
Thanks for the fast reply! I'll keep a look on this issue for the status.

**Comment by ohler55** [comment]
Please try release 2.8.3.

**Comment by JeroenBrinkman** [comment]
It works with release 2.8.4, thanks!
