### ISSUE TITLE
Incorrect HTML dumped after being parsed

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/ox#202]
Dumping HTML data after parsing it via `Ox.parse` results in incorrect HTML
```ruby
Ox::VERSION == "2.8.4"
```
```ruby
require 'ox'

html = <<-HTML
<!DOCTYPE html >
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hello World</title>
  </head>
  <body>
    <h1>Hello World</h1>
    <p>Lorem Ipsum Dolor Sit</p>
  </body>
</html>
HTML

Ox.default_options = {
    mode:   :generic,
    effort: :tolerant,
    smart:  true
}
puts Ox.dump(Ox.parse(html))
```
The output being:
```
<!DOCTYPE html >
<html>
  <head>
    <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Hello World</title>
      </meta>
    </meta>
  </head>
  <body>
    <h1>Hello World</h1>
    <p>Lorem Ipsum Dolor Sit</p>
  </body>
</html>
```
Either this is a bug or there's documentation missing on how to parse, alter and re-constitute HTML like Nokogiri..

**Comment by ohler55** [comment]
Ox is first an XML parser so it sees the first meta as not being terminated. Try parsing as HTML instead. I can provide code tomorrow although there are some docs and test for HTML if you want to take a look first.

**Comment by ohler55** [comment]
The Ox class method to to use is described here http://ohler.com/ox/Ox.html#sax_html-class_method. The `Ox.parse()` method is for XML parsing. To parse HTML the SAX parser should be used or more accurately the `Ox.sax_html()` method.

**Comment by ashmaroli** [comment]
Thanks for the response, Pete.
I did find a [StackOverflow question](https://stackoverflow.com/a/43427991/7681659) that recommended using `:sax_html` method instead of `:parse` for HTML, though I couldn't find a confirmation (or a walkthrough :stuck_out_tongue: ) in the gem / repo README..

**Comment by ohler55** [comment]
I suppose a set of examples with comments might be helpful. There are many use cases.

**Comment by ashmaroli** [comment]
> I suppose a set of examples with comments might be helpful.

That'd be great.
My particular use-case involves parsing an HTML document, altering the child-level tags to `<body>` element in the HTML file and reconstituting the document by *dump*-ing the altered markup and finally benchmark this entire process against Nokogiri..

**Comment by ohler55** [comment]
You know my weakness, benchmarks. Now I have to put together something. 😊

Can you give an example of what you mean by tags?

**Comment by ohler55** [comment]
Take a look at the `examples` branch. There is a `saxy_html.rb` example that is a framework for what I think you are looking for. I'll be adding more examples but this is a start anyway.

**Comment by ashmaroli** [comment]
I'll clarify my use-case a bit more..
The following is from a Jekyll Plugin that modifies HTML generated by Jekyll.. (for context, Jekyll is a static site generator that generates HTML files from Markdown and Liquid templates)
```ruby
  if doc.output.include?("<body")
    parsed_doc    = Nokogiri::HTML::Document.parse(doc.output)
    body          = parsed_doc.at_css("body")
    body.children = process(body)      # replace contents of <body></body> with the altered HTML output from the plugin
    doc.output    = parsed_doc.to_html # overwriting the `Jekyll::Document` output
  else
    [...] # similar steps using `Nokogiri::HTML::DocumentFragment.parse` instead of `Nokogiri::HTML::Document.parse`
  end
```
In essence, I simply want to *test* if the method above can be made more performant by replacing `Nokogiri` with `Ox` or another faster HTML parser in Ruby..

**Comment by ohler55** [comment]
So basically keep the header and replace the rest, right? What is the output type from `process(body)` and what type is `body`? With the example I gave, there is not intermediate form for body. For the best performance not using an intermediate form is best as it does not create many additional Ruby objects. Do you have some flexibility about what the `process` function takes as input and returns?

**Comment by ashmaroli** [comment]
> What is the output type from `process(body)` and what type is `body`?

`body` is an instance of `Nokogiri::XML::Element` and `body.children=` in the code above is assigned altered HTML String of the nested contents of `<body>`

**Comment by ohler55** [comment]
I see. Assigning the body or inserting and XML string into the output is easy enough. Having to build Nokogiri element is really outside of the scope of an example as it would become a lesson on how to use Nokogiri and not Ox.

If the `process` function is one that you are writing how about a more generic API instead of being locked into a specific gem?

**Comment by ashmaroli** [comment]
At this point, its all experimental.. the plugin in reference has been around for a few years now.
I'm just trying to see if *I can replace `Nokogiri` with `Ox`*, producing the same results but at lesser computational time..

But I think `Ox` is not designed for this particular scenario.
So, I'll close this ticket now..

Thanks for your time.

**Comment by ohler55** [comment]
I'd have to agree that Ox is not designed to generate Nokogiri nodes. It would work quite well if the `process` function took Ox nodes or something more generic but Ox is not a drop in replacement for Nokogiri. Thanks for getting me going on examples anyway.

**Comment by ashmaroli** [comment]
`process` function can take `Ox` nodes if need be.. the function just needs to manipulate HTML and return the manipulated markup.
`Nokogiri` just seems to have well-defined end-points to get the job done in simpler steps:

  1. Parse given HTML
  2. Search parsed data for `<body>` element
  3. Rewrite descendant nodes of the found `<body>` element (as minimally altering as possible)
  4. Dump new markup

**Comment by ohler55** [comment]
So Ox would have to support HTML using the `Ox.parse` and `Ox.dump` method. Something to put on the requested feature list. I can see how it involves fewer steps even if the SAX/Builder combo has the potential to be a lot faster.
