### ISSUE TITLE
Same output for different XML when mode: :hash used

### ISSUE THREAD

**Issue by Masa331** [ohler55/ox#204]
Hi Peter,

i'm using Ox(and it's great!) for XML parsing with mode: :hash but i'v come to one possible scenario when i don't know how to determine if the parsed code are 2 elements or one element with attributes.

Here are simple examples:
order_1.xml
```xml
<?xml version="1.0"?>
<order>
  <item>
    <name>chair</name>
  </item>

  <item>
    <name>table</name>
  </item>
</order>
```
```ruby
Ox.load(File.read('./order_1.xml'), mode: :hash)
=> {:order=>{:item=>[{:name=>"chair"}, {:name=>"table"}]}}
```

order_2.xml
```xml
<?xml version="1.0"?>
<order>
  <item name="chair">
    <name>table</name>
  </item>
</order>
```
```ruby
Ox.load(File.read('./order_2.xml'), mode: :hash)
=> {:order=>{:item=>[{:name=>"chair"}, {:name=>"table"}]}}
```

I will probably use `::parse` instead and go from there but i just want to check than i'm not missing something or maybe there is some workaround to always determine what's element and what attribute? Sorry to bother you

Thanks!

**Comment by ohler55** [comment]
Try :hash_with_attrs. It may be more of what you want.

**Comment by Masa331** [comment]
There is a mode :hash_with_attrs? I get an error whenever i try it:

```ruby
Ox.load(File.read('order_1.xml'), mode: :hash_with_attrs)
# => Ox::ParseError: :mode must be :generic, :object, :limited, :hash, :hash_no_attrs.
```
I also didn't find this mode anywhere in the repo

**Comment by Masa331** [comment]
Yeah i already used the generic one. Thanks for your time. Closing this
