### ISSUE TITLE
Question: Is it possible to convert tags in hash mode?

### ISSUE THREAD

**Issue by h8is2w8** [ohler55/ox#205]
First of all: Thanks for this lib. I really like its interface and speed!
Can you answer, is it possible to convert tags in hash mode?  I want to achieve below result, but can't find any info.

```
require 'ox'

xml = %{
<Top name="sample">
  <Middle name="second">
    <Bottom name="third">Rock bottom</Bottom>
  </Middle>
</Top>
}

puts Ox.load(xml, mode: :hash, convert_tags_to: -> (tag) { tag.downcase })

# => {:top=>{:middle=>{:bottom=>"Rock bottom"}}}
```

**Comment by ohler55** [comment]
I'm afraid that is outside the scope of the parser. The SAX parser does allow you to change element names to anything you want though.

**Comment by h8is2w8** [comment]
Wow! Replies are fast too :)

Ow, I would like to see this feature. Anyway, thanks for the answer 👍
