### ISSUE TITLE
Ox.load support for snakecase for keys

### ISSUE THREAD

**Issue by stepozer** [ohler55/ox#209]
Example:

```
xml = '<Aa>hello</Aa>'
puts Ox.load(xml, mode: :hash, snakecase: true)
>> {:aa=>"hello"}
```

Hi, is it possible?

**Comment by ohler55** [comment]
That is not an Ox option. It would be easy enough to iterate over a parsed XML and change the element names though. Maybe not as efficient as in C but this is a very specific request.

**Comment by stepozer** [comment]
Hi,

I have this option in another gem (https://github.com/cloocher/xmlhasher)

```
XmlHasher.configure do |config|
  config.snakecase = true
  config.ignore_namespaces = true
  config.string_keys = false
end
```

but right now this gem is not supported. I want change current code to your gem and C realization will have good performance. Right now we parse 2.2 Mb XML 1000 times every minute. So, if it not possible, how I can to do it?

**Comment by ohler55** [comment]
Before even thinking about adding a key converted option to Ox you can try using `Ox.load` and then iterate over the Ox::Elements and change the name of each element. Call `element.value = 'new_name'`. Then loop over each element node `element.nodes.each`.

If the performance using that approach is fast enough maybe there is no need for the Ox parser to convert.

It be nice to find out how may other people out there are interested in a key converter feature.

**Comment by stepozer** [comment]
Hi! I think about this feature about new way. Maybe we can try add something like this:

```
Ox.load(
  xml, 
  mode: :hash, 
  convert_key_to: lambda { |key| key.snakecase }
)
```

In this case each develop can setup `convert_key_to` to own. And for me it will be better that iterate Ox::Elements, because I want to get hash after xml transform without additional object generation.

**Comment by ohler55** [comment]
That seems more generally useful. Let me toy with that a bit.

**Comment by ohler55** [comment]
Give the `key-mod` branch a try and see if it works for you.

**Comment by stepozer** [comment]
Hi!

Thank you! I will compare XmlHasher, old ox gem version and new one. Will let you now about results.

**Comment by ohler55** [comment]
I hadn't hear from you so I released anyway.

**Comment by stepozer** [comment]
Hi,

Sorry was to busy on this week. So I checked your new version and get very good resuls. I compared:

```
ox (2.10.0)
```

and

```
ox (2.2.1)
xmlhasher (1.0.2)
  escape_utils (>= 1.2.0)
  ox (= 2.2.1)
```

I used XML ~450Kb. This is result table:

XmlHasher:
```
Time elapsed 6.530042999998841 seconds
Time elapsed 7.226911000001564 seconds
Time elapsed 6.842355999999199 seconds
Time elapsed 6.865918999999849 seconds
```

Simple Ox:
```
Time elapsed 4.322981999999683 seconds
Time elapsed 4.615324000000328 seconds
Time elapsed 4.367915000000721 seconds
Time elapsed 4.633617999999842 seconds
```

Ox with map cache:
```
Time elapsed 0.6337219999986701 seconds
Time elapsed 0.6482099999993807 seconds
Time elapsed 0.6256369999973685 seconds
Time elapsed 0.6547280000013416 seconds
```

xml_hasher_test.rb:

```
XmlHasher.configure do |config|
  config.snakecase = true
  config.ignore_namespaces = true
  config.string_keys = false
end

time = Benchmark.realtime do
  100.times do
    XmlHasher.parse(xml)
  end
end
puts "Time elapsed #{time} seconds"
```

ox_test.rb:
```
ep   = lambda { |key| Util.snakecase(key) }
time = Benchmark.realtime do
  100.times do
    Ox.load(xml, mode: :hash, element_key_mod: ep)
  end
end
puts "Time elapsed #{time} seconds"
```

ox_with_cache_test.rb:
```
@map = {}
ep = lambda { |key|
  if @map[key]
    @map[key]
  else
    @map[key] = Util.snakecase(key)
  end
}
time = Benchmark.realtime do
  100.times do
    Ox.load(xml, mode: :hash, element_key_mod: ep)
  end
end
puts "Time elapsed #{time} seconds"
```

Thank you!

**Comment by ohler55** [comment]
Nice results indeed.
