### ISSUE TITLE
feature request: attribute value check while parsing

### ISSUE THREAD

**Issue by dn** [ohler55/ox#211]
Thank you for Ox and Oj.

We often need selectors like:
```
node_a/node_b[@attribute = 'value']/node_c
```

I think it's possible to implement without breaking the current behaviour from ```[]```. If I prepare a PR would you consider it?

**Comment by ohler55** [comment]
I certainly consider a PR for that.

**Comment by ohler55** [comment]
Closing. A PR would still be fine.
