### ISSUE TITLE
Question/Feature Request: Object-defined dump and load

### ISSUE THREAD

**Issue by ForeverZer0** [ohler55/ox#212]
First, just recently discovered this, and it is immediately moved to the top of my "most useful gems" list. Thank you very much for creating this, it is greatly appreciated.

My question is this, as I did not see any way to do this in the documentation, or looking through the extension source with my limited C experience, could it be possible to "override" the resulting XML when dumping/loading an object? I have used this functionality quite commonly when using Marshal by defining custom "_dump" and "self._load" functions to manually control the serialization of the data. 

As this is XML, the issue is not near as important as I primarily used it as a way to know the binary format when working with the same data in other languages. 

Just curious if it could be possible to be able to define a "self._ox_load" and "_ox_dump" methods in a class that parse XML and return a node respectively, and when defined those methods are invoked instead of using the internal parsing method?

This is a fairly common feature in most serialization formats and/or languages, just hoping to see it with this wonderful little gem as well. If not, no biggie, I will continue to love it either way.

**Comment by ohler55** [comment]
If I understand correctly you would like Ox to check for a method on an object before serializing it. Something like `#as_xml` or maybe a better name that would then be encoded as XML when using the `:object` mode. Is that correct? Just making sure I understand first before committing to anything. :-)

**Comment by ForeverZer0** [comment]
Yes, basically the same exact behavior as defining a _dump/_load and/or marshal_dump/marshal_load method does. When serializing, it first checks if those methods are defined. If so, they are invoked instead of using Marshal's default implementation. 

For this lib, I think passing a node object to/from the custom methods would be more intuitive than a binary string as Marshal does, but the exact same concept.

**Comment by ohler55** [comment]
How about the method returning a Node object? Seems like a good addition. I'll create a branch over the next week and let you give it a try before releasing it.

**Comment by ForeverZer0** [comment]
That would be perfect, thank so much for the quick response.

By the way, in my project have an option to compress the XML with Zlib when saving/loading, and Ox was STILL faster than Marshal (only marginally so when using max compression levels), and the file sizes are on average 30-40% the size of their Marshal equivalent. 

Given, using Zlib defeats the purpose of human-readable format, but is optional in my project, and Zlib is pretty standard in most popular languages, so it still fits my needs in this project.

Thanks again, great job.

**Comment by ohler55** [comment]
Object serialization was the initial reason for Ox 7 years ago.

**Comment by ohler55** [comment]
Here are some thoughts.

There are two basic ways to use Ox, either for object marshaling and un-marshalling or for more general parsing and writing.

I'm hesitant to allow users to add their own encoding to objects being marshaled as there is no facility to detect how to un-marshall at this point. It could be done but it is a bigger effort.

For general dumping I could see adding a `#as_ox` method to an object that returned an`Ox::Node` object. There is no need for a reciprocal reconstruction on loading so it would be pretty straight forward to implement.

Which one of those two were you interested in or did I miss it?

**Comment by ForeverZer0** [comment]
I think perhaps you misunderstand what I mean. The same exact way that Ruby's Marshal module does not need to know how to marshal/un-marshal an object that defines a _dump or _load method. If the _dump method is defined, it simply invokes instead of using its own method, and expects that the method returns a binary string. It doesn't matter what it is, it doesn't need to know, it is just binary to write. 

All Ox would have to do would be to pass an empty "object" node to a _ox_dump (as example) method, containing the class name attribute. The user who overrides this _ox_dump method has the responsibility of populating it as they see fit, and return it at the end of the method.

On the loading side, when Ox encounters an object node, reads the class. Before enumerating the child nodes, it simply checks for a singleton method of that class "_ox_load", and if it responds, the node is passed to that method and it does not use the built in parsing. Ox does not need to know how the node is parsed. It just passes the node to the method and expects an object returned. The user-defined _ox_load takes care of the parsing. 

So really, the only additions that would need added would be to check if an object responds to _ox_dump before dumping it, and when parsing to see if it responds to _ox_load. The user who defines those methods in their classes has all the responsibility of populating the node for a dump, and parsing the node for a load. 

[Ruby Marshal _dump and _load](http://ruby-doc.org/core-2.2.2/Marshal.html#module-Marshal-label-_dump+and+_load)

Here is a really basic example using Ruby psuedo-code for an Ox module as what the C side would have to do.

```ruby
module Ox 

  def self.parse_a_node(node)
    if node.name == "o"
      class_name = node['c']
      obj_class = Object.const_get(class_name)
      if obj_class.respond_to?(:_ox_load, true)
        return obj_class.send(:_ox_load, node)
      end
      # Otherwise parse object as normal
    end
  end

  def self.dump_an_object(object)
    node = Element.new('o')
    node['c'] = object.class.to_s
    if object.respond_to?(:_ox_dump, true)
      return object.send(:_ox_dump, node)
    end
    # Otherwise dump as normal
  end
end

# And how it could be used in a very poor example...

class MyClass

  def initialize(x, y)
    @x = x
    @y = y
    @double_x = x * 2
    @triple_y = y * 3
  end

  private
  def _ox_dump(node)
    child = Ox::Element.new("XY")
    child['x'] = @x
    child['y'] = @y
    node << child
    node
  end

  private
  def self._ox_load(node)
    x = node.XY['x'].to_i
    y = node.XY['y'].to_i
    MyClass.new(x, y)
  end
end
```

**Comment by ohler55** [comment]
I was afraid thats what you were asking for. That will take a bit longer to implement. I'll add a new type indicator to the object serialization indicator map and proceed from there.

The dump method should not take a node though. Ox will set the type indicator and class so maybe expect back either a node or a Hash from the `#ox_dump` method. Not sure which is better. Probably a `Ox::Node`.

**Comment by ohler55** [comment]
Is this still an issue?

**Comment by ForeverZer0** [comment]
Not really an issue per se, but was feature request to make the library way more versatile, especially when trying to make use of it to work as a common data format for object serialization to be shared across multiple languages.

Feel free to close if not planning to implement, as JSON and YAML are likely better suited formats for this kind of thing, as they are a more basic by design to achieve this.
