### ISSUE TITLE
Bundler: Deprecation Notice

### ISSUE THREAD

**Issue by topofocus** [ohler55/ox#214]
bundle update
Fetching https://github.com/ohler55/ox.git
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/ubuntu/.rvm/gems/ruby-head/bundler/gems/ox-c2238ef2b652/ox.gemspec:28.

**Comment by ohler55** [comment]
Fixed in release 2.9.3 which was just released. Thanks.

**Comment by topofocus** [comment]
Thank you very much for maintaining the Gem.

Grüße

Hartmut Bischoff



2018-06-13 3:09 GMT+02:00 Peter Ohler <notifications@github.com>:
