### ISSUE TITLE
Crashes in object loader

### ISSUE THREAD

**Issue by mcarpenter** [ohler55/ox#218]
Hello,

I'm back from another round of fuzzing my favorite XML parser :)

I just found one problem (although 4 distinct crashes) in `Ox.load` using `:object` mode. I imagine that parsing untrusted input in this mode is already a Bad Idea so I don't think this is a security issue. However, in the interests of robustness... I tested using Ruby 2.3.3, 2.4.0 and 2.5.1, and Ox 2.9.3, x86_64 Linux. Output below is from MRI 2.3.3.

Hopefully the crashes should be fairly simple to reproduce, by pasting the input below into a file:

```ruby
ruby -r ox -e 'Ox.load(STDIN.read, mode: :object)' < ./input
```

### Sample 1
Input

    <><u =""><0><000000></000000>

Crashed at

    747         rb_struct_aset(ph->obj, h->var, h->obj);

Backtrace

    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(end_element+0x240) [0x7f66f9073330] obj_load.c:747
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0x120) [0x7f66f907ea30] parse.c:673
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f66f907f5a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f66f907f5a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f66f907f5a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(ox_parse+0x1a4) [0x7f66f907fca4] parse.c:186
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(load_str+0x301) [0x7f66f9079a51] ox.c:841

### Sample 2
Input

    <><e =""><0><0e0000></0e0000>

Crashed at

    742             rb_ivar_set(ph->obj, h->var, h->obj);

Backtrace

    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(end_element+0x36a) [0x7f014433045a] obj_load.c:742
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0x120) [0x7f014433ba30] parse.c:673
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f014433c5a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f014433c5a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f014433c5a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(ox_parse+0x1a4) [0x7f014433cca4] parse.c:186
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(load_str+0x301) [0x7f0144336a51] ox.c:841

### Sample 3
Input

    <0 =""><k =""><0><000000></000000>

Crashed at

    783             rb_hash_aset(gh->obj, ph->obj, h->obj);

Backtrace

    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(end_element+0x2b5) [0x7fbcfa5e53a5] obj_load.c:783
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0x120) [0x7fbcfa5f0a30] parse.c:673
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7fbcfa5f15a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7fbcfa5f15a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7fbcfa5f15a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(ox_parse+0x1a4) [0x7fbcfa5f1ca4] parse.c:186
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(load_str+0x301) [0x7fbcfa5eba51] ox.c:841

### Sample 4
Input

    <l><s/><0/>

Crashed at

    806             ph->obj = rb_rational_new(ph->obj, h->obj);

Backtrace

    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(end_element+0x25e) [0x7f27ac87c34e] obj_load.c:806
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0x120) [0x7f27ac887a30] parse.c:673
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(read_element+0xc94) [0x7f27ac8885a4] parse.c:644
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(ox_parse+0x1a4) [0x7f27ac888ca4] parse.c:186
    /home/mcarpenter/.rvm/gems/ruby-2.3.3/gems/ox-2.9.3/ext/ox/ox.so(load_str+0x301) [0x7f27ac882a51] ox.c:841

**Comment by ohler55** [comment]
I'll take a look and get it fixed.

**Comment by mcarpenter** [comment]
Thanks, this looks good.

If you aren't in any hurry to release I'd be happy to give this version another 48 hours of fuzzing (and I'll report back here when that's done).

**Comment by mcarpenter** [comment]
I've found another one, somewhat heisenbug-ish. The test case is pretty simple, although contains some binary (line feed, carriage return). I've attached it (zipped), and ASCII `xxd` dump is below:

[ox001:000097.gz](https://github.com/ohler55/ox/files/2181378/ox001.000097.gz)

```
vagrant@ubuntu-bionic:~/ox/crashes$ xxd ox001:000097 
00000000: 3c0d 782f 3e0a 2020 3c0d 753e 0a20 203c  <.x/>.  <.u>.  <
00000010: 0d78 2f3e 0a3c 3c                        .x/>.<<
vagrant@ubuntu-bionic:~/ox/crashes$ md5sum ox001:000097 
3120e84e51f8c294d945de791af88ed0  ox001:000097
```

This is the test script:

```ruby
#!/usr/bin/env ruby
require 'ox'
input = STDIN.read
begin
  Ox.parse(input)
rescue Ox::ParseError
end
[:generic, :object, :limited, :hash, :hash_no_attrs].each do |mode|
  puts mode
  begin
    Ox.load(input, mode: mode)
  rescue Ox::ParseError#, EncodingError
  end
end
```
When I run this:
```
vagrant@ubuntu-bionic:~/ox/crashes$ ../foo.rb < ox001:000097
generic
object
../foo.rb:11: [BUG] Segmentation fault at 0x000000000000003c
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
...
```
So this is again in `object` mode. The strange thing is if I remove any of the previous `#parse` or `#load` calls from the script then the crash doesn't happen. I have other cases where the crash occurs in other modes but (again) I need to do some other parse/load attempts before the crash appears.

So it seems, my best guess, something is corrupting state somewhere in the parser in one of those earlier calls.

The top of the stack trace:
```
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(rb_vm_bugreport+0x769) [0x7f6bd281b419]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(0xaae54) [0x7f6bd268ce54]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(0x1a86e2) [0x7f6bd278a6e2]
/lib/x86_64-linux-gnu/libc.so.6(0x7f6bd222ff20) [0x7f6bd222ff20]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(0x215882) [0x7f6bd27f7882]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(0x222c98) [0x7f6bd2804c98]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(rb_to_int+0x16f) [0x7f6bd27053ff]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(rb_num2long+0x55) [0x7f6bd26fb315]
/usr/local/rvm/rubies/ruby-2.5.1/lib/libruby.so.2.5(rb_struct_aset+0xf8) [0x7f6bd27bb178]
/home/vagrant/ox/ext/ox/ox.so(end_element+0x7d0) [0x7f6bd0c0fbb0]
/home/vagrant/ox/ext/ox/ox.so(0x73515) [0x7f6bd0c36515]
/home/vagrant/ox/ext/ox/ox.so(0x75c9d) [0x7f6bd0c38c9d]
/home/vagrant/ox/ext/ox/ox.so(ox_parse+0x5c6) [0x7f6bd0c3ab56]
/home/vagrant/ox/ext/ox/ox.so(0x6384f) [0x7f6bd0c2684f]
```

I suspect you won't be able to reproduce this. If you have a similar environment I can send you a core? Or anything else that you think might help?

**Comment by ohler55** [comment]
I'll take a look tonight.

**Comment by mcarpenter** [comment]
Thanks. Just shout if I can help... though I'm UTC+2 and only free in my evenings so there might be a bit of a delay.

**Comment by ohler55** [comment]
Ok, ready for another shot.

**Comment by mcarpenter** [comment]
Good stuff: 169 fixed, 9 to go. (And if we're lucky, the 9 remaining may have the same cause, I haven't triaged further).

[remaining.tar.gz](https://github.com/ohler55/ox/files/2185963/remaining.tar.gz)

**Comment by ohler55** [comment]
I'll wait to see what the remaining are then.

**Comment by mcarpenter** [comment]
Sorry, maybe that wasn't clear: the remaining 9 crashing test cases were attached just above ^

**Comment by ohler55** [comment]
All passed for me or rather raised an exception and did not not crash.

**Comment by mcarpenter** [comment]
Huh. I checked my setup and re-tested, all 9 throw SIGSEGV in the object mode parser, either using the little script above or the one-liner right at the top.

What exception are you seeing? If you are using the script and getting eg `EncodingError` in the `#each` loop before reaching `:object` (perhaps because of environmental differences) then that could explain it.

**Comment by ohler55** [comment]
I'll check tonight.

**Comment by ohler55** [comment]
Ok, my error on the tests. Fixed now.

**Comment by mcarpenter** [comment]
Looks good! Thanks Peter.
