### ISSUE TITLE
Feature Request: Accessing all current context's children through locate

### ISSUE THREAD

**Issue by hiphip90** [ohler55/ox#223]
Hey! Firstly, thanks a lot for this gem, really helped me shave a lot of overhead off the heavily loaded SOAP API proxy I'm maintaining.

I was wondering if there's a way to invoke the same behavior as in `Element#nodes`, using some `Element#locate` pattern? When using locate everywhere else it's nice to be able to keep parsing code consistent in how it accesses nodes.

**Comment by ohler55** [comment]
Have your tried `my_element.locate('*')`?

**Comment by hiphip90** [comment]
I did, it seems to return current context (node) wrapped in array. What I described is a pattern that would return all direct children nodes of current context.

**Comment by ohler55** [comment]
Okay, how about this:

```ruby
require 'ox'

xml = %{<?xml?>
<top>
  <one>1</one>
  <two>2</two>
  <three>3</three>
</top>
}

doc = Ox.load(xml)

top = doc.root
puts "top: #{Ox.dump(top)}"

top.locate('?').each { |node|
  puts Ox.dump(node)
}
```
which results in:
```xml
top: 
<top>
  <one>1</one>
  <two>2</two>
  <three>3</three>
</top>

<one>1</one>

<two>2</two>

<three>3</three>
```

**Comment by hiphip90** [comment]
Yes, that does it!

Thanks a lot, and sorry for bothering
