### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ohler55/ox#224]
I would like to point out that identifiers like “[`_CheckPt`](https://github.com/ohler55/ox/blob/228f92089f309fdf37694133d2395257189bfad8/ext/ox/sax_buf.h#L32 "Update candidate")” and “[`__OX_H__`](https://github.com/ohler55/ox/blob/f060f84b5cadcff209de4a517e6289d1a39fe87d/ext/ox/ox.h#L6 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ohler55** [comment]
Fixed.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/ohler55/ox/commit/f5b618285a0b9c885aa86dd9d51188fce2d60856 "Renaming of some identifiers").
