### ISSUE TITLE
Native binary should be copied to lib/ox/ox.*

### ISSUE THREAD

**Issue by peter-ellis** [ohler55/ox#225]
Just a minor thing I noticed: after getting built, the native binary (ox.bundle or ox.so) gets copied to the lib directory, e.g., lib/ox.bundle. However, the last line of ox.rb loads the binary with this: `require 'ox/ox'`. The effect is that Ox is actually loading the binary from the ext directory, not the lib directory. I ran into a confusing problem because I was packaging up the gem for a cross-platform thing and deleted the ext directory--and suddenly Ox stopped working. I think it's an easy fix to just copy the binary to lib/ox/ox.bundle instead of lib/ox.bundle.

Added bonus if you do that, it would no longer be necessary to include ext in the require_paths in your gemspec. Currently, it does this: `s.require_paths = ["lib", "ext"]`

Thanks for a great gem!

**Comment by ohler55** [comment]
I'll look into how to generate the desired Makefile. Right now I leave it up to Ruby to do what it wants.

As for the require paths, both are needed to build the gem. No way to change those.

**Comment by ohler55** [comment]
I have not been able to figure out the incantations that will get the Ruby mkmf to generate a Makefile that will copy the `.so` or `.bundle` to the `lib` directory. If you know how to do that please let me know.

**Comment by ohler55** [comment]
DO you know how to modify the `extconf.rb` so the Makefile gets generated the way you suggest?

**Comment by peter-ellis** [comment]
No, I'm sorry, unfortunately I don't know anything about how to build native binaries for gems.

**Comment by ohler55** [comment]
Sine this is not supported by the Ruby make facility and is not consistent with the Ruby make environment it is being closed,
