### ISSUE TITLE
Add support for files bigger than 2 GB

### ISSUE THREAD

**Issue by synek317** [ohler55/ox#229]
SAX parser currently uses `int` type for position. It should be `unsigned long long` to handle files over 2 GB.

**Comment by ohler55** [comment]
I suppose that is true for a 32 bit system or at least a `long` since that is what `ftell` returns.

**Comment by synek317** [comment]
`long` is unfortunately only guaranteed to be 'at least 32 bits'. I'm using Ubuntu 18.04 64 bits

**Comment by ohler55** [comment]
The best I could do is use `off_t` and switch to the `ftello`. That still does not cover some architecture that are truely 32 bit but sinc enone of the file calls are 64 bit in that case it really a mute point.

**Comment by synek317** [comment]
Have you confirmed that it works well?
I've tried to do so locally but without success.

Anyway, I've never worked before with ruby native extensions so maybe my changes were not applied at all?

**Comment by ohler55** [comment]
I don't have a 32 bit OS installed on any of my machines so I can not verify that there is a limit on those. On any 64 bit system there is not problem as an `int` is 64 bit.

**Comment by ohler55** [comment]
Any reason this should be left open?

**Comment by synek317** [comment]
I'm 99,99% sure that it does not work well and 99,99% sure that `int` instead of `unsigned long long` is the root cause - even on 64-bit machines, at least some of them.

Anyway, because of that bug I've switched to a different solution. I use ruby only occasionally and I'm total noob when it comes to native extensions, so I cannot really help here.

**Comment by ohler55** [comment]
I changed the `int` in the sax parser to `off_t` so that compiling with `-D_FILE_OFFSET_BITS=64` should give access to larger files.

**Comment by ohler55** [comment]
No additional response and not much that can be done with further feedback.
