### ISSUE TITLE
How to print xml version/doctype?

### ISSUE THREAD

**Issue by 9mm** [ohler55/ox#232]
I'm trying to use `dump()` to create an XML string which matches what an API expects. I need to format stuff in this way...

I can't figure out how to do this though

```
<?xml version='1.0'?>
<!DOCTYPE Request.dtd>
<XMLRequest>
  ...
 </XMLTrans>
</XMLRequest>
```

**Comment by 9mm** [comment]
I found `with_xml` and `with_dtd` and also this, this kind of wroks:

      doc = Ox::Document.new(version: '1.0')
      doc << Ox::DocType.new('"Request.dtd"')
      request = Ox::Element.new('XMLRequest')
      ...
      request << trans
      doc << request
      Ox.dump(doc)

This appears to work but I have no idea if the DocType line is right, it seems like its not right because I had to manually add `"` (I looked at other examples online and that appears ot be valid with double quotes). Its also putting a space before the > for some reason, which doesnt affect parsing but bothers my ocd

    <?xml version="1.0"?>\n<!DOCTYPE "Request.dtd" >

**Comment by 9mm** [comment]
Actually the API fails if I put double quotes around `Request.dtd`, is there a way I can get rid of the space then?

**Comment by ohler55** [comment]
Looks like you got most of it figured out.

The space is hard coded but I would be okay with changing it.

**Comment by 9mm** [comment]
Awesome, is that something you would be able to do next time you update it? I looked around for what file to edit + submit but I am not sure

**Comment by ohler55** [comment]
I'll do it tonight/

**Comment by 9mm** [comment]
Thanks man! I really appreciate that, I know it's so insignificant and you have way better things to be doing but thanks for helping an brother who hates trailing spaces 👌🏼

As a sidenote, because I don't want to waste an issue on this, is there a more easy way to build an XML rather than the "create variable and << to it" method.

I was thinking something like this which seems really clean, but `<<` doesnt support `[]`. I've tried quite a few different ways to make it cleaner including doing things like

    E << (E << 'xyz')

... type of deal but it's still pretty messy

Here was my idea: 

      doc = Ox::Document.new(version: '1.0') << [
        Ox::DocType.new('Request.dtd'),
        Ox::Element.new('XMLRequest') << [
          Ox::Element.new('cert') << 'cert',
          Ox::Element.new('termid') << 'term',
          Ox::Element.new('XMLTrans') << [
            Ox::Element.new('XMLTrans') << [
              Ox::Element.new('transType') << trans_type
            ]
          ]
        ]
      ]

**Comment by ohler55** [comment]
Take a look at `Ox::Builder`. There are some unit tests that show how to use it.

**Comment by 9mm** [comment]
That is amazing, it works perfectly 🙏🏼 Funny enough theres also not a space on that one, haha

**Comment by ohler55** [comment]
Released!

**Comment by 9mm** [comment]
Awesome!!
