### ISSUE TITLE
Building a large xml

### ISSUE THREAD

**Issue by drougojrom** [ohler55/ox#235]
Currently I'n trying to build a really large xml file (more than 200.000 lines) and I'm getting an error after I call  ```Ox.dump(doc)``` with SystemStackError: maximum depth exceeded.

If the file is smaller (140.000 lines) it's all good though.

Could you help me with that issue?

**Comment by ohler55** [comment]
Is the file deeply nested or relatively flat? 140K lines is not that large.

**Comment by drougojrom** [comment]
the structure looks like that
```
<yml_catalog>
  <field1></field1>
  <field1></field1>
  <array1></array1>
  <array2>
     <obj1>
       <array3>
           <obj2>
        </array3>
      </obj1>
   </array2>
</yml_catalog>
```

**Comment by ohler55** [comment]
By loops I meant object that refer to each other.

**Comment by drougojrom** [comment]
> By loops I meant object that refer to each other.

Probably, at least I think so.

I have the main object, which is doc, and then I populate this object with my first array. 
Then I create a second array and populate this one with newly created objects for the second array. Each of those objects for the second array may have another array with other objects.

After I finish with each of those, I push it back to the previous layer. So to say, objects from third array go to the third array, then it goes into previous object (obj1 on scheme) and then that object goes into second array.

**Comment by ohler55** [comment]
Try setting the `:circular` to true and see if that fixes the issue. If you do indeed have objects referring back to themselves that would cause and endless loop.

**Comment by drougojrom** [comment]
if ```:circular``` should be a parameter for dump, then it didn't help

well, but it works with smaller files now

**Comment by ohler55** [comment]
I thought it already worked with files less than 140k lines, no?

**Comment by ohler55** [comment]
Any chance you can share some sample code that demonstrates the issue?

**Comment by drougojrom** [comment]
yeah, I meant that adding that parameter didn't change anything

sure

main method looks like this:

```
  def call
    doc = Ox::Document.new(version: '1.0', encoding: 'UTF-8', with_xml: true)
    yml_catalog = Ox::Element.new('date')
    yml_catalog[:yml_catalog] = get_time
    doc << yml_catalog
    product = Ox::Element.new('product')
    yml_catalog << shop

    header.each { |obj| shop << obj }
    product << currencies
    ...
    product << categories
    product << delivery_options
    product << get_items(units)

    Ox.dump(doc, circular: true)
  end
```

then the items method, which is pretty large, looks like this:

```
  def get_items(units)
    xml_items = Ox::Element.new('items')
    without_sku = get_sku
    cat_ids = generate_cat_ids

    store_ids = Store.where(city_id: city_id, hidden:false).map(&:id)
    (Item.joins(:categories).where(
      categories: {id: cat_ids},
      items: {
                 hidden:  false, pr: false, cached_price: price }).
                 where('items.sku not in (?)', without_sku).
                 order('items.id ASC')).each_with_index do |item, index|

      category = item.categories.unhidden.order('categories.id ASC').first

      general_units = unit(item, store_ids)

      if category.present? && descr && category.path.map(&:hidden).include?(true) == false
        puts "Item ##{index} done."
        if category.path.include?(Category.find_by_cached_path('books'))
          item.authors.first(1).each do |author|
            author = Ox::Element.new('author')
            author.nodes << author.title.strip.gsub("'", "&apos;").gsub("\t", " ").gsub("<", "&lt;").gsub(">", "&gt;").gsub('"', "&quot;")
            general_units << author
        elsif
         # for other types of categories it looks pretty much the same
          ......
          end
       end
    end
  end
end
```

and the unit method looks like this:

```
def unit(item, store_ids)
    xml_unit = Ox::Element.new('unit')
    xml_unit[:id] = item.sku_for_feed
    xml_unit[:available] = 'true'
    xml_unit[:type] = 'some_unit'

    xml_unit_url = Ox::Element.new('url')
    xml_unit_url.nodes << (item_url(item) + offer_url)
    xml_unit << xml_unit_url

  if item.description.present?
      description_xml = Ox::Element.new('description')
      description_xml.nodes << "#{truncate(strip_tags(item.description.gsub('</p><p>',' '))
              .gsub("'", "&apos;").gsub("\t", " ").gsub("<", "&lt;")
              .gsub(">", "&gt;").gsub('"', "&quot;").gsub("\n", " "),
      :escape => false, :separator => ' ', :length => 3000)}"
      xml_unit << description_xml
    end
end
```

**Comment by ohler55** [comment]
That all makes sense. I suspect you are just running out of memory since all the objects are held in memory until dump is called. Have you looked at the Ox::Builder? The Ox::Builder.file() method will create a builder that write to a file as you add parts to the XML. Should be very easy on the memory use.

**Comment by drougojrom** [comment]
no, I didn't see that builder. 
Where can I take a look on an example with that one?

**Comment by ohler55** [comment]
In the `test/tests.rb` file. Search for builder or just go to line 1408.

**Comment by drougojrom** [comment]
thank you so much!
with builder it works perfectly :)
