### ISSUE TITLE
Supporting multiple root elements

### ISSUE THREAD

**Issue by brendon** [ohler55/ox#236]
Hi @ohler55, I was wondering of `ox` supports consuming 'html' with multiple root elements? I'm trying to create a cut down version of a Vue-component consumer and a component looks like this:

```
<template>
  <div>Hello there!</div>
</template>

<style>
  div, span {
    color: blue;
    font-weight: bold;
    font-size: 3em;
  }
</style>
```

Unfortunately when I parse this with `ox` I only get the second part when I dump it back out. I suspect this is because multiple root nodes isn't allowed? I guess the workaround is to wrap it all in a `<component></component>` tag, but just wanted to check if there was another way.

**Comment by ohler55** [comment]
Ox was implemented to parse XML and with the proper options HTML. It is not meant to parse multiple separate XML or HTML segments. But...

The Ox SAX parser should handle it okay. It is a different approach though so if that doesn't work and you can modify the document then wrapping it with any valid element like `div` or `component` should work.

**Comment by brendon** [comment]
Thanks @ohler55 :) I found that if I wrapped the string with an element as you say, it parsed nicely. Unfortunately I have to abandon my attempt because I needed to query the document using full fledged CSS selectors (from a CSS file) :(
