### ISSUE TITLE
Non self-closed tags

### ISSUE THREAD

**Issue by tuwukee** [ohler55/ox#238]
Hi @ohler55 ,
`Ox.dump` method generates self-closed tags f.e.
```
irb(main):017:0> puts Ox.dump(data)

<outer>
  <empty/>
</oter>
=> nil
```
Is it possible to force it to generate the full form?
```
<outer>
  <empty></empty>
</oter>
```
Basically, I'm looking for the `Ox` equivalent of `Nokogiri::XML::Node::SaveOptions::NO_EMPTY_TAGS` setting.

**Comment by ohler55** [comment]
Let me look into that and see what is the best approach to handle that.

**Comment by ohler55** [comment]
Checkout the `no_empty` branch and see if that is what you looking for.

```ruby
puts Ox.dump({}, no_empty: true)
> <h></h>
puts Ox.dump(Ox::Element.new('empty'), no_empty: true)
> <empty></empty>
```

**Comment by tuwukee** [comment]
Hey, that's exactly what I was looking for.
Thank you!

**Comment by ohler55** [comment]
Great. I'll merge but not release yet. One more change before the release.

**Comment by ohler55** [comment]
Released
