### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by smithtim** [ohler55/ox#241]
When parsing and dumping HTML, Ox recognizes some entities (like `&lt;`):

```ruby
x = Ox.parse '<html>foo &lt; bar</html>'
 # => #<Ox::Element:0x00007fd0c88473a8 @value="html", @nodes=["foo < bar"]>
Ox.dump x
 # => "\n<html>foo &lt; bar</html>\n"
```

but not others (like `&sect;`):

```ruby
x = Ox.parse '<html>foo &sect; bar</html>'
 # => #<Ox::Element:0x00007fd0c98e5a70 @value="html", @nodes=["foo &sect; bar"]>
Ox.dump x
 # => "\n<html>foo &amp;sect; bar</html>\n"
```

Is there a way to get Ox to recognize all HTML entities?  The dumped HTML is incorrect otherwise.

**Comment by ohler55** [comment]
Just pushed a `develop` branch with support for all HTML 4 entity sequences. It is no efficient yet but it will allow you to try out the feature.

**Comment by ohler55** [comment]
Hash added.

**Comment by smithtim** [comment]
Thanks!  But it's not working for me.  I'm getting the same output as before:

```ruby
Ox::VERSION
 # => "2.13.0"
x = Ox.parse '<html>foo &sect; bar</html>'
 # => #<Ox::Element:0x00007fc29b8718c8 @value="html", @nodes=["foo &sect; bar"]>
Ox.dump x
 # => "\n<html>foo &amp;sect; bar</html>\n"

**Comment by ohler55** [comment]
What options are you using? Make sure `:convert_special` is set to true.

**Comment by smithtim** [comment]
Hmm, that didn't work either:

```ruby
Ox::VERSION
 #  => "2.13.0"
Ox.default_options = {convert_special: true}
 # => {:convert_special=>true}
x = Ox.parse '<html>foo &sect; bar</html>'
 # => #<Ox::Element:0x00007ff25b8901c0 @value="html", @nodes=["foo &sect; bar"]>
Ox.dump x
 # => "\n<html>foo &amp;sect; bar</html>\n"
```

Do you get different output?

**Comment by ohler55** [comment]
I see what I did wrong. The attributes are handled, the text is not. I'll get that fixed too. Sorry about that.

**Comment by ohler55** [comment]
Okay, fixed (I hope) in the develop branch again.

**Comment by smithtim** [comment]
That worked, thanks!

**Comment by smithtim** [comment]
Oops, this broke `&apos;`.

It is the only one of the five predefined entities in XML that is not in HTML 4.  (It is in HTML 5.)

```ruby
Ox::VERSION
 # => "2.13.1"
x = Ox.parse '<html>foo &apos; bar</html>'
 # => #<Ox::Element:0x00007fae1f8be1b8 @value="html", @nodes=["foo &apos; bar"]>
Ox.dump x
 # => "\n<html>foo &amp;apos; bar</html>\n"
```

**Comment by ohler55** [comment]
Please try out the current develop branch. Just pushed a fix.

**Comment by smithtim** [comment]
Did you push it to `develop`?  I don't see any commits since January 30.

**Comment by ohler55** [comment]
Maybe something failed. I just moved over the weekend and internet in the bar is spotty. Pushed again.

**Comment by smithtim** [comment]
It's fixed, thanks!

**Comment by ohler55** [comment]
Release 2.13.2
