### ISSUE TITLE
Missing YARD docs for Ox#to_file and #to_xml

### ISSUE THREAD

**Issue by tanius** [ohler55/ox#245]
I was just looking how to use the `Ox#to_file` class method, but it's not documented in the generated YARD documentation ([see](http://www.ohler.com/ox/Ox.html#to_file-class_method)).

However, I found the documentation of the equivalent C method in [`ext/ox/ox.c` l. 1336](https://github.com/ohler55/ox/blob/develop/ext/ox/ox.c#L1336).

I am not sure how the documentation generation works here – maybe there is some custom YARD extension that takes over native method documentation into the documentation of the equivalent Ruby method? Anyway, there seems to be a hiccup so that the documentation is missing in the final output :)

The same also applies to [`Ox#to_xml` in the YARD docs](http://www.ohler.com/ox/Ox.html#to_xml-class_method).

**Comment by ohler55** [comment]
Maybe it's time to switch to rdoc. I'll look into it.

**Comment by ohler55** [comment]
I have no solution for yardoc but if you use rdoc you will see both.

**Comment by tanius** [comment]
Thank you!

(Also, you now hold the global record for the fastest fix to an issue I reported. :zap: )

**Comment by ohler55** [comment]
I try to stay on top of things. 😄
