### ISSUE TITLE
Using have_func/have_macro instead of hardcoding Ruby implementation names and versions

### ISSUE THREAD

**Issue by eregon** [ohler55/ox#246]
From https://github.com/oracle/truffleruby/issues/1591

The extconf.rb contains hardcoded checks which are brittle, and therefore return an incorrect result on any implementation not explicitly thought of:
https://github.com/ohler55/ox/blob/0db3f9c947e390cee2400f7b965dc4113d4ac97a/ext/ox/extconf.rb#L14-L40

I think these can all use mkmf's `have_func`/`have_macro`/etc which would be the correct and reliable way to check for those.

This prevents running Ox on TruffleRuby and potentially other Ruby implementations.

**Comment by ohler55** [comment]
Fixed in 2.13.3

**Comment by eregon** [comment]
Thank you!
