### ISSUE TITLE
parser fails on certain unicode characters

### ISSUE THREAD

**Issue by kp666** [ohler55/ox#250]
parser fails when there is a Unicode character like End of Text

This works: https://gist.github.com/kp666/cb194a6ff7b2f5a20280fe76abf435b8
This fails: https://gist.github.com/kp666/6b2ac64c7674127b1ea8143854882aab

**Comment by ohler55** [comment]
I'll take a look.

**Comment by ohler55** [comment]
I checked the XML specification to make sure and it still describes the character `\u0003` as not a valid character in an XML document. I believe Ox is reporting correctly that `\u0003` is not a valid character.

**Comment by kp666** [comment]
Thanks for the update

**Comment by ohler55** [comment]
Has this been answered to your satisfaction?
