### ISSUE TITLE
Parsing of double space (`u20`)

### ISSUE THREAD

**Issue by leesio** [ohler55/ox#251]
Hi there,
I think I've found some unusual behaviour in the library and I'm interested to understand whether I've found a weird edge case/bug, or whether I'm using the library incorrectly somehow.

It seems like `Ox` replaces multiple consecutive space characters (unicode20) with a single instance.

This is demonstrable with the following simple example:
```
require 'ox'

t = <<-EOF
<?xml version="1.0" encoding="UTF-8"?>
  <Message><Data>This  is a test message</Data></Message>
EOF

puts Ox.parse(t).Message.Data.text
```
This outputs:
```
This is a test message
```

Note that the double space in the XML payload is replaced by a single space in the parsed object.

Parsing the same example using Go's `encoding/xml` library yields what I believe to be the correct result

```
package main

import (
	"encoding/xml"
	"fmt"
)

type Message struct {
	XMLName xml.Name `xml:"Message"`
	Data    string   `xml:"Data"`
}

var example = []byte(`<?xml version="1.0" encoding="UTF-8"?>
    <Message><Data>This  is a test message</Data></Message>
`)

func main() {
	var m Message
	err := xml.Unmarshal(example, &m)
	if err != nil {
		panic(err)
	}
	fmt.Println(m.Data)
}
```

```
This  is a test message
```

Any help understanding this behaviour would be appreciated 😄 

Thanks for your work on the library!

**Comment by ohler55** [comment]
Over the years I have found that different developers have different ideas about how text is parsed in XML. Most prefer the HTML approach that collapses spaces and new lines but some  others feel just new lines should be ignored. There is a third camp that feel the text should be returned exactly like it appears in the file. Ox support all three of those approach with the `:skip` option. Set the `:skip` option to `:skip_none` and you will get the text back unchanged.

As a side note; while Go is becoming popular it is not the gold standard. Defining the correct behaviour as what the Go XML encoding package does is not really a valid assertion.

**Comment by ohler55** [comment]
My apologies if that aside came over as too strong. It was not intended to be unfriendly.

**Comment by leesio** [comment]
Ahh this seems to be exactly what I was looking for, thanks!

> My apologies if that aside came over as too strong. It was not intended to be unfriendly.

No problem. I should have been clearer that the Go example gave the result *I wanted* not the "correct" result, since both are correct.

Thanks again for your assistance. I'm not sure how I missed the `:skip` option.
