### ISSUE TITLE
Locate multiple paths at once

### ISSUE THREAD

**Issue by echan00** [ohler55/ox#252]
Is it possible to locate multiple paths?  I want to do something like the following: 

`xml.locate('*/w:p, */w:t')`

**Comment by ohler55** [comment]
The locate method is a simplified XML Path, very simplified. As such I don't want to make the path parser portion any more complex that is current is. It is easy enough to call the method twice and merge the results. If you would like to submit a PR for having the locate method take multiple arguments I would consider that enhancement. It could do the same as what you are asking for but not add any complexity to the path parser.
