### ISSUE TITLE
Ox ignores CData when converting XML to hash?

### ISSUE THREAD

**Issue by emilebosch** [ohler55/ox#253]
Hi thanks for making ox! Its super fast and im currently implementing it.
However I a wondering whether I'm missing something:

```xml
<Lol>
  <Data>
    <![CDATA[Some data ]]>
  </Data>
</Lol>
```

Add the logic:
```ruby
p Ox.load_file "test.xml", mode: :hash, symbolize_keys: false
{"Lol"=>{"Data"=>nil}}
```

I would expect the data to contain the CDATA much like Nokogiri. Is there a setting I miss?

**Comment by emilebosch** [comment]
Solved it by making my own OX:Element to JSON converter!

**Comment by GMolini** [comment]
Would you mind sharing it? Id like to have that too
