### ISSUE TITLE
Install on jruby 2.5.7 error

### ISSUE THREAD

**Issue by pouracc** [ohler55/ox#254]
Hi,

I installl ox gem on jruby 2.5.7 and got error:

NoMeThodError: undefined method slice! for nil:NilClass at extconf.rb

Please help to resolve, thanks!

**Comment by ohler55** [comment]
jruby has not supported C extensions for many years. The current version of ruby is 9.2.13. There was never a 2.5.7 release of jruby as noted on https://www.jruby.org/files/downloads/index.html.

**Comment by pouracc** [comment]
Thank you!
