### ISSUE TITLE
Ox ignores CData when converting XML to hash

### ISSUE THREAD

**Issue by GMolini** [ohler55/ox#256]
This is the same as issue #253 , which the author closed as he found a solution. Still, the issue is there and Im not sure why it happens (and what I could do to solve it)

**Comment by ohler55** [comment]
I'll take a look. Might be next week though.

**Comment by GMolini** [comment]
Thanks! Whenever you find the time :)

**Comment by GMolini** [comment]
Ok, so I think I found what the problem is.

In the file hash_load.c there is no function add_cdata. and _parseCallbacks is defined as: 

```
struct _parseCallbacks   _ox_hash_callbacks = {
    NULL,
    NULL,
    NULL,
    NULL,
    add_text,
    add_element,
    end_element,
    finish,
};
```

That causes the check in line 901 of parse.c 
```
    if (0 != pi->pcb->add_cdata) {
	pi->pcb->add_cdata(pi, start, end - start);
    }
```

to fail, skipping adding the data. I tried just adding a function add_cdata to hash_load.c that is just a copy of the add_text function

```
static void
add_cdata(PInfo pi, const char *cdata, size_t len) {
    Helper		parent = helper_stack_peek(&pi->helpers);

    volatile VALUE       s = rb_str_new2(cdata);
		volatile VALUE	a;

#if HAVE_RB_ENC_ASSOCIATE
    if (0 != pi->options->rb_enc) {
        rb_enc_associate(s, pi->options->rb_enc);
    }
#endif

    switch (parent->type) {
    case NoCode:
	parent->obj = s;
	parent->type = StringCode;
	break;
    case ArrayCode:
	rb_ary_push(parent->obj, s);
	break;
    default:
	a = rb_ary_new();
	rb_ary_push(a, parent->obj);
	rb_ary_push(a, s);
	parent->obj = a;
	parent->type = ArrayCode;
	break;
    }
}
```

and adding it to the struct
```
struct _parseCallbacks   _ox_hash_callbacks = {
    NULL,
    NULL,
    NULL,
    add_cdata,
    add_text,
    add_element,
    end_element,
    finish,
};
```

And now it seems to work. The following xml
```
<Lol>
  <Data>
    <![CDATA[MYTERM]]>
  </Data>
  <Data>
    <![CDATA[MYTERM2]]>
  </Data>
  <Data>
    <![CDATA[MYTERM3]]>
  </Data>
</Lol>
```

Produces the following output
```
{"Lol"=>{"Data"=>["MYTERM", "MYTERM2", "MYTERM3"]}}
```

**Comment by ohler55** [comment]
It took me longer than expected to get to this. I was trying to remember why there was no data handler. I think my reasoning at the time was that CDATA is usually used for raw data so was not suitable for a simple hash. I can see the desire for it though. I wonder if an option might be a better approach. Do you have any thoughts on that?

**Comment by GMolini** [comment]
Sure, an option would work fine. Although maybe I would argue that to me the default makes more sense if it parses everything, then lets the user discard as fit for his application, so the option would be to discard raw data if unneeded. But either way would work for me.

**Comment by ohler55** [comment]
I'll add an option. I'm hesitant to change the default as it might break existing users.

**Comment by ohler55** [comment]
Pushed a branch named hash-load-cdata. It has the new :with_cdata option. I have not tested it yet but will add unit tests tomorrow.

**Comment by ohler55** [comment]
with unit test now. I'll release as soon as you give it a thumbs up.

**Comment by GMolini** [comment]
Seems to work fine :+1:

**Comment by GMolini** [comment]
Maybe I would suggest adding it to the readme too

**Comment by ohler55** [comment]
The readme is supposed to be a quick intro and not full documentation. The option was added to the documentation and also to the change log. I think that should be enough. No?

**Comment by GMolini** [comment]
ah, sure, adding it in the documentation would be enough, of course

**Comment by ohler55** [comment]
Released, ready for a close.
