### ISSUE TITLE
Missing new lines in tags bodies

### ISSUE THREAD

**Issue by v-kolesnikov** [ohler55/ox#261]
Parsing XML documents with Ox raises an issue with tags that have multi-line values, e.g. `<div>The first line\nThe second line</div>`.

Here is a self-completed script that demonstrates the issue:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'ox'
  gem 'nokogiri'
  gem 'power_p'
end

input = %Q{The first line\nThe second line}
xml = "<div>#{input}</div>"

p { Nokogiri.XML(xml).text == input }
p { Ox.load(xml).nodes[0] == input }
```

```
p { Nokogiri.XML(xml).text == input }
    |        |   |    |    |  |
    |        |   |    |    |  "The first line\nThe second line"
    |        |   |    |    true
    |        |   |    "The first line\nThe second line"
    |        |   "<div>The first line\nThe second line</div>"
    |        #<Nokogiri::XML::Document:0x438 name="document" children=[#<Nokogiri::XML::Element:0x424 name="div" children=[#<Nokogiri::XML::Text:0x410 "The first line\nThe second line">]>]>
    Nokogiri
p { Ox.load(xml).nodes[0] == input }
    |  |    |    |    |   |  |
    |  |    |    |    |   |  "The first line\nThe second line"
    |  |    |    |    |   false
    |  |    |    |    "The first line The second line"
    |  |    |    ["The first line The second line"]
    |  |    "<div>The first line\nThe second line</div>"
    |  #<Ox::Element:0x00007fd5198be8e0 @value="div", @nodes=["The first line The second line"]>
    Ox
```

**Comment by ohler55** [comment]
Many people prefer the behaviour of collapsing white space into a single character. I think you will find every browser does exactly that. Ox does support several different options for collapsing or skipping white space. You can read about those options in the Ox documentation http://www.ohler.com/ox/Ox.html#method-c-default_options. If you are looking to turn any skipping or collapsing then set the `:skip` option to `:skip_off`.

I'm not sure why you wanted to compare the Ox behaviour to Nokogiri. Ox does not attempt to mimic Nokogiri and makes no claim to behave the same as Nokogiri.

**Comment by v-kolesnikov** [comment]
> You can read about those options in the Ox documentation http://www.ohler.com/ox/Ox.html#method-c-default_options. If you are looking to turn any skipping or collapsing then set the `:skip` option to `:skip_off`.

It is exactly what I need! Thanks a lot!

> I'm not sure why you wanted to compare the Ox behaviour to Nokogiri. Ox does not attempt to mimic Nokogiri and makes no claim to behave the same as Nokogiri.

I've migrated from Nokogiri to Ox and then found this different behaviour of two gems.
