### ISSUE TITLE
Encoding is broken in v2.14.3.

### ISSUE THREAD

**Issue by sylvain-8422** [ohler55/ox#269]
We are having strange encoding behaviours after updating to v2.14.3.

There is no issue using v2.14.2.

This fix broke something: 3e97ceab84e829bf9153daad9e9134173b85943f.

I can reproduce the problem using our application code.

I am working on a simple test case to clearly show the problem, but I still wanted to inform you early that something is probably very broken right now with v2.14.3.

I guess that this part should have stayed outside of the `else`, like it was before:

https://github.com/ohler55/ox/commit/3e97ceab84e829bf9153daad9e9134173b85943f#diff-fcfebda3410294505c9c78348d0f3c9fe926ae052832a312be1f8ff6d356857fL127-L129

**Comment by ohler55** [comment]
Thanks for the heads up. I'll take a look as well.

**Comment by sylvain-8422** [comment]
Ok, here is a way that I can show the difference between v2.14.2 and v2.14.3:

```
# Read from disk, as a binary file, pure ASCII (no characters beyond 7 bits).
xml = '<?xml version="1.0" encoding="UTF-8" ?><text>H&#233;ra&#239;dios</text>'
      .force_encoding(Encoding::ASCII_8BIT)
```

### v2.14.2

```
> text = Ox.load(xml).root.text
=> "Héraïdios"

> text.encoding
=> #<Encoding:UTF-8>
```

### v.2.14.3

```
> text = Ox.load(xml).root.text
=> "H\xE9ra\xEFdios"

> text.encoding
=> #<Encoding:ASCII-8BIT>

> text[0]
=> "H"

> text[1]
=> "\xE9"

> text[2]
=> "r"

> text[3]
=> "a"
```

v2.14.3 does not encode characters as UTF-8 like it did before.

We are using the `fieldhand` gem for OAI-PMH, that uses `ox`, and data is now filled with Chinese characters, when before it was producing valid UTF-8.

**Comment by ohler55** [comment]
Great test case. I'll use that for testing.

**Comment by ohler55** [comment]
The `encoding-re-fix` branch has the fix. Please check and I'll release.

**Comment by sylvain-8422** [comment]
It works great! Thank you! 👍

**Comment by ohler55** [comment]
Released
