### ISSUE TITLE
Various thoughts

### ISSUE THREAD

**Issue by sandstrom** [ohler55/ox#271]
Thanks for an awesome gem! 🏅 

A few thoughts:

 - [x] 1. How about removing the 'projects' and 'wiki' tabs, since they aren't used?
 - [x] 2. Have you thought about enabling discussions in this repo? Can be quite useful to e.g. deflect Q/A stuff from issues (things like this 🙃)
 - [x] 3. Are the files in misc still relevant, e.g. `/misc/load_cfg.rb`? Looks somewhat outdated, but I may be totally wrong.
 - [x] 4. There seems to be a `Builder` class (https://github.com/ohler55/ox/blob/develop/ext/ox/builder.c), but I can't find any documentation on how to use it. Is that an internal class, or something that's public?
 - [ ] 5. When using the generic XML writing capability (https://github.com/ohler55/ox#generic-xml-writing-and-parsing), I'm guessing it's still holding everything in memory? 
    
    Has there been any discussion on using a streaming writer instead?
    
    Most large XML documents usually aren't very "deep", so when writing a document sequentially (streaming write), at any point there are rarely more than 5-10 "open" tags. Maybe it would be alright if the ruby layer only kept the currently open tags in memory, and wrote everything else to disk (to keep memory usage down when generating large documents).
    
    Not sure it's a good idea though, just wanted to put it out there. Ox already seems to be very efficient:
    https://medium.com/neuronio/generating-xml-in-ruby-builder-vs-nokogiri-vs-libxml-vs-ox-757ce2d8f83c

**Comment by ohler55** [comment]
The projects and wiki just appeared without my configuring them. I'll check on how to remove them If you have some pointers on how to do items 1 and 2 that would help.

I have not heard any discussion about a streaming writer.

**Comment by sandstrom** [comment]
Thanks for answering!

You enable them under https://github.com/ohler55/ox/settings

**Comment by ohler55** [comment]
All are good suggestions. I'll see what I can do.

**Comment by ohler55** [comment]
Checking off the items one at a time. If you would like to start a discussion or two that would be great. Maybe one with the medium article.

**Comment by ohler55** [comment]
Ox::Builder docs fixed.

**Comment by ohler55** [comment]
load_cfg.rb was removed from misc. The dtd was left in place as were the two sample XML file so that people have some example to play with.

**Comment by ohler55** [comment]
With the addition of the discussion topic [Streaming Writer](https://github.com/ohler55/ox/discussions/273) I think this issue can be closed.

**Comment by sandstrom** [comment]
Awesome! 💯 Yeah, feel free to close.

A few more minor things:

- Maybe drop https://github.com/ohler55/ox/blob/develop/notes if it isn't used for anything, or move to an issue?
- Maybe move `sax_benchmark` into /misc?
- Consider removing https://github.com/ohler55/ox/blob/develop/contrib/builder.rb and builder_test, since they are easily confused with `http://www.ohler.com/ox/Ox/Builder.html` (the real Ox Builder).

**Comment by ohler55** [comment]
Thanks for the suggestions. The note file are notes to myself. Misc might be a better place for it. That or nothing-to-see-here directory. :-)

**Comment by ohler55** [comment]
* Moved notes
 * Left sax_benchmark since it is a contribution
 * Renamed contrib/builder.
