### ISSUE TITLE
Single carriage return is not converted to line feed

### ISSUE THREAD

**Issue by abicky** [ohler55/ox#282]
As described on https://www.w3.org/TR/2008/REC-xml-20081126/#sec-line-ends, a single carriage return should be converted to a line feed, but ox doesn't convert it. Is this behavior expected?
Actually, other XML libraries such as nokogiri and rexml convert it:

```ruby
require 'nokogiri'
require 'ox'
require 'rexml'

class Handler
  def text(value)
    p value
  end
  alias_method :characters, :text

  def method_missing(*args); end
end

xml = "<xml><value>foo\rbar</value></xml>"
handler = Handler.new

puts '== nokogiri =='
Nokogiri::XML::SAX::Parser.new(handler).parse(xml)
puts '== rexml =='
REXML::Parsers::StreamParser.new(REXML::Source.new(xml), handler).parse
puts '== ox with skip_return =='
Ox.sax_parse(handler, xml, { skip: :skip_return })
puts '== ox with skip_white =='
Ox.sax_parse(handler, xml, { skip: :skip_white })
```

The output is here:

```
== nokogiri ==
"foo"
"\nbar"
== rexml ==
"foo\nbar"
== ox with skip_return ==
"foo\rbar"
== ox with skip_white ==
"foo bar"
```

**Comment by ohler55** [comment]
What was the setting of the `:skip` option? That is used to control how the parser treats white space.

**Comment by ohler55** [comment]
It does look like Ox should convert `\r` to `\n` in all cases other than the `:skip_none` or `:skip_off` options. I'll schedule the issue into my work load.

**Comment by abicky** [comment]
Thank you for your quick response and consideration! I'm looking forward to it.

**Comment by ohler55** [comment]
I'm going to put this issue as secondary to the cache improvements that are already in the works. I'll put more effort into getting that done though.

**Comment by ohler55** [comment]
Please try the "sax-cache" branch. I believe the issue is fixed there.

**Comment by ohler55** [comment]
Released

**Comment by ohler55** [comment]
Can this be closed?

**Comment by abicky** [comment]
I'm sorry for my late reply. I tried the latest version, but the output hasn't changed as follows:

```
Ox::VERSION: 2.14.8
== nokogiri ==
"foo"
"\nbar"
== rexml ==
"foo\nbar"
== ox with skip_return ==
"foo\rbar"
== ox with skip_white ==
"foo bar"
```

As you can see above, the single carriage return remains when Ox parses the XML string with skip_return, whereas other parsers replace it with a linefeed.

Here is the script I executed:

```ruby
require 'nokogiri'
require 'ox'
require 'rexml'

class Handler
  def text(value)
    p value
  end
  alias_method :characters, :text

  def method_missing(*args); end
end

xml = "<xml><value>foo\rbar</value></xml>"
handler = Handler.new

puts "Ox::VERSION: #{Ox::VERSION}"

puts '== nokogiri =='
Nokogiri::XML::SAX::Parser.new(handler).parse(xml)
puts '== rexml =='
REXML::Parsers::StreamParser.new(REXML::Source.new(xml), handler).parse
puts '== ox with skip_return =='
Ox.sax_parse(handler, xml, { skip: :skip_return })
puts '== ox with skip_white =='
Ox.sax_parse(handler, xml, { skip: :skip_white })
```

**Comment by abicky** [comment]
According to [your comment](https://github.com/ohler55/ox/issues/282#issuecomment-1005279918), you intended to convert `\r` to `\n` when the skip option is neither `:skip_none` nor `:skip_off`, but you seemed to have changed Ox to convert `\r` to `\n` if the skip option is `:skip_none` or `:skip_off` because the commit https://github.com/ohler55/ox/pull/285/commits/3f1ad6d5a93a2b3519773579a14a8abf7415233a changed the test results in those cases.

**Comment by ohler55** [comment]
I see. Right, the skip return should also skip `\r`. I'll fix that.

**Comment by ohler55** [comment]
The SAX parser was not updated. Doing that now.

**Comment by ohler55** [comment]
Please try the "sax-newline-fix" branch.

**Comment by abicky** [comment]
I've confirmed Ox converts `\r` to `\n` 👍 

```
% git switch sax-newline-fix
Switched to branch 'sax-newline-fix'
Your branch is up to date with 'origin/sax-newline-fix'.
% cd ext/ox
% ruby extconf.rb
>>>>> Creating Makefile for ruby version 3.0.2 on x86_64-darwin20 <<<<<
checking for rb_time_timespec()... yes
checking for rb_struct_alloc_noinit()... yes
checking for rb_obj_encoding()... yes
checking for rb_ivar_foreach()... yes
checking for rb_ext_ractor_safe() in ruby.h... yes
checking for pthread_mutex_init()... yes
checking for rb_enc_interned_str()... yes
checking for rb_time_nano_new()... yes
checking for index()... yes
checking for ruby/st.h... yes
checking for sys/uio.h... yes
checking for struct tm.tm_gmtoff... yes
creating Makefile
% make
compiling base64.c
compiling builder.c
compiling cache.c
compiling cache8.c
compiling dump.c
compiling err.c
compiling gen_load.c
compiling hash_load.c
compiling intern.c
compiling obj_load.c
compiling ox.c
compiling parse.c
compiling sax.c
compiling sax_as.c
compiling sax_buf.c
compiling sax_hint.c
compiling slotcache.c
compiling special.c
linking shared-object ox.bundle
% cd ../..
% ruby -Iext -Ilib /path/to/script.rb
Ox::VERSION: 2.14.9
== nokogiri ==
"foo"
"\nbar"
== rexml ==
"foo\nbar"
== ox with skip_return ==
"foo\nbar"
== ox with skip_white ==
"foo bar"
```

**Comment by ohler55** [comment]
Great, thanks. I'll release then.

**Comment by ohler55** [comment]
Released

**Comment by abicky** [comment]
Thank you for releasing the latest version, which resolves this issue. I've also confirmed the behavior with the latest version.
