### ISSUE TITLE
Process XML with instructions longer than 1024 characters.

### ISSUE THREAD

**Issue by AnnaKL** [ohler55/ox#284]
We have a problem with processing some XML files with Ox. The error we're getting from `load` method is 
`Ox::ParseError:
       processing instruction content too large or not terminated at line 14393, column 47 [parse.c:255]`

We confirmed that XML is valid and we were able to process is with different parser.
It looks like there is a [size limit](https://github.com/ohler55/ox/blob/59c4234fe01fb5de08d49b39ecf5fc7338c1ffdc/ext/ox/parse.c#L237) instruction can have in order for Ox to be able to parse it.
Could we exceed this limit or make it configurable maybe via `default_options` ?
Our current use case contains instruction of over 4000 chars.

**Comment by ohler55** [comment]
The size limit is used to determine if the data is allocated on the stack or the heap. Ox should definitely handle much larger files. Are you able to share the XML that is breaking Ox? Maybe in a gist?

**Comment by AnnaKL** [comment]
Thanks a lot for quick response. The gist with record causing this issue can be found [here ](https://gist.github.com/AnnaKL/d0a928dcd3cba222f5154ba26ad80a03).
The issue is not related to the size of the file. That's why this file is very short with just one record. 
It's caused by the size of `<?MML` on line 88. If I make it shorter to the size of the one on line 67 it parses without a problem.

**Comment by ohler55** [comment]
I haven't seen the use of processing instructions like that before. I'll get Ox updated to handle the longer MML processing instructions.

**Comment by AnnaKL** [comment]
Great news. Thanks a lot.

**Comment by ohler55** [comment]
Please try the "sax-cache" branch. It has a fix candidate.

**Comment by AnnaKL** [comment]
We've had a problem with installing gem with that branch. We think there is missing `<stdbool.h>` in `parse.c`.
We added it and successfully parsed the file with long instruction 💯

**Comment by ohler55** [comment]
Thanks, I'll update.

**Comment by ohler55** [comment]
Updated and released.

**Comment by AnnaKL** [comment]
That's very helpful. Thank you very much.
