### ISSUE TITLE
RESX XML parsing - support for xml:space="preserve"

### ISSUE THREAD

**Issue by fahseltc** [ohler55/ox#287]
I am trying to parse a RESX formatted file, which is based on XML and used in C#. These files are generally used for localization of strings.
I have a user who wishes to upload a RESX formatted file with whitespace inside an element as follows:
`<data name="SecureDocumentsIntroText" xml:space="preserve">
    <value>This file came from another computer or the internet. DYN_GENERIC_SUITE_NAME has opened it securely to keep you safe.`

`DYN_GENERIC_SUITE_NAME opens files that pose a risk to your computer in a secure container. The file can be used as normal. If the file contains a virus DYN_GENERIC_SUITE_NAME will block it and let you know.</value>
    <comment>DYN_GENERIC_SUITE_NAME will be replaced with the product name.</comment>
  </data>`

In notepad, there appears to be CRLF characters present in the empty whitespace, but when parsed with OX, all of the whitespace is stripped.
In the XML format specification, they mention the use of the xml:space="preserve" and how it should function (https://www.w3.org/TR/xml/#sec-white-space). Ox does not seem to heed this and there doesn't appear to be any option I can pass in to make it behave this way.

Here is a code snippet I am using to parse the file
`doc = Ox.load_file(@file.to_s)
 keys = doc.locate("root/data/@name")
 values = doc.locate("root/data/value/*")`

`[1] pry(#<ResxImporter>)> value
=> "This file came from another computer or the internet. DYN_GENERIC_SUITE_NAME has opened it securely to keep you safe. DYN_GENERIC_SUITE_NAME opens files that pose a risk to your computer in a secure container. The file can be used as normal. If the file contains a virus DYN_GENERIC_SUITE_NAME will block it and let you know."`

I would guess that OX would return something like a \n character or otherwise preserve the whitespace. Thanks for looking and feel free to reach out.

**Comment by ohler55** [comment]
Have you tried the skip options? Ox supports several different whitespace preservation modes.

**Comment by ohler55** [comment]
Did that work for you? Can this be closed?
