### ISSUE TITLE
[BUG] Bus Error (crashes ruby when using more than 16458 characters in a field)

### ISSUE THREAD

**Issue by xtr3me** [ohler55/ox#289]
Hi Peter,

I'm currently working to migrate my existing XML builder (Nokogiri) to Ox and came across an issue which crashes the Ruby process.

```
[BUG] Bus Error at 0x00000022be83de18
ruby 2.6.5p114 (2019-10-01 revision 67812) [-darwin20]
```

I've managed to reduce the example to the following code:
```
require 'ox'

example_data = 'a' * 16459
Ox::Builder.file('./ox_result.xml', :indent => 2) do |xml|
  xml.cdata example_data
end
```

When using 16458 characters this example succeeds without any issue, but when adding 1 extra character (16459) it will crash the Ruby process.

I have tried this example case on Ruby 2.6.5 and 3.1.1 using an Apple m1 mac and an Intel mac using Ox version 2.14.9

```
[BUG] Segmentation fault at 0x00007fef6ffc1818
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]
```

Is there a predefined limit I need to adhere to or is this a bug?

**Comment by ohler55** [comment]
It's a bug. I'll get it fixed.

**Comment by ohler55** [comment]
Please check the "builder-long" branch. If it works for you I'll release.

**Comment by xtr3me** [comment]
It works flawlessly now, thank you very much for solving this

**Comment by ohler55** [comment]
I'll release today then.

**Comment by ohler55** [comment]
Released!
