### ISSUE TITLE
Ox.load result changes after parsing specific xml.

### ISSUE THREAD

**Issue by yutakuroda** [ohler55/ox#291]
Hello, Thank you for developing the great xml parser.

I notice Ox.load result changes after parsing specific xml.
There are examples.

```ruby
require 'ox'

xml1 = '<foo var="1"></foo>'
xml2 = '<hoge fuga="1"></hoge>'

Ox.load(xml1)
p Ox.load(xml2)
# #<Ox::Element:0x0000000002267ad0 @value="hoge", @attributes={:fuga=>"1"}, @nodes=[]>
```

```ruby
require 'ox'

xml1 = '<foo></foo>'
xml2 = '<hoge fuga="1"></hoge>'

Ox.load(xml1)
p Ox.load(xml2)
# #<Ox::Element:0x0000000002f46620 @value="hoge", @nodes=[], @attributes={:fuga=>"1"}>
# the order of @nodes and @attributes is changed!
```

The specific xml conditions I found are below
- with end tag.
  - ok: `<foo></foo>`
  - ng: `<foo/>`
- without any attributes in the root element.
  - ok: `<foo></foo>`
  - ng: `<foo var="1"></foo>`

ox version: 2.14.9
environment: Docker(docker image is: lambci/lambda:build-ruby2.7)

**Comment by ohler55** [comment]
Sorry I missed this one. What do you mean the order has changed? Are you referring to the way Ruby displays the Ox::Element instance? If so Ox has no control over that.

**Comment by yutakuroda** [comment]
Yes, I said about the way Ruby displays. I understood this is not the matter of Ox.
I'll check it a bit more. Thank you for your replay
