### ISSUE TITLE
Sax parser segfault in v2.14.7+

### ISSUE THREAD

**Issue by bryanp** [ohler55/ox#292]
Hitting an issue with ox v2.14.7 and greater on Ruby 3.1.1. Here's some sample code:

```ruby
require "stringio"
require "ox"

class Sample < ::Ox::Sax
  def attr(name, value); end
end

handler = Sample.new
Ox.sax_parse(handler, StringIO.new("<input disabled>"))
```

The issue occurs when the `attr` callback is defined and the content has an attribute defined without a value. Works fine on 2.14.6. Crash logs here: https://gist.github.com/bryanp/4d46146454cbde58dadad7f7fc704bd3

**Comment by ohler55** [comment]
I'll take a look and get it fixed.

**Comment by ohler55** [comment]
Please try the missing-attr-value branch.

**Comment by ohler55** [comment]
Great, I'll release tomorrow.
