### ISSUE TITLE
Sax parsing with default encoding set to UTF-8 breaks Ox::Sax#text

### ISSUE THREAD

**Issue by matheussilvasantos** [ohler55/ox#294]
When I run the script:

```ruby
xml = <<XML
  <a>ó</a>
  <b>42.42</b>
  <c>FOOBAR</c>
  <d>foobar</d>
XML

require "ox"

class A < Ox::Sax
  def text(value)
    p value
  end
end

handler = A.new
Ox.sax_parse(handler, xml)
```

It outputs:

```
"\xC3\xB3"
"42.42"
"FOOBAR"
"foobar"
```

When I add `Ox.default_options = { encoding: "UTF-8" }` to the script, it outputs:

```
"  "
"ó"
"\n  "
"42.42"
"\n  "
"FOOBAR"
"\n  "
"foobar"
```

**Comment by matheussilvasantos** [comment]
I just saw the `skip` option. `Ox.default_options = { encoding: "UTF-8", skip: :skip_return }` made it work for me. I'll close this issue for now.

**Comment by ohler55** [comment]
Great. Solved before I could even react to it.
