### ISSUE TITLE
cannot load such file -- ox/ox

### ISSUE THREAD

**Issue by sobrinho** [ohler55/ox#302]
Hapenning only on CI so I'm not sure why:

```
Traceback (most recent call last):
	23: from ./scripts/run-rubocop.rb:9:in `<main>'
	22: from ./scripts/run-rubocop.rb:9:in `require_relative'
	21: from /root/app-api/config/environment.rb:3:in `<top (required)>'
	20: from /root/app-api/config/environment.rb:3:in `require_relative'
	19: from /root/app-api/config/application.rb:20:in `<top (required)>'
	18: from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler.rb:176:in `require'
	17: from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `require'
	16: from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `each'
	15: from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `block in require'
	14: from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `each'
	13: from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	12: from /root/app-api/vendor/gems/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	11: from /root/app-api/vendor/gems/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	10: from /root/app-api/vendor/gems/ruby/2.7.0/bundler/gems/address_validate-37b1788476f3/lib/address_validate.rb:7:in `<main>'
	 9: from /root/app-api/vendor/gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
	 8: from /root/app-api/vendor/gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 7: from /root/app-api/vendor/gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
	 6: from /root/app-api/vendor/gems/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 5: from /root/app-api/vendor/gems/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 4: from /root/app-api/vendor/gems/ruby/2.7.0/gems/ox-2.14.11/lib/ox.rb:79:in `<main>'
	 3: from /root/app-api/vendor/gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
	 2: from /root/app-api/vendor/gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 1: from /root/app-api/vendor/gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/root/app-api/vendor/gems/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- ox/ox (LoadError)

Exited with code exit status 1
CircleCI received exit code 1
```

Happens on absolutely any try to boot the app.

**Comment by sobrinho** [comment]
```
# ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]

# gem install ox
Fetching ox-2.14.11.gem
Building native extensions. This could take a while...
Successfully installed ox-2.14.11
1 gem installed

# irb
irb(main):001:0> gem 'ox', '2.14.11'
=> true
irb(main):002:0> require 'ox'
Traceback (most recent call last):
        9: from /usr/local/bin/irb:23:in `<main>'
        8: from /usr/local/bin/irb:23:in `load'
        7: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        6: from (irb):2
        5: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        4: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        3: from /usr/local/bundle/gems/ox-2.14.11/lib/ox.rb:79:in `<top (required)>'
        2: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        1: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
LoadError (cannot load such file -- ox/ox)
```

**Comment by sobrinho** [comment]
Works fine on docker, so, something might be messed up on CircleCI, but still not sure how to debug:

```
$ docker run --rm -it --platform=linux/amd64 ruby:2.7.6-buster bash
Unable to find image 'ruby:2.7.6-buster' locally
2.7.6-buster: Pulling from library/ruby
2730d739afad: Pull complete
a122751b3533: Pull complete
0a277c3efe7c: Pull complete
25c35b81c503: Pull complete
cb8cde86ddb2: Pull complete
1b4693b2324f: Pull complete
558286cb3a23: Pull complete
ca7d15697c52: Pull complete
Digest: sha256:f2ba73c31b11be325121bc5018231e21e13348c3b3bc75be44e7a6568893f5c1
Status: Downloaded newer image for ruby:2.7.6-buster
root@de375efbf8e4:/# ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
root@de375efbf8e4:/# gem install ox
Fetching ox-2.14.11.gem
Building native extensions. This could take a while...
Successfully installed ox-2.14.11
1 gem installed
root@de375efbf8e4:/# irb
irb(main):001:0> gem 'ox', '2.14.11'
=> true
irb(main):002:0> require 'ox'
=> true
irb(main):003:0>
```

**Comment by ohler55** [comment]
What platform does Circle CI run on? Windows? Linux? MacOS?

**Comment by hsbt** [comment]
@sobrinho Can you try with ox-2.14.12? It seems same issue of https://github.com/ohler55/ox/issues/300. You may use the latest version of RubyGems in Ruby docker image.

**Comment by sobrinho** [comment]
It worked, nice, thanks! ❤️

**Comment by mihika52** [comment]
I'm having the same kind of error.I'm using a mac m1 pro.How to fix it?I have already installed ox gem and its showing true.However the rails s command is still not working.

mhingar@IN-MHINGAR-MBP enlighten % rails s
/Users/mhingar/rails/enlighten/vendor/gems/rails_sql_views-0.8.0/rails_sql_views.gemspec:72: warning: constant Gem::RubyGemsVersion is deprecated
/Users/mhingar/rails/enlighten/vendor/gems/rails_sql_views-0.8.0/rails_sql_views.gemspec:72: warning: constant Gem::RubyGemsVersion is deprecated
DEPRECATED: Please use restforce (https://github.com/ejholmes/restforce) instead.
Traceback (most recent call last):
	24: from bin/rails:4:in `<main>'
	23: from bin/rails:4:in `require'
	22: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	21: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	20: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	19: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	18: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	17: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	16: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
	15: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
	14: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	13: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:145:in `require'
	12: from /Users/mhingar/rails/enlighten/config/application.rb:15:in `<top (required)>'
	11: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	10: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
	 9: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
	 8: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
	 7: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
	 6: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	 5: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
	 4: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/ox-2.13.2/lib/ox.rb:79:in `<top (required)>'
	 3: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	 2: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/mhingar/.rvm/gems/ruby-2.6.5@enlighten_upgrade/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- ox/ox (LoadError)
