### ISSUE TITLE
Cleaning built artifacts after installation breaks macOS

### ISSUE THREAD

**Issue by lipidity** [ohler55/ox#303]
Recent rubygems now run [make clean](https://github.com/rubygems/rubygems/issues/3958) after installation so this breaks ox on macOS.

Same as https://github.com/ohler55/ox/issues/300 which was fixed in https://github.com/ohler55/ox/issues/301 but on macOS (arm64) the `ox.o` file seems to be needed at runtime -- there is no `ox.so`.

**Comment by hsbt** [comment]
`require` and `require_relative` will fallback `.bundle` with `.so` extension on macOS platform .

**Comment by hsbt** [comment]
see

```
$ ruby -v
ruby 3.3.0dev (2022-12-26T02:43:08Z master bb2c360138) +YJIT [arm64-darwin22]
$ gem i ox
Building native extensions. This could take a while...
Successfully installed ox-2.14.12
1 gem installed
$ irb
>> require "ox"
=> true
```

**Comment by lipidity** [comment]
Thank you for the response. I will check this tomorrow to confirm.

**Comment by lipidity** [comment]
Wiped everything and tried again -- it worked this time!

Thank you again, and sorry for the incorrect report.
