### ISSUE TITLE
Incorrect ` Start End Mismatch` exception in sax parser

### ISSUE THREAD

**Issue by dsander** [ohler55/ox#304]
HI! 👋 

We have noticed a very interesting bug that seemed random at first. When parsing certain XML files we are getting `Start End Mismatch: element 'Properties' closed but not opened` errors that are not correct (the XML is valid). What is more interesing ist that if we first parse a different XML the first one works without problems.

https://github.com/projectivetech/ox/tree/closed-but-no-opened-repro contains a reproduction. Clone the branch and execute `./reproduction.sh`. Note: we have to access the parsed nodes in the SAX handler not doing anything with the parsed data in ruby doesn'y seem to trigger the exception.

When [this line](https://github.com/projectivetech/ox/blob/closed-but-no-opened-repro/reproduction.rb#L48) is commented in the second XML parses successfully. 

By bisecting we found that https://github.com/ohler55/ox/commit/4326d9f19dff7fb577ee2ccf8afb213b02954561 is the commit that introduced the problem for us.

XML that does not work: https://github.com/projectivetech/ox/blob/closed-but-no-opened-repro/two.xml
XML that works (and fixes the parsing for the first one): https://github.com/projectivetech/ox/blob/closed-but-no-opened-repro/one.xml

Sorry that the files are so massive, slimmed down the offending XML a little bit but didn't get it to a size that can be pasted here.

**Comment by ohler55** [comment]
I'll take a look this weekend.

**Comment by ohler55** [comment]
It did not fail for me. I'm using an M1 Mac and ruby 3.1.0. What platform and ruby version are you using?

**Comment by dsander** [comment]
I initially tested it on x86-64 linux with ruby 3.0. It also fails on my intel macbook with ruby 3.1. Looks like it is only an issue on x86-64.

**Comment by ohler55** [comment]
I'll try on my linux box and see what I get.

**Comment by ohler55** [comment]
Fixed it! In older Ruby versions a symbol's backing string would not move. That is no longer true. I'll get the fix up this evening. I need to cleanup a bit and prepare a branch that you can review.

**Comment by dsander** [comment]
That is great news, thanks a lot!

**Comment by ohler55** [comment]
Please try the "symbol-move" branch.

**Comment by dsander** [comment]
Works perfectly, thanks again!

**Comment by ohler55** [comment]
Released.
