### ISSUE TITLE
Ruby 2.7.6 LoadError: cannot load such file -- ox/ox

### ISSUE THREAD

**Issue by r351574nc3** [ohler55/ox#305]
I am trying to `bundle exec rails assets:precompile` in my project that depends on ox `2.10.0`. The issue seems to be that ox is unable to load its C extension for some reason. This is the line causing the problem https://github.com/ohler55/ox/blob/f060f84b5cadcff209de4a517e6289d1a39fe87d/lib/ox.rb#L79

After some investigation, I found that this may solve my problem https://github.com/ohler55/ox/pull/301/files

Due to dependencies, I cannot change my version of `2.10.0` and I can't really upgrade my ruby version from `2.7.6`. Is there anything that can be done to get around this?

**Comment by ohler55** [comment]
I suspect that the ext director is not in your path or the ox.bundle file is not in the path. I'd focus on the paths. It's not an ox issue but a sub load/path issue.

**Comment by r351574nc3** [comment]
This build had been working fine for me. What changed was I removed `gem update --system` from my build.  It had been installing `rubygems-update-3.3.26`, but had recently started installing `rubygems-update-3.4.4` which is what has apparently led to my issue. My problem was solved by removing the gem from my build.

**Comment by mtomov** [comment]
Thanks @r351574nc3 for posting the issue and the reply! We had the same, and indeed removing `gem update --system` from the docker build soved it!

Thanks so much again! 🙌
