### ISSUE TITLE
segfault in 2.14.13 -- free(): invalid pointer Aborted (core dumped)

### ISSUE THREAD

**Issue by ianfloats** [ohler55/ox#307]
2.14.13 segfaults, 2.14.12 does not.  

Seen on ruby 2.7.7p221 and 3.0.5p211.

Sorry I don't have an isolated example or more debug output, and don't have time at the moment to generate it.   I'm hoping the "free(): invalid pointer" and relatively tiny change between 2.14.12 to 2.14.13 gives you enough to intuit the cause.

Seen in a Rails app when running test suite.  It triggered during random tests, unrelated to ox-using code, so I suspect it happens during garbage collection.

**Comment by ohler55** [comment]
I'll do some debugging.

**Comment by ianfloats** [comment]
Some stackoverflows and blogs mention using xfree instead of free.

> It is important to use xfree() to free the memory allocated by these calls. In the nominal case there isn't much difference between regular free() and xfree(), but if ruby is built a certain way, xfree() does some additional internal accounting.  (https://clalance.blogspot.com/2011/01/writing-ruby-extensions-in-c-part-12.html)

**Comment by ohler55** [comment]
Yeah, it was allocated with a ruby call. My mistake. Fixed in the develop branch. Will release tomorrow unless you test and it still fails.

**Comment by ohler55** [comment]
Released v2.14.14

**Comment by ianfloats** [comment]
Sorry to report that 2.14.14 segfaults also, in the same way.

**Comment by ohler55** [comment]
Can you give me anything else to go on such as a test that fails?

**Comment by ianfloats** [comment]
Apologies, didn't have the bandwidth to create an isolated test case last year.

2.14.15 fixed this segfault.

Thanks, Peter!
