### ISSUE TITLE
Verbose output of inspect

### ISSUE THREAD

**Issue by 23tux** [ohler55/ox#324]
I just started to play around with ox, and noticed that when parsing bigger XML documents, it's hard to navigate the parsed document just by looking at the `#inspect` output. This issue from 2013 mentions something similar: https://github.com/ohler55/ox/issues/39

The main pain point for me is that all the `@nodes` are listed _before_ the `@value` instance variable, which would define the name of the node. So when the list of `@nodes` is pretty long it always is cut off at the end of my screen, **and I have no idea what the name of the element is, because `@value` is listed below `@nodes`**:

```
doc = Ox::Document.new
samples = Ox::Element.new("samples").tap { |el| el[:test] = "test" }
doc << samples
100.times do
  samples << Ox::Element.new("sample")
end

doc
=> #<Ox::Document:0x0000000136a16af8
 @attributes={},
 @nodes=
  [#<Ox::Element:0x0000000136a16670
    @attributes={:test=>"test"},
    @nodes=
     [#<Ox::Element:0x0000000136a16260 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x0000000136a160d0 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x0000000136a15fe0 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x0000000136a15d38 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x0000000136a15950 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x0000000136a156a8 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x0000000136a14e10 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fbac8 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fb618 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fb258 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369faee8 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fabf0 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369faa10 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fa8f8 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fa740 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fa448 @attributes={}, @nodes=[], @value="sample">,
      #<Ox::Element:0x00000001369fa178 @attributes={}, @nodes=[], @value="sample">,
:
```

Would it be possible to move the `@value` variable to the front of `#inspect`?

And if I may suggest a second improvement: Most of the time the memory address is just noise, I think it would be helpful to have an option to disable it to get a better overview. Maybe this could be included in the `.default_options` like this:

```
Ox.default_options = {
  tidy_inspect: true
}
```

**Comment by ohler55** [comment]
The `#inspect` method is the default for all objects. It is not implemented by Ox. All I can suggest it implement what you prefer as a monkey patch in your project. It doesn't seem like an enhancement worth adding when the Ruby default is what implement `#inspect`.

**Comment by 23tux** [comment]
Thanks for your answer, that's sounds reasonable. As altering `#inspect` is really tricky, I tried another approach by patching `#initialize`:

As Ruby sorts it's instance variables A-Z, I tried adding a `@_value = value` variable to the constructor, so that it appears first when using `#inspect`.

Unfortunately, my patch is never called, maybe you can spot what's wrong with it:

```
Ox::Node.prepend(Module.new do
  def initialize(value)
    super
    @_value = value
  end
end)
doc = Ox.load_file("All Accounts.xml")
```

**Comment by ohler55** [comment]
Altering or over-riding #inspect is pretty easy. Probably easier than trying the hack with modules and an _value.

**Comment by 23tux** [comment]
Thanks, I tried it out and got some decent output going. Thanks for the help!
