### ISSUE TITLE
? in unquoted attribute value causes HTML to not be properly parsed

### ISSUE THREAD

**Issue by SpyMachine** [ohler55/ox#345]
Hi, I've run into a situation where an element is never seen by our SAX handler and it appears to be due to a query parameter in an attribute value in the element before it. The element is not quoted. According to the [HTML spec](https://html.spec.whatwg.org/multipage/introduction.html#intro-early-example), attribute values can be unquoted with a stipulation:

> [Attributes](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attributes) are placed inside the start tag, and consist of a [name](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name) and a [value](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-value), separated by an "=" character. The attribute value can remain [unquoted](https://html.spec.whatwg.org/multipage/syntax.html#unquoted) if it doesn't contain [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace) or any of " ' ` = < or >. Otherwise, it has to be quoted using either single or double quotes. The value, along with the "=" character, can be omitted altogether if the value is the empty string.

Taking the following example using some of the examples from the README:

```
require 'ox'

body = '<html>
<body>
  <iframe src=http://test.com?a=b></iframe>
  <input type="submit" id="test" />
</body>
</html>'

Ox.default_options = {
  mode: :generic,
  effort: :tolerant,
  smart: true
}

class Sample < ::Ox::Sax
  def start_element(name) = puts("start: #{name}")
  def end_element(name) = puts("end: #{name}")
  def attr(name, value) = puts("  #{name} => #{value}")
  def text(value) = puts("text #{value}")
end

handler = Sample.new
Ox.sax_parse(handler, body)
```

This skips the input element completely.

```
start: html
text 
start: body
text 
  
start: iframe
  src => http://test.com
end: iframe
end: body
end: html
```

This may make sense given the stipulation that the value cannot be quoted if it contains an "=". However, I still see the same issue if I remove the actual query parameter and just leave behind "<iframe src=http://test.com?>". Only until I remove the "?" is the input found.

In my situation, I have no control over the HTML so if it's possible, we'd really like to be able to handle the case with full query parameters. Perhaps something that could be handled with the "tolerant" setting? Funny enough, it works correctly if I leave the "=" and take out the "?".

**Comment by ohler55** [comment]
I'll look into it more this week. There should be something that can be done to handle it.

**Comment by ohler55** [comment]
Please try the "more-html-tolerant" branch. I also added a unit test at the end of sax/sax_test.rb.

**Comment by SpyMachine** [comment]
Yep, that works! Thanks Peter, always appreciate your fast response :)

**Comment by ohler55** [comment]
Released
