### ISSUE TITLE
Failed to build the gem native extension on JRuby

### ISSUE THREAD

**Issue by roque86** [ohler55/ox#362]
I was trying to check ox to see if it would improve marshal dump and load for my use case, but I could not install the gem because it failed to build the gem native extension.

Is jruby even supported?  
ruby '2.5.8', engine: 'jruby', version: '9.2.19.0'

```
Installing ox 2.14.14 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ox-2.14.14/ext/ox
/opt/jruby/bin/jruby -I /opt/jruby/lib/ruby/stdlib -r
./siteconf20241009-1309-1o49ssp.rb extconf.rb
>>>>> Creating Makefile for jruby version 2.5.8 on java <<<<<
NoMethodError: undefined method `slice!' for nil:NilClass
  <main> at extconf.rb:31
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

The above error is related to the CONFIG['warnflags'] slices in ox/extconf.rb. 

```
CONFIG['warnflags'].slice!(/ -Wsuggest-attribute=format/)
CONFIG['warnflags'].slice!(/ -Wdeclaration-after-statement/)
CONFIG['warnflags'].slice!(/ -Wmissing-noreturn/)
```

I could try to investigate it deeply, but I would appreciate any initial feedback to determine whether it is worth the trouble.

**Comment by ohler55** [comment]
Many years ago jruby stopped supporting C extensions. Since Ox is a C extension jruby does not support it.
