### ISSUE TITLE
feature request: sax push parser

### ISSUE THREAD

**Issue by notezen** [ohler55/ox#50]
Is it possible ?

**Comment by Zapotek** [comment]
I just found myself in need of this feature as well.

**Comment by Zapotek** [comment]
Not very efficient but does the job:

```ruby
buffer, buffer_in = IO.pipe

handler = MySAXHandler.new

Thread.new do
    Ox.sax_xml( document, buffer, sax_options )
end

buffer_in << '<parent><chi'
buffer_in << 'ld>some con'
buffer_in << 'tent</child></parent>'
buffer_in.close

# Do stuff with handler
```

**Comment by ohler55** [comment]
I prefer that over cooking something into Ox that does the same thing as a stream or pipe. You might be surprised how efficient it is.

**Comment by Zapotek** [comment]
Creating threads isn't efficient for this, for example in my case this can be called hundreds of times in series leaving me with that many short-lived threads which has substantial impact on resource utilization and performance.

Pushing directly to Ox seems like the cleaner way and push parsers are an established paradigm.

**Comment by ohler55** [comment]
Another approach would be to keep a longer running thread that services parse requests. This feature will take some time to get done. Right now the state of the parser is on the stack and not carried around in a ruby object. That would have to change for the parser to be reentrant. The solution may be to keep a thread in C to maintain the parser state but I have no idea what problems that would cause for Ruby.
