### ISSUE TITLE
how to put an url in the attribute of an element

### ISSUE THREAD

**Issue by littlell** [ohler55/ox#90]
just like,
when i set the attribute "http://www.baidu.com?a=b&c=d", the final result is "http://www.baidu.com?a=b&amp;c=d", it seems like the ox gem add a '&amp'
for me~
need help~

**Comment by davetchen** [comment]
Hi @ohler55, we are users of the AWS SDK via this gem

https://github.com/aws/aws-sdk-ruby

and would like to switch over to OX from Nokogiri to take advantage of your performance improvements. 

It looks like everything would work if we can enable :convert_special as a default in a Rails initializer/ox.rb file. I tried 
```
Ox.default_options = {convert_special: true}
```
But no luck. Thanks for taking a look! -dave

**Comment by ohler55** [comment]
The convert_special is an argument to the SAX parser and not currently in the defaults. It seems like it would make sense to add it to the defaults though. I'll get that done over the next day or two.

**Comment by ohler55** [comment]
Finished the change. On github the default options now include convert_special. Please give it a try.

**Comment by davetchen** [comment]
Is the change in 'master'? Could not find the commit.

**Comment by ohler55** [comment]
Should be there now. I didn't check the push had failed.

**Comment by ohler55** [comment]
Is it working for you?

**Comment by davetchen** [comment]
Looks like it is *always* doing the "convert_special" function now, even if the option is set to false. The function to change and retrieve the defaults via `Ox.default_options` does work for me.

**Comment by ohler55** [comment]
Thanks for checking. Fixed in and pushed.

**Comment by davetchen** [comment]
Looks like its working now, thanks for the quick turn! Please let me know when you do the next release.  Using the aws-sdk-v2:

<code>
> obj = s3.bucket("xxxxxx").objects.first
> obj.etag
 => "&quot;03839134ac50414adae3c548119f40b0&quot;" 

> Ox.default_options = {convert_special: true}
 => {:convert_special=>true}

> obj = s3.bucket("xxxxxx").objects.first
> obj.etag
 => "\"03839134ac50414adae3c548119f40b0\"" 
<\code>

**Comment by ohler55** [comment]
released
