### ISSUE TITLE
question: how locate by attribute value?

### ISSUE THREAD

**Issue by vad4msiu** [ohler55/ox#98]
If I have a xml:

```
<?xml?>
<People>
  <Person age="58">
    <given>Peter</given>
    <surname>Ohler</surname>
  </Person>
  <Person>
    <given>Makie</given>
    <surname>Ohler</surname>
  </Person>
</People>
```

Can I locate only Person with age="58" ?
I thought do it like this:

``` ruby
doc.locate("People/Person[@age='58']")
```

But it doesn't work.

**Comment by isaiah** [comment]
Delete the gem please, it's not a "optimised" XML parser, it's a handicapped one.

**Comment by ohler55** [comment]
If don't a gem useful there is no reason to be an ass about it. The gem is not being deleted any tie soon.
