### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by aabes** [ohler55/ox#99]
Trying to build on JRuby 1.7.12, getting:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

.rvm/rubies/jruby-1.7.12/bin/jruby extconf.rb 
.rvm/rubies/jruby-1.7.12/lib/ruby/shared/mkmf.rb:14: Use RbConfig instead of obsolete and deprecated Config.
mkmf.rb can't find header files for ruby at .rvm/rubies/jruby-1.7.12/lib/native/include/ruby/ruby.h

**Comment by oshanz** [comment]
@ohler55 I don't know about JRuby C integration. I read there is some thing called `FFI bindings` on JRuby instead of C extensions.

**Comment by ohler55** [comment]
I'll look into it, thanks.
